// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"

	"entgo.io/contrib/entgqlgo/internal/todo/ent/billproduct"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
)

// BillProductUpdate is the builder for updating BillProduct entities.
type BillProductUpdate struct {
	config
	hooks    []Hook
	mutation *BillProductMutation
}

// Where appends a list predicates to the BillProductUpdate builder.
func (_u *BillProductUpdate) Where(ps ...predicate.BillProduct) *BillProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BillProductUpdate) SetName(v string) *BillProductUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BillProductUpdate) SetNillableName(v *string) *BillProductUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSku sets the "sku" field.
func (_u *BillProductUpdate) SetSku(v string) *BillProductUpdate {
	_u.mutation.SetSku(v)
	return _u
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_u *BillProductUpdate) SetNillableSku(v *string) *BillProductUpdate {
	if v != nil {
		_u.SetSku(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *BillProductUpdate) SetQuantity(v int) *BillProductUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *BillProductUpdate) SetNillableQuantity(v *int) *BillProductUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *BillProductUpdate) AddQuantity(v int) *BillProductUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// Mutation returns the BillProductMutation object of the builder.
func (_u *BillProductUpdate) Mutation() *BillProductMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BillProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BillProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillProductUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := billproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BillProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sku(); ok {
		if err := billproduct.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "BillProduct.sku": %w`, err)}
		}
	}
	return nil
}

var billproductUpdateDescriptor = entbuilder.UpdateDescriptor[config, *BillProductMutation]{
	Fields: []entbuilder.UpdateFieldDescriptor[*BillProductMutation]{
		{
			Column: billproduct.FieldName,
			Type:   field.TypeString,
			Set: func(m *BillProductMutation) (driver.Value, bool, error) {
				if value, ok := m.Name(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},

		{
			Column: billproduct.FieldSku,
			Type:   field.TypeString,
			Set: func(m *BillProductMutation) (driver.Value, bool, error) {
				if value, ok := m.Sku(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},

		{
			Column: billproduct.FieldQuantity,
			Type:   field.TypeInt,
			Set: func(m *BillProductMutation) (driver.Value, bool, error) {
				if value, ok := m.Quantity(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
			Add: func(m *BillProductMutation) (driver.Value, bool, error) {
				if value, ok := m.AddedQuantity(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},
	},
	Edges: []entbuilder.UpdateEdgeDescriptor[config, *BillProductMutation]{},
}

func (_u *BillProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billproduct.Table, billproduct.Columns, sqlgraph.NewFieldSpec(billproduct.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if err := entbuilder.ApplyUpdate(_u.config, _u.mutation, &billproductUpdateDescriptor, _spec); err != nil {
		return 0, err
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BillProductUpdateOne is the builder for updating a single BillProduct entity.
type BillProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BillProductMutation
}

// SetName sets the "name" field.
func (_u *BillProductUpdateOne) SetName(v string) *BillProductUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BillProductUpdateOne) SetNillableName(v *string) *BillProductUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSku sets the "sku" field.
func (_u *BillProductUpdateOne) SetSku(v string) *BillProductUpdateOne {
	_u.mutation.SetSku(v)
	return _u
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (_u *BillProductUpdateOne) SetNillableSku(v *string) *BillProductUpdateOne {
	if v != nil {
		_u.SetSku(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *BillProductUpdateOne) SetQuantity(v int) *BillProductUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *BillProductUpdateOne) SetNillableQuantity(v *int) *BillProductUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *BillProductUpdateOne) AddQuantity(v int) *BillProductUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// Mutation returns the BillProductMutation object of the builder.
func (_u *BillProductUpdateOne) Mutation() *BillProductMutation {
	return _u.mutation
}

// Where appends a list predicates to the BillProductUpdate builder.
func (_u *BillProductUpdateOne) Where(ps ...predicate.BillProduct) *BillProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BillProductUpdateOne) Select(field string, fields ...string) *BillProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BillProduct entity.
func (_u *BillProductUpdateOne) Save(ctx context.Context) (*BillProduct, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BillProductUpdateOne) SaveX(ctx context.Context) *BillProduct {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BillProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BillProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BillProductUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := billproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "BillProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Sku(); ok {
		if err := billproduct.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "BillProduct.sku": %w`, err)}
		}
	}
	return nil
}

func (_u *BillProductUpdateOne) sqlSave(ctx context.Context) (_node *BillProduct, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(billproduct.Table, billproduct.Columns, sqlgraph.NewFieldSpec(billproduct.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BillProduct.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, billproduct.FieldID)
		for _, f := range fields {
			if !billproduct.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != billproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if err := entbuilder.ApplyUpdate(_u.config, _u.mutation, &billproductUpdateDescriptor, _spec); err != nil {
		return nil, err
	}
	_node = &BillProduct{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{billproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
