// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"

	"entgo.io/contrib/entgqlgo/internal/todo/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/predicate"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/todo"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CategoryUpdate is the builder for updating Category entities.
type CategoryUpdate struct {
	config
	hooks    []Hook
	mutation *CategoryMutation
}

// Where appends a list predicates to the CategoryUpdate builder.
func (_u *CategoryUpdate) Where(ps ...predicate.Category) *CategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *CategoryUpdate) SetText(v string) *CategoryUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableText(v *string) *CategoryUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CategoryUpdate) SetStatus(v category.Status) *CategoryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableStatus(v *category.Status) *CategoryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *CategoryUpdate) SetKind(v category.Kind) *CategoryUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableKind(v *category.Kind) *CategoryUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetConfigType sets the "config_type" field.
func (_u *CategoryUpdate) SetConfigType(v category.ConfigType) *CategoryUpdate {
	_u.mutation.SetConfigType(v)
	return _u
}

// SetNillableConfigType sets the "config_type" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableConfigType(v *category.ConfigType) *CategoryUpdate {
	if v != nil {
		_u.SetConfigType(*v)
	}
	return _u
}

// ClearConfigType clears the value of the "config_type" field.
func (_u *CategoryUpdate) ClearConfigType() *CategoryUpdate {
	_u.mutation.ClearConfigType()
	return _u
}

// SetTags sets the "tags" field.
func (_u *CategoryUpdate) SetTags(v []string) *CategoryUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *CategoryUpdate) AppendTags(v []string) *CategoryUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *CategoryUpdate) ClearTags() *CategoryUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetConfig sets the "config" field.
func (_u *CategoryUpdate) SetConfig(v map[string]string) *CategoryUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *CategoryUpdate) ClearConfig() *CategoryUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CategoryUpdate) SetExternalID(v uuid.UUID) *CategoryUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CategoryUpdate) SetNillableExternalID(v *uuid.UUID) *CategoryUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *CategoryUpdate) ClearExternalID() *CategoryUpdate {
	_u.mutation.ClearExternalID()
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *CategoryUpdate) SetAttributes(v map[string]interface{}) *CategoryUpdate {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *CategoryUpdate) ClearAttributes() *CategoryUpdate {
	_u.mutation.ClearAttributes()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *CategoryUpdate) SetPayload(v []byte) *CategoryUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *CategoryUpdate) ClearPayload() *CategoryUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// AddTodoIDs adds the "todos" edge to the Todo entity by IDs.
func (_u *CategoryUpdate) AddTodoIDs(ids ...int) *CategoryUpdate {
	_u.mutation.AddTodoIDs(ids...)
	return _u
}

// AddTodos adds the "todos" edges to the Todo entity.
func (_u *CategoryUpdate) AddTodos(v ...*Todo) *CategoryUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTodoIDs(ids...)
}

// Mutation returns the CategoryMutation object of the builder.
func (_u *CategoryUpdate) Mutation() *CategoryMutation {
	return _u.mutation
}

// ClearTodos clears all "todos" edges to the Todo entity.
func (_u *CategoryUpdate) ClearTodos() *CategoryUpdate {
	_u.mutation.ClearTodos()
	return _u
}

// RemoveTodoIDs removes the "todos" edge to Todo entities by IDs.
func (_u *CategoryUpdate) RemoveTodoIDs(ids ...int) *CategoryUpdate {
	_u.mutation.RemoveTodoIDs(ids...)
	return _u
}

// RemoveTodos removes "todos" edges to Todo entities.
func (_u *CategoryUpdate) RemoveTodos(v ...*Todo) *CategoryUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTodoIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CategoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CategoryUpdate) check() error {
	if v, ok := _u.mutation.Text(); ok {
		if err := category.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Category.text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := category.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Category.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := category.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Category.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigType(); ok {
		if err := category.ConfigTypeValidator(v); err != nil {
			return &ValidationError{Name: "config_type", err: fmt.Errorf(`ent: validator failed for field "Category.config_type": %w`, err)}
		}
	}
	return nil
}

var categoryUpdateDescriptor = entbuilder.UpdateDescriptor[config, *CategoryMutation]{
	Fields: []entbuilder.UpdateFieldDescriptor[*CategoryMutation]{
		{
			Column: category.FieldText,
			Type:   field.TypeString,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.Text(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},

		{
			Column: category.FieldStatus,
			Type:   field.TypeEnum,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.Status(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},

		{
			Column: category.FieldKind,
			Type:   field.TypeEnum,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.Kind(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},

		{
			Column: category.FieldConfigType,
			Type:   field.TypeEnum,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.ConfigType(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
			Clear: func(m *CategoryMutation) bool {
				return m.ConfigTypeCleared()
			},
		},

		{
			Column: category.FieldTags,
			Type:   field.TypeJSON,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.Tags(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
			Append: func(m *CategoryMutation) (func(*sql.UpdateBuilder), bool, error) {
				if value, ok := m.AppendedTags(); ok {
					return func(u *sql.UpdateBuilder) {
						sqljson.Append(u, category.FieldTags, value)
					}, true, nil
				}
				return nil, false, nil
			},
			Clear: func(m *CategoryMutation) bool {
				return m.TagsCleared()
			},
		},

		{
			Column: category.FieldConfig,
			Type:   field.TypeJSON,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.Config(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
			Clear: func(m *CategoryMutation) bool {
				return m.ConfigCleared()
			},
		},

		{
			Column: category.FieldExternalID,
			Type:   field.TypeUUID,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.ExternalID(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
			Clear: func(m *CategoryMutation) bool {
				return m.ExternalIDCleared()
			},
		},

		{
			Column: category.FieldAttributes,
			Type:   field.TypeJSON,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.Attributes(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
			Clear: func(m *CategoryMutation) bool {
				return m.AttributesCleared()
			},
		},

		{
			Column: category.FieldPayload,
			Type:   field.TypeBytes,
			Set: func(m *CategoryMutation) (driver.Value, bool, error) {
				if value, ok := m.Payload(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
			Clear: func(m *CategoryMutation) bool {
				return m.PayloadCleared()
			},
		},
	},
	Edges: []entbuilder.UpdateEdgeDescriptor[config, *CategoryMutation]{
		{
			Clear: func(cfg config, m *CategoryMutation) (*sqlgraph.EdgeSpec, bool, error) {
				if m.TodosCleared() {
					edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
						Rel:          sqlgraph.O2M,
						Inverse:      false,
						Table:        category.TodosTable,
						Columns:      category.TodosColumn,
						Bidi:         false,
						TargetColumn: todo.FieldID,
						TargetType:   field.TypeInt,
					})
					return edge, true, nil
				}
				return nil, false, nil
			},
			Remove: func(cfg config, m *CategoryMutation) ([]*sqlgraph.EdgeSpec, error) {
				nodes := m.RemovedTodosIDs()
				if len(nodes) == 0 || m.TodosCleared() {
					return nil, nil
				}
				edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
					Rel:          sqlgraph.O2M,
					Inverse:      false,
					Table:        category.TodosTable,
					Columns:      category.TodosColumn,
					Bidi:         false,
					TargetColumn: todo.FieldID,
					TargetType:   field.TypeInt,
				})
				for _, id := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, id)
				}
				return []*sqlgraph.EdgeSpec{edge}, nil
			},
			Add: func(cfg config, m *CategoryMutation) ([]*sqlgraph.EdgeSpec, error) {
				nodes := m.TodosIDs()
				if len(nodes) == 0 {
					return nil, nil
				}
				edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
					Rel:          sqlgraph.O2M,
					Inverse:      false,
					Table:        category.TodosTable,
					Columns:      category.TodosColumn,
					Bidi:         false,
					TargetColumn: todo.FieldID,
					TargetType:   field.TypeInt,
				})
				for _, id := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, id)
				}
				return []*sqlgraph.EdgeSpec{edge}, nil
			},
		},
	},
}

func (_u *CategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(category.Table, category.Columns, sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if err := entbuilder.ApplyUpdate(_u.config, _u.mutation, &categoryUpdateDescriptor, _spec); err != nil {
		return 0, err
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{category.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CategoryUpdateOne is the builder for updating a single Category entity.
type CategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CategoryMutation
}

// SetText sets the "text" field.
func (_u *CategoryUpdateOne) SetText(v string) *CategoryUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableText(v *string) *CategoryUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CategoryUpdateOne) SetStatus(v category.Status) *CategoryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableStatus(v *category.Status) *CategoryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *CategoryUpdateOne) SetKind(v category.Kind) *CategoryUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableKind(v *category.Kind) *CategoryUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetConfigType sets the "config_type" field.
func (_u *CategoryUpdateOne) SetConfigType(v category.ConfigType) *CategoryUpdateOne {
	_u.mutation.SetConfigType(v)
	return _u
}

// SetNillableConfigType sets the "config_type" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableConfigType(v *category.ConfigType) *CategoryUpdateOne {
	if v != nil {
		_u.SetConfigType(*v)
	}
	return _u
}

// ClearConfigType clears the value of the "config_type" field.
func (_u *CategoryUpdateOne) ClearConfigType() *CategoryUpdateOne {
	_u.mutation.ClearConfigType()
	return _u
}

// SetTags sets the "tags" field.
func (_u *CategoryUpdateOne) SetTags(v []string) *CategoryUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *CategoryUpdateOne) AppendTags(v []string) *CategoryUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *CategoryUpdateOne) ClearTags() *CategoryUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetConfig sets the "config" field.
func (_u *CategoryUpdateOne) SetConfig(v map[string]string) *CategoryUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *CategoryUpdateOne) ClearConfig() *CategoryUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *CategoryUpdateOne) SetExternalID(v uuid.UUID) *CategoryUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *CategoryUpdateOne) SetNillableExternalID(v *uuid.UUID) *CategoryUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *CategoryUpdateOne) ClearExternalID() *CategoryUpdateOne {
	_u.mutation.ClearExternalID()
	return _u
}

// SetAttributes sets the "attributes" field.
func (_u *CategoryUpdateOne) SetAttributes(v map[string]interface{}) *CategoryUpdateOne {
	_u.mutation.SetAttributes(v)
	return _u
}

// ClearAttributes clears the value of the "attributes" field.
func (_u *CategoryUpdateOne) ClearAttributes() *CategoryUpdateOne {
	_u.mutation.ClearAttributes()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *CategoryUpdateOne) SetPayload(v []byte) *CategoryUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *CategoryUpdateOne) ClearPayload() *CategoryUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// AddTodoIDs adds the "todos" edge to the Todo entity by IDs.
func (_u *CategoryUpdateOne) AddTodoIDs(ids ...int) *CategoryUpdateOne {
	_u.mutation.AddTodoIDs(ids...)
	return _u
}

// AddTodos adds the "todos" edges to the Todo entity.
func (_u *CategoryUpdateOne) AddTodos(v ...*Todo) *CategoryUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTodoIDs(ids...)
}

// Mutation returns the CategoryMutation object of the builder.
func (_u *CategoryUpdateOne) Mutation() *CategoryMutation {
	return _u.mutation
}

// ClearTodos clears all "todos" edges to the Todo entity.
func (_u *CategoryUpdateOne) ClearTodos() *CategoryUpdateOne {
	_u.mutation.ClearTodos()
	return _u
}

// RemoveTodoIDs removes the "todos" edge to Todo entities by IDs.
func (_u *CategoryUpdateOne) RemoveTodoIDs(ids ...int) *CategoryUpdateOne {
	_u.mutation.RemoveTodoIDs(ids...)
	return _u
}

// RemoveTodos removes "todos" edges to Todo entities.
func (_u *CategoryUpdateOne) RemoveTodos(v ...*Todo) *CategoryUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTodoIDs(ids...)
}

// Where appends a list predicates to the CategoryUpdate builder.
func (_u *CategoryUpdateOne) Where(ps ...predicate.Category) *CategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CategoryUpdateOne) Select(field string, fields ...string) *CategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Category entity.
func (_u *CategoryUpdateOne) Save(ctx context.Context) (*Category, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CategoryUpdateOne) SaveX(ctx context.Context) *Category {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Text(); ok {
		if err := category.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Category.text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := category.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Category.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := category.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Category.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigType(); ok {
		if err := category.ConfigTypeValidator(v); err != nil {
			return &ValidationError{Name: "config_type", err: fmt.Errorf(`ent: validator failed for field "Category.config_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CategoryUpdateOne) sqlSave(ctx context.Context) (_node *Category, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(category.Table, category.Columns, sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Category.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, category.FieldID)
		for _, f := range fields {
			if !category.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != category.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if err := entbuilder.ApplyUpdate(_u.config, _u.mutation, &categoryUpdateDescriptor, _spec); err != nil {
		return nil, err
	}
	_node = &Category{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{category.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
