// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strconv"

	"entgo.io/contrib/entgqlgo"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/todo"
	"github.com/graphql-go/graphql"
)

// NewSchema creates a new GraphQL schema with Query and Mutation types.
// The client is used for database operations in resolvers.
func NewSchema(client *Client) (graphql.Schema, error) {
	return graphql.NewSchema(graphql.SchemaConfig{
		Query:    newQueryType(client),
		Mutation: newMutationType(client),
	})
}

// newQueryType creates the root Query type.
func newQueryType(client *Client) *graphql.Object {
	return graphql.NewObject(graphql.ObjectConfig{
		Name: "Query",
		Fields: graphql.Fields{
			"categories": &graphql.Field{
				Type: graphql.NewNonNull(graphql.NewList(CategoryType)),
				Args: graphql.FieldConfigArgument{
					"first": &graphql.ArgumentConfig{
						Type:        graphql.Int,
						Description: "Returns the first n elements.",
					},
					"offset": &graphql.ArgumentConfig{
						Type:        graphql.Int,
						Description: "Skip the first n elements.",
					},
				},
				Description: "Query all Categories.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					query := client.Category.Query()
					// Apply eager loading based on selection
					fields := entgqlgo.CollectFields(p.Info)
					if contains(fields, "todos") {
						query = query.WithTodos()
					}
					// Apply pagination
					if first, ok := p.Args["first"].(int); ok && first > 0 {
						query = query.Limit(first)
					}
					if offset, ok := p.Args["offset"].(int); ok && offset > 0 {
						query = query.Offset(offset)
					}
					return query.All(p.Context)
				},
			},
			"category": &graphql.Field{
				Type: CategoryType,
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the Category.",
					},
				},
				Description: "Query a single Category by ID.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return nil, nil
					}
					// Convert ID based on type
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return nil, err
					}
					return client.Category.Get(p.Context, idInt)
				},
			},
			"todos": &graphql.Field{
				Type: graphql.NewNonNull(graphql.NewList(TodoType)),
				Args: graphql.FieldConfigArgument{
					"first": &graphql.ArgumentConfig{
						Type:        graphql.Int,
						Description: "Returns the first n elements.",
					},
					"offset": &graphql.ArgumentConfig{
						Type:        graphql.Int,
						Description: "Skip the first n elements.",
					},
				},
				Description: "Query all Todos.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					query := client.Todo.Query()
					// Apply eager loading based on selection
					fields := entgqlgo.CollectFields(p.Info)
					if contains(fields, "parent") {
						query = query.WithParent()
					}
					if contains(fields, "children") {
						query = query.WithChildren()
					}
					if contains(fields, "category") {
						query = query.WithCategory()
					}
					// Apply pagination
					if first, ok := p.Args["first"].(int); ok && first > 0 {
						query = query.Limit(first)
					}
					if offset, ok := p.Args["offset"].(int); ok && offset > 0 {
						query = query.Offset(offset)
					}
					return query.All(p.Context)
				},
			},
			"todo": &graphql.Field{
				Type: TodoType,
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the Todo.",
					},
				},
				Description: "Query a single Todo by ID.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return nil, nil
					}
					// Convert ID based on type
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return nil, err
					}
					return client.Todo.Get(p.Context, idInt)
				},
			}, "node": &graphql.Field{
				Type: NodeInterface,
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the node.",
					},
				},
				Description: "Fetches an object given its ID.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return nil, nil
					}
					return client.Noder(p.Context, fmt.Sprint(id))
				},
			},
		},
	})
}

// newMutationType creates the root Mutation type.
func newMutationType(client *Client) *graphql.Object {
	return graphql.NewObject(graphql.ObjectConfig{
		Name: "Mutation",
		Fields: graphql.Fields{
			"createCategory": &graphql.Field{
				Type:        CategoryType,
				Args:        createCategoryArgs(),
				Description: "Create a new Category.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					create := client.Category.Create()
					if v, ok := p.Args["text"]; ok {
						create = create.SetText(v.(string))
					}
					if v, ok := p.Args["status"]; ok {
						create = create.SetStatus(v.(category.Status))
					}
					return create.Save(p.Context)
				},
			},
			"updateCategory": &graphql.Field{
				Type:        CategoryType,
				Args:        updateCategoryArgs(),
				Description: "Update an existing Category.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return nil, fmt.Errorf("id is required")
					}
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return nil, err
					}
					update := client.Category.UpdateOneID(idInt)
					if v, ok := p.Args["text"]; ok {
						update = update.SetText(v.(string))
					}
					if v, ok := p.Args["status"]; ok {
						update = update.SetStatus(v.(category.Status))
					}
					return update.Save(p.Context)
				},
			},
			"deleteCategory": &graphql.Field{
				Type: graphql.Boolean,
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the Category to delete.",
					},
				},
				Description: "Delete a Category.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return false, fmt.Errorf("id is required")
					}
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return false, err
					}
					err = client.Category.DeleteOneID(idInt).Exec(p.Context)
					return err == nil, err
				},
			},
			"createTodo": &graphql.Field{
				Type:        TodoType,
				Args:        createTodoArgs(),
				Description: "Create a new Todo.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					create := client.Todo.Create()
					if v, ok := p.Args["status"]; ok {
						create = create.SetStatus(v.(todo.Status))
					}
					if v, ok := p.Args["priority"]; ok {
						create = create.SetPriority(v.(int))
					}
					if v, ok := p.Args["text"]; ok {
						create = create.SetText(v.(string))
					}
					return create.Save(p.Context)
				},
			},
			"updateTodo": &graphql.Field{
				Type:        TodoType,
				Args:        updateTodoArgs(),
				Description: "Update an existing Todo.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return nil, fmt.Errorf("id is required")
					}
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return nil, err
					}
					update := client.Todo.UpdateOneID(idInt)
					if v, ok := p.Args["status"]; ok {
						update = update.SetStatus(v.(todo.Status))
					}
					if v, ok := p.Args["priority"]; ok {
						update = update.SetPriority(v.(int))
					}
					if v, ok := p.Args["text"]; ok {
						update = update.SetText(v.(string))
					}
					return update.Save(p.Context)
				},
			},
			"deleteTodo": &graphql.Field{
				Type: graphql.Boolean,
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the Todo to delete.",
					},
				},
				Description: "Delete a Todo.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return false, fmt.Errorf("id is required")
					}
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return false, err
					}
					err = client.Todo.DeleteOneID(idInt).Exec(p.Context)
					return err == nil, err
				},
			},
		},
	})
}

func createCategoryArgs() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"text": &graphql.ArgumentConfig{
			Type: graphql.NewNonNull(graphql.String),
		},
		"status": &graphql.ArgumentConfig{
			Type: graphql.NewNonNull(graphql.String),
		},
	}
}

func updateCategoryArgs() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"id": &graphql.ArgumentConfig{
			Type:        graphql.NewNonNull(graphql.ID),
			Description: "The ID of the Category to update.",
		},
		"text": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
		"status": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
	}
}

func createTodoArgs() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"status": &graphql.ArgumentConfig{
			Type: graphql.NewNonNull(graphql.String),
		},
		"priority": &graphql.ArgumentConfig{
			Type: graphql.NewNonNull(graphql.Int),
		},
		"text": &graphql.ArgumentConfig{
			Type: graphql.NewNonNull(graphql.String),
		},
	}
}

func updateTodoArgs() graphql.FieldConfigArgument {
	return graphql.FieldConfigArgument{
		"id": &graphql.ArgumentConfig{
			Type:        graphql.NewNonNull(graphql.ID),
			Description: "The ID of the Todo to update.",
		},
		"status": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
		"priority": &graphql.ArgumentConfig{
			Type: graphql.Int,
		},
		"text": &graphql.ArgumentConfig{
			Type: graphql.String,
		},
	}
}

// contains checks if a slice contains a string.
func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}
