// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgqlgo"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/todo"
	"entgo.io/ent/dialect/sql"
	"github.com/graphql-go/graphql"
)

// Pagination types for Relay-style connections.
// These implement the Relay Cursor Connections Specification.

// PaginationArgs represents the standard Relay pagination arguments.
type PaginationArgs struct {
	First  *int
	After  *entgqlgo.Cursor[int]
	Last   *int
	Before *entgqlgo.Cursor[int]
}

// ParsePaginationArgs extracts pagination arguments from GraphQL ResolveParams.
func ParsePaginationArgs(p graphql.ResolveParams) (*PaginationArgs, error) {
	args := &PaginationArgs{}

	if first, ok := p.Args["first"].(int); ok {
		args.First = &first
	}
	if last, ok := p.Args["last"].(int); ok {
		args.Last = &last
	}
	// Handle after cursor - may be parsed as cursor by scalar or as string
	if after := p.Args["after"]; after != nil {
		switch v := after.(type) {
		case *entgqlgo.Cursor[int]:
			args.After = v
		case string:
			c := &entgqlgo.Cursor[int]{}
			if err := c.UnmarshalText([]byte(v)); err != nil {
				return nil, err
			}
			args.After = c
		}
	}
	// Handle before cursor - may be parsed as cursor by scalar or as string
	if before := p.Args["before"]; before != nil {
		switch v := before.(type) {
		case *entgqlgo.Cursor[int]:
			args.Before = v
		case string:
			c := &entgqlgo.Cursor[int]{}
			if err := c.UnmarshalText([]byte(v)); err != nil {
				return nil, err
			}
			args.Before = c
		}
	}

	// Validate arguments
	if err := validatePaginationArgs(args); err != nil {
		return nil, err
	}

	return args, nil
}

// validatePaginationArgs validates that pagination arguments are valid.
func validatePaginationArgs(args *PaginationArgs) error {
	if args.First != nil && args.Last != nil {
		return errors.New("passing both first and last is not supported")
	}
	if args.First != nil && *args.First < 0 {
		return errors.New("first must be a non-negative integer")
	}
	if args.Last != nil && *args.Last < 0 {
		return errors.New("last must be a non-negative integer")
	}
	if args.After != nil && args.Before != nil {
		return errors.New("passing both after and before is not supported")
	}
	return nil
}

// CategoryEdge represents an edge in a Category connection.
type CategoryEdge struct {
	Node   *Category            `json:"node,omitempty"`
	Cursor entgqlgo.Cursor[int] `json:"cursor"`
}

// CategoryConnection represents a connection to a list of Categories.
type CategoryConnection struct {
	Edges      []*CategoryEdge        `json:"edges,omitempty"`
	PageInfo   entgqlgo.PageInfo[int] `json:"pageInfo"`
	TotalCount int                    `json:"totalCount"`
}

// CategoryEdgeType is the GraphQL type for CategoryEdge.
var CategoryEdgeType = graphql.NewObject(graphql.ObjectConfig{
	Name:        "CategoryEdge",
	Description: "An edge in a Category connection.",
	Fields: graphql.FieldsThunk(func() graphql.Fields {
		return graphql.Fields{
			"node": &graphql.Field{
				Type:        CategoryType,
				Description: "The item at the end of the edge.",
			},
			"cursor": &graphql.Field{
				Type:        graphql.NewNonNull(CursorScalar),
				Description: "A cursor for use in pagination.",
			},
		}
	}),
})

// CategoryConnectionType is the GraphQL type for CategoryConnection.
var CategoryConnectionType = graphql.NewObject(graphql.ObjectConfig{
	Name:        "CategoryConnection",
	Description: "A connection to a list of Categories.",
	Fields: graphql.Fields{
		"edges": &graphql.Field{
			Type:        graphql.NewList(CategoryEdgeType),
			Description: "A list of edges.",
		},
		"pageInfo": &graphql.Field{
			Type:        graphql.NewNonNull(PageInfoType),
			Description: "Information to aid in pagination.",
		},
		"totalCount": &graphql.Field{
			Type:        graphql.NewNonNull(graphql.Int),
			Description: "Identifies the total count of items in the connection.",
		},
	},
})

// PaginateCategories returns a paginated list of Categories.
func (c *Client) PaginateCategories(
	ctx context.Context,
	after, before *entgqlgo.Cursor[int],
	first, last *int,
	opts ...CategoryQueryOption,
) (*CategoryConnection, error) {
	query := c.Category.Query()
	for _, opt := range opts {
		opt(query)
	}

	// Get total count
	totalCount, err := query.Clone().Count(ctx)
	if err != nil {
		return nil, err
	}

	// Apply cursor pagination
	if after != nil {
		query = query.Where(category.IDGT(after.ID))
	}
	if before != nil {
		query = query.Where(category.IDLT(before.ID))
	}

	// Apply limit
	limit := 0
	if first != nil {
		limit = *first + 1 // +1 to check if there are more items
		query = query.Limit(limit)
	} else if last != nil {
		limit = *last + 1
		query = query.Order(category.ByID(sql.OrderDesc()))
		query = query.Limit(limit)
	}

	nodes, err := query.All(ctx)
	if err != nil {
		return nil, err
	}

	// Build connection
	conn := &CategoryConnection{
		TotalCount: totalCount,
	}

	// Check for more pages
	hasMore := len(nodes) > 0 && limit > 0 && len(nodes) == limit
	if hasMore {
		nodes = nodes[:len(nodes)-1]
	}

	// Reverse if paginating backwards
	if last != nil {
		for i, j := 0, len(nodes)-1; i < j; i, j = i+1, j-1 {
			nodes[i], nodes[j] = nodes[j], nodes[i]
		}
	}

	// Build edges
	conn.Edges = make([]*CategoryEdge, len(nodes))
	for i, node := range nodes {
		conn.Edges[i] = &CategoryEdge{
			Node:   node,
			Cursor: entgqlgo.Cursor[int]{ID: node.ID},
		}
	}

	// Build page info
	if len(conn.Edges) > 0 {
		conn.PageInfo.StartCursor = &conn.Edges[0].Cursor
		conn.PageInfo.EndCursor = &conn.Edges[len(conn.Edges)-1].Cursor
	}
	conn.PageInfo.HasNextPage = (first != nil && hasMore) || (last != nil && before != nil)
	conn.PageInfo.HasPreviousPage = (last != nil && hasMore) || (first != nil && after != nil)

	return conn, nil
}

// PaginateCategoriesWithOrder returns a paginated list of Categories with ordering.
func (c *Client) PaginateCategoriesWithOrder(
	ctx context.Context,
	after, before *entgqlgo.Cursor[int],
	first, last *int,
	order *CategoryOrder,
	opts ...CategoryQueryOption,
) (*CategoryConnection, error) {
	query := c.Category.Query()
	for _, opt := range opts {
		opt(query)
	}

	// Get total count
	totalCount, err := query.Clone().Count(ctx)
	if err != nil {
		return nil, err
	}

	// Apply cursor pagination
	if after != nil {
		query = query.Where(category.IDGT(after.ID))
	}
	if before != nil {
		query = query.Where(category.IDLT(before.ID))
	}

	// Apply ordering and limit
	// Note: ordering must be applied in the same block as pagination direction
	// to avoid applying conflicting orders (e.g., ASC then DESC)
	limit := 0
	if first != nil {
		// Forward pagination - apply ordering then limit
		if order != nil {
			query = query.Order(order.ToOrderOption())
		} else {
			query = query.Order(category.ByID())
		}
		limit = *first + 1 // +1 to check if there are more items
		query = query.Limit(limit)
	} else if last != nil {
		// Backward pagination - apply reversed ordering then limit
		limit = *last + 1
		if order != nil {
			reversedOrder := &CategoryOrder{
				Field:     order.Field,
				Direction: order.Direction.Reverse(),
			}
			query = query.Order(reversedOrder.ToOrderOption())
		} else {
			query = query.Order(category.ByID(sql.OrderDesc()))
		}
		query = query.Limit(limit)
	} else {
		// No pagination - apply default ordering
		if order != nil {
			query = query.Order(order.ToOrderOption())
		} else {
			query = query.Order(category.ByID())
		}
	}

	nodes, err := query.All(ctx)
	if err != nil {
		return nil, err
	}

	// Build connection
	conn := &CategoryConnection{
		TotalCount: totalCount,
	}

	// Check for more pages
	hasMore := len(nodes) > 0 && limit > 0 && len(nodes) == limit
	if hasMore {
		nodes = nodes[:len(nodes)-1]
	}

	// Reverse if paginating backwards
	if last != nil {
		for i, j := 0, len(nodes)-1; i < j; i, j = i+1, j-1 {
			nodes[i], nodes[j] = nodes[j], nodes[i]
		}
	}

	// Build edges
	conn.Edges = make([]*CategoryEdge, len(nodes))
	for i, node := range nodes {
		conn.Edges[i] = &CategoryEdge{
			Node:   node,
			Cursor: entgqlgo.Cursor[int]{ID: node.ID},
		}
	}

	// Build page info
	if len(conn.Edges) > 0 {
		conn.PageInfo.StartCursor = &conn.Edges[0].Cursor
		conn.PageInfo.EndCursor = &conn.Edges[len(conn.Edges)-1].Cursor
	}
	conn.PageInfo.HasNextPage = (first != nil && hasMore) || (last != nil && before != nil)
	conn.PageInfo.HasPreviousPage = (last != nil && hasMore) || (first != nil && after != nil)

	return conn, nil
}

// CategoryQueryOption is a function that modifies a CategoryQuery.
type CategoryQueryOption func(*CategoryQuery)

// TodoEdge represents an edge in a Todo connection.
type TodoEdge struct {
	Node   *Todo                `json:"node,omitempty"`
	Cursor entgqlgo.Cursor[int] `json:"cursor"`
}

// TodoConnection represents a connection to a list of Todos.
type TodoConnection struct {
	Edges      []*TodoEdge            `json:"edges,omitempty"`
	PageInfo   entgqlgo.PageInfo[int] `json:"pageInfo"`
	TotalCount int                    `json:"totalCount"`
}

// TodoEdgeType is the GraphQL type for TodoEdge.
var TodoEdgeType = graphql.NewObject(graphql.ObjectConfig{
	Name:        "TodoEdge",
	Description: "An edge in a Todo connection.",
	Fields: graphql.FieldsThunk(func() graphql.Fields {
		return graphql.Fields{
			"node": &graphql.Field{
				Type:        TodoType,
				Description: "The item at the end of the edge.",
			},
			"cursor": &graphql.Field{
				Type:        graphql.NewNonNull(CursorScalar),
				Description: "A cursor for use in pagination.",
			},
		}
	}),
})

// TodoConnectionType is the GraphQL type for TodoConnection.
var TodoConnectionType = graphql.NewObject(graphql.ObjectConfig{
	Name:        "TodoConnection",
	Description: "A connection to a list of Todos.",
	Fields: graphql.Fields{
		"edges": &graphql.Field{
			Type:        graphql.NewList(TodoEdgeType),
			Description: "A list of edges.",
		},
		"pageInfo": &graphql.Field{
			Type:        graphql.NewNonNull(PageInfoType),
			Description: "Information to aid in pagination.",
		},
		"totalCount": &graphql.Field{
			Type:        graphql.NewNonNull(graphql.Int),
			Description: "Identifies the total count of items in the connection.",
		},
	},
})

// PaginateTodos returns a paginated list of Todos.
func (c *Client) PaginateTodos(
	ctx context.Context,
	after, before *entgqlgo.Cursor[int],
	first, last *int,
	opts ...TodoQueryOption,
) (*TodoConnection, error) {
	query := c.Todo.Query()
	for _, opt := range opts {
		opt(query)
	}

	// Get total count
	totalCount, err := query.Clone().Count(ctx)
	if err != nil {
		return nil, err
	}

	// Apply cursor pagination
	if after != nil {
		query = query.Where(todo.IDGT(after.ID))
	}
	if before != nil {
		query = query.Where(todo.IDLT(before.ID))
	}

	// Apply limit
	limit := 0
	if first != nil {
		limit = *first + 1 // +1 to check if there are more items
		query = query.Limit(limit)
	} else if last != nil {
		limit = *last + 1
		query = query.Order(todo.ByID(sql.OrderDesc()))
		query = query.Limit(limit)
	}

	nodes, err := query.All(ctx)
	if err != nil {
		return nil, err
	}

	// Build connection
	conn := &TodoConnection{
		TotalCount: totalCount,
	}

	// Check for more pages
	hasMore := len(nodes) > 0 && limit > 0 && len(nodes) == limit
	if hasMore {
		nodes = nodes[:len(nodes)-1]
	}

	// Reverse if paginating backwards
	if last != nil {
		for i, j := 0, len(nodes)-1; i < j; i, j = i+1, j-1 {
			nodes[i], nodes[j] = nodes[j], nodes[i]
		}
	}

	// Build edges
	conn.Edges = make([]*TodoEdge, len(nodes))
	for i, node := range nodes {
		conn.Edges[i] = &TodoEdge{
			Node:   node,
			Cursor: entgqlgo.Cursor[int]{ID: node.ID},
		}
	}

	// Build page info
	if len(conn.Edges) > 0 {
		conn.PageInfo.StartCursor = &conn.Edges[0].Cursor
		conn.PageInfo.EndCursor = &conn.Edges[len(conn.Edges)-1].Cursor
	}
	conn.PageInfo.HasNextPage = (first != nil && hasMore) || (last != nil && before != nil)
	conn.PageInfo.HasPreviousPage = (last != nil && hasMore) || (first != nil && after != nil)

	return conn, nil
}

// PaginateTodosWithOrder returns a paginated list of Todos with ordering.
func (c *Client) PaginateTodosWithOrder(
	ctx context.Context,
	after, before *entgqlgo.Cursor[int],
	first, last *int,
	orders []*TodoOrder,
	opts ...TodoQueryOption,
) (*TodoConnection, error) {
	query := c.Todo.Query()
	for _, opt := range opts {
		opt(query)
	}

	// Get total count
	totalCount, err := query.Clone().Count(ctx)
	if err != nil {
		return nil, err
	}

	// Apply cursor pagination
	if after != nil {
		query = query.Where(todo.IDGT(after.ID))
	}
	if before != nil {
		query = query.Where(todo.IDLT(before.ID))
	}

	// Apply ordering and limit
	// Note: ordering must be applied in the same block as pagination direction
	// to avoid applying conflicting orders (e.g., ASC then DESC)
	limit := 0
	if first != nil {
		// Forward pagination - apply ordering then limit
		if len(orders) > 0 {
			query = ApplyTodoOrderList(query, orders)
		} else {
			query = query.Order(todo.ByID())
		}
		limit = *first + 1 // +1 to check if there are more items
		query = query.Limit(limit)
	} else if last != nil {
		// Backward pagination - apply reversed ordering then limit
		limit = *last + 1
		if len(orders) > 0 {
			// Reverse each order direction for backward pagination
			reversedOrders := make([]*TodoOrder, len(orders))
			for i, o := range orders {
				reversedOrders[i] = &TodoOrder{
					Field:     o.Field,
					Direction: o.Direction.Reverse(),
				}
			}
			query = ApplyTodoOrderList(query, reversedOrders)
		} else {
			query = query.Order(todo.ByID(sql.OrderDesc()))
		}
		query = query.Limit(limit)
	} else {
		// No pagination - apply default ordering
		if len(orders) > 0 {
			query = ApplyTodoOrderList(query, orders)
		} else {
			query = query.Order(todo.ByID())
		}
	}

	nodes, err := query.All(ctx)
	if err != nil {
		return nil, err
	}

	// Build connection
	conn := &TodoConnection{
		TotalCount: totalCount,
	}

	// Check for more pages
	hasMore := len(nodes) > 0 && limit > 0 && len(nodes) == limit
	if hasMore {
		nodes = nodes[:len(nodes)-1]
	}

	// Reverse if paginating backwards
	if last != nil {
		for i, j := 0, len(nodes)-1; i < j; i, j = i+1, j-1 {
			nodes[i], nodes[j] = nodes[j], nodes[i]
		}
	}

	// Build edges
	conn.Edges = make([]*TodoEdge, len(nodes))
	for i, node := range nodes {
		conn.Edges[i] = &TodoEdge{
			Node:   node,
			Cursor: entgqlgo.Cursor[int]{ID: node.ID},
		}
	}

	// Build page info
	if len(conn.Edges) > 0 {
		conn.PageInfo.StartCursor = &conn.Edges[0].Cursor
		conn.PageInfo.EndCursor = &conn.Edges[len(conn.Edges)-1].Cursor
	}
	conn.PageInfo.HasNextPage = (first != nil && hasMore) || (last != nil && before != nil)
	conn.PageInfo.HasPreviousPage = (last != nil && hasMore) || (first != nil && after != nil)

	return conn, nil
}

// TodoQueryOption is a function that modifies a TodoQuery.
type TodoQueryOption func(*TodoQuery)
