// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"time"

	"entgo.io/contrib/entgqlgo/internal/todo/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/todo"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/runtime/entgen"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TodoCreate is the builder for creating a Todo entity.
type TodoCreate struct {
	config
	mutation *TodoMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TodoCreate) SetCreatedAt(v time.Time) *TodoCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TodoCreate) SetNillableCreatedAt(v *time.Time) *TodoCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TodoCreate) SetStatus(v todo.Status) *TodoCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *TodoCreate) SetPriority(v int) *TodoCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *TodoCreate) SetNillablePriority(v *int) *TodoCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetText sets the "text" field.
func (_c *TodoCreate) SetText(v string) *TodoCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *TodoCreate) SetScore(v float64) *TodoCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *TodoCreate) SetNillableScore(v *float64) *TodoCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *TodoCreate) SetDueDate(v time.Time) *TodoCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_c *TodoCreate) SetNillableDueDate(v *time.Time) *TodoCreate {
	if v != nil {
		_c.SetDueDate(*v)
	}
	return _c
}

// SetTags2 sets the "tags2" field.
func (_c *TodoCreate) SetTags2(v []string) *TodoCreate {
	_c.mutation.SetTags2(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *TodoCreate) SetMetadata(v map[string]interface{}) *TodoCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *TodoCreate) SetExternalID(v uuid.UUID) *TodoCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_c *TodoCreate) SetNillableExternalID(v *uuid.UUID) *TodoCreate {
	if v != nil {
		_c.SetExternalID(*v)
	}
	return _c
}

// SetDuration sets the "duration" field.
func (_c *TodoCreate) SetDuration(v int64) *TodoCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_c *TodoCreate) SetNillableDuration(v *int64) *TodoCreate {
	if v != nil {
		_c.SetDuration(*v)
	}
	return _c
}

// SetParentID sets the "parent" edge to the Todo entity by ID.
func (_c *TodoCreate) SetParentID(id int) *TodoCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Todo entity by ID if the given value is not nil.
func (_c *TodoCreate) SetNillableParentID(id *int) *TodoCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Todo entity.
func (_c *TodoCreate) SetParent(v *Todo) *TodoCreate {
	return _c.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Todo entity by IDs.
func (_c *TodoCreate) AddChildIDs(ids ...int) *TodoCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the Todo entity.
func (_c *TodoCreate) AddChildren(v ...*Todo) *TodoCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_c *TodoCreate) SetCategoryID(id int) *TodoCreate {
	_c.mutation.SetCategoryID(id)
	return _c
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_c *TodoCreate) SetNillableCategoryID(id *int) *TodoCreate {
	if id != nil {
		_c = _c.SetCategoryID(*id)
	}
	return _c
}

// SetCategory sets the "category" edge to the Category entity.
func (_c *TodoCreate) SetCategory(v *Category) *TodoCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (_c *TodoCreate) Mutation() *TodoMutation {
	return _c.mutation
}

// Save creates the Todo in the database.
func (_c *TodoCreate) Save(ctx context.Context) (*Todo, error) {
	if err := entgen.ApplyDefaults(_c.mutation, todoCreateSpec.Fields); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TodoCreate) SaveX(ctx context.Context) *Todo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TodoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TodoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

var todoCreateSpec = entgen.CreateSpec[*TodoMutation]{
	Fields: []entgen.FieldSpec[*TodoMutation]{
		{
			Name: "created_at",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Todo.created_at"`)}
				},
			},
			IsSet: func(m *TodoMutation) bool {
				_, ok := m.CreatedAt()
				return ok
			},
			Default: func(m *TodoMutation) error {
				if _, ok := m.CreatedAt(); !ok {
					v := todo.DefaultCreatedAt()
					m.SetCreatedAt(v)
				}
				return nil
			},
		},
		{
			Name: "status",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Todo.status"`)}
				},
			},
			IsSet: func(m *TodoMutation) bool {
				_, ok := m.Status()
				return ok
			},
			Validators: []func(*TodoMutation) error{
				func(m *TodoMutation) error {
					if v, ok := m.Status(); ok {
						if err := todo.StatusValidator(v); err != nil {
							return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
						}
					}
					return nil
				},
			},
		},
		{
			Name: "priority",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Todo.priority"`)}
				},
			},
			IsSet: func(m *TodoMutation) bool {
				_, ok := m.Priority()
				return ok
			},
			Default: func(m *TodoMutation) error {
				if _, ok := m.Priority(); !ok {
					v := todo.DefaultPriority
					m.SetPriority(v)
				}
				return nil
			},
		},
		{
			Name: "text",
			Requirement: entgen.FieldRequirement{
				Required: true,
				Error: func() error {
					return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Todo.text"`)}
				},
			},
			IsSet: func(m *TodoMutation) bool {
				_, ok := m.Text()
				return ok
			},
			Validators: []func(*TodoMutation) error{
				func(m *TodoMutation) error {
					if v, ok := m.Text(); ok {
						if err := todo.TextValidator(v); err != nil {
							return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Todo.text": %w`, err)}
						}
					}
					return nil
				},
			},
		},
		{
			Name: "score",
		},
		{
			Name: "due_date",
		},
		{
			Name: "tags2",
		},
		{
			Name: "metadata",
		},
		{
			Name: "external_id",
		},
		{
			Name: "duration",
		},
	},
	Edges: []entgen.EdgeSpec[*TodoMutation]{},
}

var todoCreateDescriptor = entbuilder.CreateDescriptor[config, Todo, *TodoMutation]{
	Table: todo.Table,
	NewNode: func(cfg config) *Todo {
		return &Todo{config: cfg}
	},
	ID: &entbuilder.IDDescriptor[config, Todo, *TodoMutation]{
		Column:      todo.FieldID,
		Type:        field.TypeInt,
		UserDefined: false,
		AssignGenerated: func(node *Todo, value driver.Value) error {
			switch v := value.(type) {
			case int:
				node.ID = int(v)
			case int8:
				node.ID = int(v)
			case int16:
				node.ID = int(v)
			case int32:
				node.ID = int(v)
			case int64:
				node.ID = int(v)
			case uint:
				node.ID = int(v)
			case uint8:
				node.ID = int(v)
			case uint16:
				node.ID = int(v)
			case uint32:
				node.ID = int(v)
			case uint64:
				node.ID = int(v)
			default:
				if v, ok := value.(int); ok {
					node.ID = v
					return nil
				}
				return fmt.Errorf("unexpected Todo.ID type: %T", value)
			}
			return nil
		},
	},

	Fields: []entbuilder.FieldDescriptor[config, Todo, *TodoMutation]{

		entbuilder.SimpleField[config, Todo, *TodoMutation, time.Time](
			todo.FieldCreatedAt,
			field.TypeTime,
			(*TodoMutation).CreatedAt,
			func(n *Todo, v time.Time) { n.CreatedAt = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, todo.Status](
			todo.FieldStatus,
			field.TypeEnum,
			(*TodoMutation).Status,
			func(n *Todo, v todo.Status) { n.Status = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, int](
			todo.FieldPriority,
			field.TypeInt,
			(*TodoMutation).Priority,
			func(n *Todo, v int) { n.Priority = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, string](
			todo.FieldText,
			field.TypeString,
			(*TodoMutation).Text,
			func(n *Todo, v string) { n.Text = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, float64](
			todo.FieldScore,
			field.TypeFloat64,
			(*TodoMutation).Score,
			func(n *Todo, v float64) { n.Score = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, time.Time](
			todo.FieldDueDate,
			field.TypeTime,
			(*TodoMutation).DueDate,
			func(n *Todo, v time.Time) { n.DueDate = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, []string](
			todo.FieldTags2,
			field.TypeJSON,
			(*TodoMutation).Tags2,
			func(n *Todo, v []string) { n.Tags2 = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, map[string]interface{}](
			todo.FieldMetadata,
			field.TypeJSON,
			(*TodoMutation).Metadata,
			func(n *Todo, v map[string]interface{}) { n.Metadata = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, uuid.UUID](
			todo.FieldExternalID,
			field.TypeUUID,
			(*TodoMutation).ExternalID,
			func(n *Todo, v uuid.UUID) { n.ExternalID = v },
		),

		entbuilder.SimpleField[config, Todo, *TodoMutation, int64](
			todo.FieldDuration,
			field.TypeInt64,
			(*TodoMutation).Duration,
			func(n *Todo, v int64) { n.Duration = v },
		),
	},
	Edges: []entbuilder.EdgeDescriptor[config, Todo, *TodoMutation]{
		{
			Value: func(cfg config, m *TodoMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.ParentIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.M2O,
					Inverse: true,
					Table:   todo.ParentTable,
					Columns: []string{todo.ParentColumn},
					Bidi:    false,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
			Assign: func(node *Todo, ev entbuilder.EdgeValue) error {
				ids, ok := ev.Nodes.([]int)
				if !ok || len(ids) == 0 {
					return nil
				}
				node.todo_children = &ids[0]
				return nil
			},
		},

		{
			Value: func(cfg config, m *TodoMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.ChildrenIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.O2M,
					Inverse: false,
					Table:   todo.ChildrenTable,
					Columns: []string{todo.ChildrenColumn},
					Bidi:    false,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
		},

		{
			Value: func(cfg config, m *TodoMutation) (entbuilder.EdgeValue, bool, error) {
				nodes := m.CategoryIDs()
				if len(nodes) == 0 {
					return entbuilder.EdgeValue{}, false, nil
				}
				edge := &sqlgraph.EdgeSpec{
					Rel:     sqlgraph.M2O,
					Inverse: true,
					Table:   todo.CategoryTable,
					Columns: []string{todo.CategoryColumn},
					Bidi:    false,
					Target: &sqlgraph.EdgeTarget{
						IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
					},
				}
				for _, k := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, k)
				}
				return entbuilder.EdgeValue{Spec: edge, Nodes: nodes}, true, nil
			},
			Assign: func(node *Todo, ev entbuilder.EdgeValue) error {
				ids, ok := ev.Nodes.([]int)
				if !ok || len(ids) == 0 {
					return nil
				}
				node.category_todos = &ids[0]
				return nil
			},
		},
	},
}

func (_c *TodoCreate) sqlSave(ctx context.Context) (*Todo, error) {
	if err := entgen.CheckCreate(_c.driver.Dialect(), _c.mutation, todoCreateSpec); err != nil {
		return nil, err
	}
	_node, _spec, err := entbuilder.BuildCreateSpec(_c.config, _c.mutation, &todoCreateDescriptor)
	if err != nil {
		return nil, err
	}
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if err := entbuilder.ApplyGeneratedID(_c.mutation, _spec, _node, &todoCreateDescriptor); err != nil {
		return nil, err
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

// TodoCreateBulk is the builder for creating many Todo entities in bulk.
type TodoCreateBulk struct {
	config
	err      error
	builders []*TodoCreate
}

// Save creates the Todo entities in the database.
func (_c *TodoCreateBulk) Save(ctx context.Context) ([]*Todo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Todo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		if err := entgen.ApplyDefaults(_c.builders[i].mutation, todoCreateSpec.Fields); err != nil {
			return nil, err
		}
	}
	for i := range _c.builders {
		func(i int, root context.Context) {
			curr := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TodoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := entgen.CheckCreate(curr.driver.Dialect(), mutation, todoCreateSpec); err != nil {
					return nil, err
				}
				curr.mutation = mutation
				var err error
				nodes[i], specs[i], err = entbuilder.BuildCreateSpec(curr.config, mutation, &todoCreateDescriptor)
				if err != nil {
					return nil, err
				}
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
					if err == nil {
						for j := range specs {
							if err = entbuilder.ApplyGeneratedID(_c.builders[j].mutation, specs[j], nodes[j], &todoCreateDescriptor); err != nil {
								break
							}
							_c.builders[j].mutation.id = &nodes[j].ID
							_c.builders[j].mutation.done = true
						}
					}
				}
				if err != nil {
					return nil, err
				}
				return nodes[i], nil
			})
			for i := len(curr.hooks) - 1; i >= 0; i-- {
				mut = curr.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TodoCreateBulk) SaveX(ctx context.Context) []*Todo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TodoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TodoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
