// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package internal

import (
	"context"
	"reflect"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/runtime/entbuilder"

	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/predicate"
)

// CategoryMutation is an alias for entbuilder.Mutation parameterised by Category.
type CategoryMutation = entbuilder.Mutation[Category, int]

// CategoryMutationOption is a functional option for CategoryMutation.
type CategoryMutationOption = func(*CategoryMutation)

// categoryDescriptor describes Category's fields and edges
// for the generic mutation runtime.
var categoryDescriptor = &entbuilder.Descriptor{
	Name:   "Category",
	IDType: reflect.TypeFor[int](),
	Fields: map[string]entbuilder.FieldSpec{
		"name": {
			Type:   reflect.TypeFor[string](),
			GoName: "Name",
		},
		"config_type": {
			Type:     reflect.TypeFor[CategoryConfigType](),
			GoName:   "ConfigType",
			Nillable: true,
		},
	},
	Edges: map[string]entbuilder.EdgeSpec{
		"todos": {
			Cardinality:  entbuilder.O2M,
			Target:       "Todo",
			TargetIDType: reflect.TypeFor[int](),
		},
	}}

// NewCategoryMutation creates a new mutation for the Category entity.
func NewCategoryMutation(c Config, op Op, opts ...CategoryMutationOption) *CategoryMutation {
	return entbuilder.NewMutation[Category, int](&c, op, categoryDescriptor, opts...)
}

// WithCategoryID sets the ID field and old-value loader of the mutation.
// The getFunc callback fetches the old entity value for OldField support.
// If getFunc is nil, the old-value loader is not set (used by DeleteOneID).
func WithCategoryID(id int, getFunc func(context.Context, int) (*Category, error)) CategoryMutationOption {
	return func(m *CategoryMutation) {
		m.SetID(id)
		if getFunc != nil {
			m.SetOldValueLoader(func(ctx context.Context) (any, error) { return getFunc(ctx, id) })
		}
	}
}

// WithCategory sets the old Category of the mutation.
func WithCategory(node *Category) CategoryMutationOption {
	return func(m *CategoryMutation) {
		m.SetID(node.ID)
		m.SetOldValueLoader(func(context.Context) (any, error) { return node, nil })
	}
}

// WithCategoryIDsFunc sets the function used to query entity IDs.
func WithCategoryIDsFunc(fn func(context.Context, ...predicate.Category) ([]int, error)) CategoryMutationOption {
	return func(m *CategoryMutation) {
		m.SetIDsFunc(func(ctx context.Context, preds ...func(*sql.Selector)) ([]any, error) {
			ps := make([]predicate.Category, len(preds))
			for i, p := range preds {
				ps[i] = p
			}
			ids, err := fn(ctx, ps...)
			if err != nil {
				return nil, err
			}
			out := make([]any, len(ids))
			for i, id := range ids {
				out[i] = id
			}
			return out, nil
		})
	}
}
