// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package internal

import (
	"context"
	"reflect"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/runtime/entbuilder"

	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/predicate"
)

// TodoMutation is an alias for entbuilder.Mutation parameterised by Todo.
type TodoMutation = entbuilder.Mutation[Todo, int]

// TodoMutationOption is a functional option for TodoMutation.
type TodoMutationOption = func(*TodoMutation)

// todoDescriptor describes Todo's fields and edges
// for the generic mutation runtime.
var todoDescriptor = &entbuilder.Descriptor{
	Name:   "Todo",
	IDType: reflect.TypeFor[int](),
	Fields: map[string]entbuilder.FieldSpec{
		"text": {
			Type:   reflect.TypeFor[string](),
			GoName: "Text",
		},
		"status": {
			Type:   reflect.TypeFor[TodoStatus](),
			GoName: "Status",
		},
		"priority": {
			Type:     reflect.TypeFor[int](),
			GoName:   "Priority",
			Nillable: true,
			Numeric:  true,
		},
		"created_at": {
			Type:   reflect.TypeFor[time.Time](),
			GoName: "CreatedAt",
		},
	},
	Edges: map[string]entbuilder.EdgeSpec{
		"parent": {
			Cardinality:  entbuilder.O2OUnique,
			Target:       "Todo",
			TargetIDType: reflect.TypeFor[int](),
			Inverse:      true,
		},
		"children": {
			Cardinality:  entbuilder.O2M,
			Target:       "Todo",
			TargetIDType: reflect.TypeFor[int](),
		},
		"category": {
			Cardinality:  entbuilder.O2OUnique,
			Target:       "Category",
			TargetIDType: reflect.TypeFor[int](),
			Inverse:      true,
		},
	}}

// NewTodoMutation creates a new mutation for the Todo entity.
func NewTodoMutation(c Config, op Op, opts ...TodoMutationOption) *TodoMutation {
	return entbuilder.NewMutation[Todo, int](&c, op, todoDescriptor, opts...)
}

// WithTodoID sets the ID field and old-value loader of the mutation.
// The getFunc callback fetches the old entity value for OldField support.
// If getFunc is nil, the old-value loader is not set (used by DeleteOneID).
func WithTodoID(id int, getFunc func(context.Context, int) (*Todo, error)) TodoMutationOption {
	return func(m *TodoMutation) {
		m.SetID(id)
		if getFunc != nil {
			m.SetOldValueLoader(func(ctx context.Context) (any, error) { return getFunc(ctx, id) })
		}
	}
}

// WithTodo sets the old Todo of the mutation.
func WithTodo(node *Todo) TodoMutationOption {
	return func(m *TodoMutation) {
		m.SetID(node.ID)
		m.SetOldValueLoader(func(context.Context) (any, error) { return node, nil })
	}
}

// WithTodoIDsFunc sets the function used to query entity IDs.
func WithTodoIDsFunc(fn func(context.Context, ...predicate.Todo) ([]int, error)) TodoMutationOption {
	return func(m *TodoMutation) {
		m.SetIDsFunc(func(ctx context.Context, preds ...func(*sql.Selector)) ([]any, error) {
			ps := make([]predicate.Todo, len(preds))
			for i, p := range preds {
				ps[i] = p
			}
			ids, err := fn(ctx, ps...)
			if err != nil {
				return nil, err
			}
			out := make([]any, len(ids))
			for i, id := range ids {
				out[i] = id
			}
			return out, nil
		})
	}
}
