// Code generated by ent, DO NOT EDIT.

package gqlgo

import (
	"entgo.io/contrib/entgqlgo"
	"entgo.io/contrib/entgqlgo/internal/parity/ent"
	"entgo.io/contrib/entgqlgo/internal/parity/ent/category"
	"entgo.io/contrib/entgqlgo/internal/parity/ent/todo"
	"entgo.io/ent/dialect/sql"
	"github.com/graphql-go/graphql"
)

// CategoryOrderFieldEnum is the GraphQL enum for ordering Category by field.
var CategoryOrderFieldEnum = graphql.NewEnum(graphql.EnumConfig{
	Name:        "CategoryOrderField",
	Description: "Properties by which Category connections can be ordered.",
	Values: graphql.EnumValueConfigMap{
		"TEXT": &graphql.EnumValueConfig{
			Value:       "TEXT",
			Description: "Order by TEXT.",
		},
	},
})

// CategoryOrderInputType is the GraphQL input type for ordering Categories.
var CategoryOrderInputType = graphql.NewInputObject(graphql.InputObjectConfig{
	Name:        "CategoryOrder",
	Description: "Ordering options for Category connections.",
	Fields: graphql.InputObjectConfigFieldMap{
		"field": &graphql.InputObjectFieldConfig{
			Type:        graphql.NewNonNull(CategoryOrderFieldEnum),
			Description: "The field to order by.",
		},
		"direction": &graphql.InputObjectFieldConfig{
			Type:         graphql.NewNonNull(OrderDirectionEnum),
			DefaultValue: entgqlgo.OrderDirectionAsc,
			Description:  "The direction to order by.",
		},
		"nullsDirection": &graphql.InputObjectFieldConfig{
			Type:        NullsDirectionEnum,
			Description: "The direction to order null values.",
		},
	},
})

// CategoryOrder represents an ordering option for Category.
type CategoryOrder struct {
	Field     string
	Direction entgqlgo.OrderDirection
	Nulls     *entgqlgo.NullsDirection
}

// ParseCategoryOrder parses a GraphQL order input map into a CategoryOrder.
func ParseCategoryOrder(m map[string]interface{}) (*CategoryOrder, error) {
	order := &CategoryOrder{
		Direction: entgqlgo.OrderDirectionAsc,
	}
	if field, ok := m["field"].(string); ok {
		order.Field = field
	}
	if dir, ok := m["direction"]; ok {
		switch v := dir.(type) {
		case entgqlgo.OrderDirection:
			order.Direction = v
		case string:
			order.Direction = entgqlgo.OrderDirection(v)
		}
	}
	if nulls, ok := m["nullsDirection"]; ok && nulls != nil {
		switch v := nulls.(type) {
		case entgqlgo.NullsDirection:
			order.Nulls = &v
		case string:
			nd := entgqlgo.NullsDirection(v)
			order.Nulls = &nd
		}
	}
	return order, nil
}

// ToOrderOption converts the order to an ent Category OrderOption.
func (o *CategoryOrder) ToOrderOption() category.OrderOption {
	if o == nil {
		return category.ByID()
	}
	opts := []sql.OrderTermOption{o.Direction.OrderTermOption()}
	if o.Nulls != nil {
		opts = append(opts, o.Nulls.OrderTermOption())
	}
	switch o.Field {
	case "TEXT":
		return category.ByText(opts...)
	default:
		return category.ByID(opts...)
	}
}

// TodoOrderFieldEnum is the GraphQL enum for ordering Todo by field.
var TodoOrderFieldEnum = graphql.NewEnum(graphql.EnumConfig{
	Name:        "TodoOrderField",
	Description: "Properties by which Todo connections can be ordered.",
	Values: graphql.EnumValueConfigMap{
		"CREATED_AT": &graphql.EnumValueConfig{
			Value:       "CREATED_AT",
			Description: "Order by CREATED_AT.",
		},
		"STATUS": &graphql.EnumValueConfig{
			Value:       "STATUS",
			Description: "Order by STATUS.",
		},
		"PRIORITY": &graphql.EnumValueConfig{
			Value:       "PRIORITY",
			Description: "Order by PRIORITY.",
		},
		"TEXT": &graphql.EnumValueConfig{
			Value:       "TEXT",
			Description: "Order by TEXT.",
		},
	},
})

// TodoOrderInputType is the GraphQL input type for ordering Todos.
var TodoOrderInputType = graphql.NewInputObject(graphql.InputObjectConfig{
	Name:        "TodoOrder",
	Description: "Ordering options for Todo connections.",
	Fields: graphql.InputObjectConfigFieldMap{
		"field": &graphql.InputObjectFieldConfig{
			Type:        graphql.NewNonNull(TodoOrderFieldEnum),
			Description: "The field to order by.",
		},
		"direction": &graphql.InputObjectFieldConfig{
			Type:         graphql.NewNonNull(OrderDirectionEnum),
			DefaultValue: entgqlgo.OrderDirectionAsc,
			Description:  "The direction to order by.",
		},
		"nullsDirection": &graphql.InputObjectFieldConfig{
			Type:        NullsDirectionEnum,
			Description: "The direction to order null values.",
		},
	},
})

// TodoOrder represents an ordering option for Todo.
type TodoOrder struct {
	Field     string
	Direction entgqlgo.OrderDirection
	Nulls     *entgqlgo.NullsDirection
}

// ParseTodoOrder parses a GraphQL order input map into a TodoOrder.
func ParseTodoOrder(m map[string]interface{}) (*TodoOrder, error) {
	order := &TodoOrder{
		Direction: entgqlgo.OrderDirectionAsc,
	}
	if field, ok := m["field"].(string); ok {
		order.Field = field
	}
	if dir, ok := m["direction"]; ok {
		switch v := dir.(type) {
		case entgqlgo.OrderDirection:
			order.Direction = v
		case string:
			order.Direction = entgqlgo.OrderDirection(v)
		}
	}
	if nulls, ok := m["nullsDirection"]; ok && nulls != nil {
		switch v := nulls.(type) {
		case entgqlgo.NullsDirection:
			order.Nulls = &v
		case string:
			nd := entgqlgo.NullsDirection(v)
			order.Nulls = &nd
		}
	}
	return order, nil
}

// ToOrderOption converts the order to an ent Todo OrderOption.
func (o *TodoOrder) ToOrderOption() todo.OrderOption {
	if o == nil {
		return todo.ByID()
	}
	opts := []sql.OrderTermOption{o.Direction.OrderTermOption()}
	if o.Nulls != nil {
		opts = append(opts, o.Nulls.OrderTermOption())
	}
	switch o.Field {
	case "CREATED_AT":
		return todo.ByCreatedAt(opts...)
	case "STATUS":
		return todo.ByStatus(opts...)
	case "PRIORITY":
		return todo.ByPriority(opts...)
	case "TEXT":
		return todo.ByText(opts...)
	default:
		return todo.ByID(opts...)
	}
}

// ParseTodoOrderList parses a list of GraphQL order inputs.
func ParseTodoOrderList(list []interface{}) ([]*TodoOrder, error) {
	orders := make([]*TodoOrder, 0, len(list))
	for _, item := range list {
		if m, ok := item.(map[string]interface{}); ok {
			order, err := ParseTodoOrder(m)
			if err != nil {
				return nil, err
			}
			orders = append(orders, order)
		}
	}
	return orders, nil
}

// ApplyTodoOrderList applies multiple order options to a query.
func ApplyTodoOrderList(query *ent.TodoQuery, orders []*TodoOrder) *ent.TodoQuery {
	for _, o := range orders {
		query = query.Order(o.ToOrderOption())
	}
	return query
}
