// Code generated by ent, DO NOT EDIT.

package gqlgo

import (
	"fmt"

	"entgo.io/contrib/entgqlgo/internal/parity/ent"
	"github.com/graphql-go/graphql"
)

// GraphQL type definitions for ent types.
// These are generated to work with github.com/graphql-go/graphql.

// CustomInterfaces maps interface names referenced by entgqlgo.Implements
// annotations to their graphql.Interface definitions. Populate this map before
// building the schema (it is read lazily when graphql.NewSchema is called).
// Interface names referenced by Implements annotations but not present in
// this map are silently omitted from the type's interface list.
var CustomInterfaces = map[string]*graphql.Interface{}

// CustomTypes maps type names referenced by entgqlgo.Type annotations (for
// types that are not built-in GraphQL scalars, e.g. custom enums or scalars
// defined outside ent) to their graphql.Type definitions. Populate this map
// before building the schema. Names referenced by Type annotations but not
// present here fall back to graphql.String (see customTypeOr).
var CustomTypes = map[string]graphql.Type{}

// ExtraFields registers additional fields on generated object types — e.g. a
// computed field with a custom resolver (Deal.taskCount) that ent itself does
// not expose. Key by the GraphQL type name (e.g. "Todo", "Deal"); the value is
// merged into that type's field map when its FieldsThunk resolves.
//
// This is the supported extension seam for adding fields to generated object
// types: because those types are built with graphql.FieldsThunk, calling
// (*Object).AddFieldConfig on them after construction is a silent no-op. Populate
// ExtraFields before NewSchema / SchemaConfig is called (it is read lazily the
// first time the schema resolves each object's fields). Entries whose key does
// not match a generated type are ignored; an extra field whose name collides
// with a generated field overrides the generated one.
var ExtraFields = map[string]graphql.Fields{}

// mergeExtraFields overlays ExtraFields[typeName] onto fields and returns it. It
// is called from each generated object's FieldsThunk so consumer-registered
// fields participate in the schema exactly like generated ones.
func mergeExtraFields(typeName string, fields graphql.Fields) graphql.Fields {
	for name, f := range ExtraFields[typeName] {
		fields[name] = f
	}
	return fields
}

// customTypeOr returns the registered custom type for name, or fallback if no
// such type has been registered in CustomTypes. graphql.Type satisfies both the
// graphql.Input and graphql.Output interfaces, so the result is usable for both
// input-object and output-object field configs.
func customTypeOr(name string, fallback graphql.Type) graphql.Type {
	if t, ok := CustomTypes[name]; ok && t != nil {
		return t
	}
	return fallback
}

var (
	// CategoryType is the GraphQL type for Category.
	CategoryType *graphql.Object
	// TodoType is the GraphQL type for Todo.
	TodoType *graphql.Object
)

func init() {
	CategoryType = graphql.NewObject(graphql.ObjectConfig{
		Name: "Category",
		Interfaces: graphql.InterfacesThunk(func() []*graphql.Interface {
			ifaces := []*graphql.Interface{NodeInterface}
			return ifaces
		}),
		Fields: graphql.FieldsThunk(func() graphql.Fields {
			return mergeExtraFields("Category", graphql.Fields{
				"text": &graphql.Field{
					Type: graphql.NewNonNull(graphql.String),
				},
				"status": &graphql.Field{
					Type: graphql.NewNonNull(CategoryStatusEnum),
				},
				"configType": &graphql.Field{
					Type: CategoryConfigTypeEnum,
				},
				"metadata": &graphql.Field{
					Type: customTypeOr("Map", graphql.String),
				},
				"id": &graphql.Field{
					Type:        graphql.NewNonNull(graphql.ID),
					Description: "The unique identifier of the Category.",
				},
				"todos": &graphql.Field{
					Type: graphql.NewNonNull(TodoConnectionType),
					Args: graphql.FieldConfigArgument{
						"after": &graphql.ArgumentConfig{
							Type:        CursorScalar,
							Description: "Returns the elements in the list that come after the specified cursor.",
						},
						"first": &graphql.ArgumentConfig{
							Type:        graphql.Int,
							Description: "Returns the first _n_ elements from the list.",
						},
						"before": &graphql.ArgumentConfig{
							Type:        CursorScalar,
							Description: "Returns the elements in the list that come before the specified cursor.",
						},
						"last": &graphql.ArgumentConfig{
							Type:        graphql.Int,
							Description: "Returns the last _n_ elements from the list.",
						},
						"where": &graphql.ArgumentConfig{
							Type:        TodoWhereInputType,
							Description: "Filtering options for Todos returned from the connection.",
						},
						"orderBy": &graphql.ArgumentConfig{
							Type:        graphql.NewList(graphql.NewNonNull(TodoOrderInputType)),
							Description: "Ordering options for Todos returned from the connection.",
						},
					},
					Resolve: resolveCategoryTodos,
				},
				"ownerC": &graphql.Field{
					Type:    TodoType,
					Resolve: resolveCategoryOwnerC,
				},
				"subStatuses": &graphql.Field{
					Type:    graphql.NewList(graphql.NewNonNull(TodoType)),
					Resolve: resolveCategorySubStatuses,
				},
			})
		}),
	})
	TodoType = graphql.NewObject(graphql.ObjectConfig{
		Name: "Todo",
		Interfaces: graphql.InterfacesThunk(func() []*graphql.Interface {
			ifaces := []*graphql.Interface{NodeInterface}
			return ifaces
		}),
		Fields: graphql.FieldsThunk(func() graphql.Fields {
			return mergeExtraFields("Todo", graphql.Fields{
				"createdAt": &graphql.Field{
					Type: graphql.NewNonNull(TimeScalar),
				},
				"status": &graphql.Field{
					Type: graphql.NewNonNull(TodoStatusEnum),
				},
				"priority": &graphql.Field{
					Type: graphql.NewNonNull(graphql.Int),
				},
				"text": &graphql.Field{
					Type: graphql.NewNonNull(graphql.String),
				},
				"note": &graphql.Field{
					Type: graphql.NewNonNull(graphql.String),
				},
				"id": &graphql.Field{
					Type:        graphql.NewNonNull(graphql.ID),
					Description: "The unique identifier of the Todo.",
				},
				"parent": &graphql.Field{
					Type:    TodoType,
					Resolve: resolveTodoParent,
				},
				"children": &graphql.Field{
					Type: graphql.NewNonNull(TodoConnectionType),
					Args: graphql.FieldConfigArgument{
						"after": &graphql.ArgumentConfig{
							Type:        CursorScalar,
							Description: "Returns the elements in the list that come after the specified cursor.",
						},
						"first": &graphql.ArgumentConfig{
							Type:        graphql.Int,
							Description: "Returns the first _n_ elements from the list.",
						},
						"before": &graphql.ArgumentConfig{
							Type:        CursorScalar,
							Description: "Returns the elements in the list that come before the specified cursor.",
						},
						"last": &graphql.ArgumentConfig{
							Type:        graphql.Int,
							Description: "Returns the last _n_ elements from the list.",
						},
						"where": &graphql.ArgumentConfig{
							Type:        TodoWhereInputType,
							Description: "Filtering options for Todos returned from the connection.",
						},
						"orderBy": &graphql.ArgumentConfig{
							Type:        graphql.NewList(graphql.NewNonNull(TodoOrderInputType)),
							Description: "Ordering options for Todos returned from the connection.",
						},
					},
					Resolve: resolveTodoChildren,
				},
				"category": &graphql.Field{
					Type:    CategoryType,
					Resolve: resolveTodoCategory,
				},
				"owner": &graphql.Field{
					Type:    graphql.NewNonNull(CategoryType),
					Resolve: resolveTodoOwner,
				},
			})
		}),
	})
}

// resolveCategoryTodos resolves the todos edge for Category
// as a Relay connection with cursor pagination.
func resolveCategoryTodos(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Category)
	if !ok {
		return nil, nil
	}
	args, err := ParsePaginationArgs(p)
	if err != nil {
		return nil, err
	}
	query := source.QueryTodos()
	// Apply where filter.
	if whereArg, ok := p.Args["where"].(map[string]interface{}); ok {
		whereInput, err := ParseTodoWhereInput(whereArg)
		if err != nil {
			return nil, fmt.Errorf("parsing where input: %w", err)
		}
		query, err = whereInput.Filter(query)
		if err != nil {
			return nil, fmt.Errorf("applying where filter: %w", err)
		}
	}
	// Eager-load nested edges selected under edges { node { ... } }.
	query = TodoQueryCollectFieldsConnection(p.Context, p.Info, query)
	var orders []*TodoOrder
	if orderByArg, ok := p.Args["orderBy"].([]interface{}); ok {
		orders, err = ParseTodoOrderList(orderByArg)
		if err != nil {
			return nil, fmt.Errorf("parsing orderBy: %w", err)
		}
	}
	return paginateTodoQuery(p.Context, query, args.After, args.Before, args.First, args.Last, orders)
}

// resolveCategoryOwnerC resolves the owner_c edge for Category.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveCategoryOwnerC(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Category)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edge := source.Edges.OwnerC; edge != nil {
		return edge, nil
	}
	// Fall back to query
	edge, err := source.QueryOwnerC().Only(p.Context)
	if err != nil {
		// For optional edges, not found is not an error - return nil
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return edge, nil
}

// resolveCategorySubStatuses resolves the sub_statuses edge for Category.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveCategorySubStatuses(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Category)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edges := source.Edges.SubStatuses; edges != nil {
		return edges, nil
	}
	// Fall back to query
	return source.QuerySubStatuses().All(p.Context)
}

// resolveTodoParent resolves the parent edge for Todo.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveTodoParent(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Parent; edge != nil {
		return edge, nil
	}
	// Fall back to query
	edge, err := source.QueryParent().Only(p.Context)
	if err != nil {
		// For optional edges, not found is not an error - return nil
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return edge, nil
}

// resolveTodoChildren resolves the children edge for Todo
// as a Relay connection with cursor pagination.
func resolveTodoChildren(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}
	args, err := ParsePaginationArgs(p)
	if err != nil {
		return nil, err
	}
	query := source.QueryChildren()
	// Apply where filter.
	if whereArg, ok := p.Args["where"].(map[string]interface{}); ok {
		whereInput, err := ParseTodoWhereInput(whereArg)
		if err != nil {
			return nil, fmt.Errorf("parsing where input: %w", err)
		}
		query, err = whereInput.Filter(query)
		if err != nil {
			return nil, fmt.Errorf("applying where filter: %w", err)
		}
	}
	// Eager-load nested edges selected under edges { node { ... } }.
	query = TodoQueryCollectFieldsConnection(p.Context, p.Info, query)
	var orders []*TodoOrder
	if orderByArg, ok := p.Args["orderBy"].([]interface{}); ok {
		orders, err = ParseTodoOrderList(orderByArg)
		if err != nil {
			return nil, fmt.Errorf("parsing orderBy: %w", err)
		}
	}
	return paginateTodoQuery(p.Context, query, args.After, args.Before, args.First, args.Last, orders)
}

// resolveTodoCategory resolves the category edge for Todo.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveTodoCategory(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Category; edge != nil {
		return edge, nil
	}
	// Fall back to query
	edge, err := source.QueryCategory().Only(p.Context)
	if err != nil {
		// For optional edges, not found is not an error - return nil
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return edge, nil
}

// resolveTodoOwner resolves the owner edge for Todo.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveTodoOwner(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Owner; edge != nil {
		return edge, nil
	}
	// Fall back to query
	edge, err := source.QueryOwner().Only(p.Context)
	if err != nil {
		// For optional edges, not found is not an error - return nil
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return edge, nil
}
