// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package todo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TodoUpdate is the builder for updating Todo entities.
type TodoUpdate struct {
	Config
	hooks    []Hook
	mutation *TodoMutation
}

// NewTodoUpdate returns a new TodoUpdate initialized with the given config, hooks, and mutation.
func NewTodoUpdate(c Config, hooks []Hook, mutation *TodoMutation) *TodoUpdate {
	return &TodoUpdate{Config: c, hooks: hooks, mutation: mutation}
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdate) Where(ps ...predicate.Todo) *TodoUpdate {
	_u.mutation.WhereP(ps...)
	return _u
}

// SetText sets the "text" field.
func (_u *TodoUpdate) SetText(v string) *TodoUpdate {
	_ = _u.mutation.SetField("text", v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableText(v *string) *TodoUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TodoUpdate) SetStatus(v Status) *TodoUpdate {
	_ = _u.mutation.SetField("status", v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableStatus(v *Status) *TodoUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TodoUpdate) SetPriority(v int) *TodoUpdate {
	_ = _u.mutation.ResetField("priority")
	_ = _u.mutation.SetField("priority", v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TodoUpdate) SetNillablePriority(v *int) *TodoUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TodoUpdate) AddPriority(v int) *TodoUpdate {
	_ = _u.mutation.AddField("priority", v)
	return _u
}

// ClearPriority clears the value of the "priority" field.
func (_u *TodoUpdate) ClearPriority() *TodoUpdate {
	_ = _u.mutation.ClearField("priority")
	return _u
}

// SetScore sets the "score" field.
func (_u *TodoUpdate) SetScore(v float64) *TodoUpdate {
	_ = _u.mutation.ResetField("score")
	_ = _u.mutation.SetField("score", v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableScore(v *float64) *TodoUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *TodoUpdate) AddScore(v float64) *TodoUpdate {
	_ = _u.mutation.AddField("score", v)
	return _u
}

// ClearScore clears the value of the "score" field.
func (_u *TodoUpdate) ClearScore() *TodoUpdate {
	_ = _u.mutation.ClearField("score")
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TodoUpdate) SetDueDate(v time.Time) *TodoUpdate {
	_ = _u.mutation.SetField("due_date", v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableDueDate(v *time.Time) *TodoUpdate {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TodoUpdate) ClearDueDate() *TodoUpdate {
	_ = _u.mutation.ClearField("due_date")
	return _u
}

// SetTags2 sets the "tags2" field.
func (_u *TodoUpdate) SetTags2(v []string) *TodoUpdate {
	_ = _u.mutation.SetField("tags2", v)
	return _u
}

// AppendTags2 appends value to the "tags2" field.
func (_u *TodoUpdate) AppendTags2(v []string) *TodoUpdate {
	_ = _u.mutation.AppendField("tags2", v)
	return _u
}

// ClearTags2 clears the value of the "tags2" field.
func (_u *TodoUpdate) ClearTags2() *TodoUpdate {
	_ = _u.mutation.ClearField("tags2")
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TodoUpdate) SetMetadata(v map[string]interface{}) *TodoUpdate {
	_ = _u.mutation.SetField("metadata", v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TodoUpdate) ClearMetadata() *TodoUpdate {
	_ = _u.mutation.ClearField("metadata")
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *TodoUpdate) SetExternalID(v uuid.UUID) *TodoUpdate {
	_ = _u.mutation.SetField("external_id", v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableExternalID(v *uuid.UUID) *TodoUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *TodoUpdate) ClearExternalID() *TodoUpdate {
	_ = _u.mutation.ClearField("external_id")
	return _u
}

// SetDuration sets the "duration" field.
func (_u *TodoUpdate) SetDuration(v int64) *TodoUpdate {
	_ = _u.mutation.ResetField("duration")
	_ = _u.mutation.SetField("duration", v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableDuration(v *int64) *TodoUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *TodoUpdate) AddDuration(v int64) *TodoUpdate {
	_ = _u.mutation.AddField("duration", v)
	return _u
}

// ClearDuration clears the value of the "duration" field.
func (_u *TodoUpdate) ClearDuration() *TodoUpdate {
	_ = _u.mutation.ClearField("duration")
	return _u
}

// SetParentID sets the "parent" edge to the Todo entity by ID.
func (_u *TodoUpdate) SetParentID(id int) *TodoUpdate {
	_ = _u.mutation.SetEdgeID("parent", id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Todo entity by ID if the given value is not nil.
func (_u *TodoUpdate) SetNillableParentID(id *int) *TodoUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// AddChildIDs adds the "children" edge to the Todo entity by IDs.
func (_u *TodoUpdate) AddChildIDs(ids ...int) *TodoUpdate {
	_ = _u.mutation.AddEdgeIDs("children", entbuilder.ToAny(ids)...)
	return _u
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *TodoUpdate) SetCategoryID(id int) *TodoUpdate {
	_ = _u.mutation.SetEdgeID("category", id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *TodoUpdate) SetNillableCategoryID(id *int) *TodoUpdate {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// Mutation returns the TodoMutation object of the builder.
func (_u *TodoUpdate) Mutation() *TodoMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Todo entity.
func (_u *TodoUpdate) ClearParent() *TodoUpdate {
	_ = _u.mutation.ClearEdge("parent")
	return _u
}

// ClearChildren clears all "children" edges to the Todo entity.
func (_u *TodoUpdate) ClearChildren() *TodoUpdate {
	_ = _u.mutation.ClearEdge("children")
	return _u
}

// RemoveChildIDs removes the "children" edge to Todo entities by IDs.
func (_u *TodoUpdate) RemoveChildIDs(ids ...int) *TodoUpdate {
	_ = _u.mutation.RemoveEdgeIDs("children", entbuilder.ToAny(ids)...)
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *TodoUpdate) ClearCategory() *TodoUpdate {
	_ = _u.mutation.ClearEdge("category")
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TodoUpdate) Save(ctx context.Context) (int, error) {
	return entbuilder.RunUpdate(ctx, &entbuilder.UpdateState[*TodoMutation]{Hooks: _u.hooks, Mutation: _u.mutation}, _u.sqlSave)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TodoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoUpdate) check() error {
	if v, ok := entbuilder.GetField[string](_u.mutation, "text"); ok {
		if err := TextValidator(v); err != nil {
			return &ValidationError{Name: "text", Err: fmt.Errorf(`ent: validator failed for field "Todo.text": %w`, err)}
		}
	}
	if v, ok := entbuilder.GetField[Status](_u.mutation, "status"); ok {
		if err := StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", Err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TodoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(Table, Columns, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	if ps := _u.mutation.MutationPredicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := entbuilder.GetField[string](_u.mutation, "text"); ok {
		_spec.SetField(FieldText, field.TypeString, value)
	}
	if value, ok := entbuilder.GetField[Status](_u.mutation, "status"); ok {
		_spec.SetField(FieldStatus, field.TypeEnum, value)
	}
	if value, ok := entbuilder.GetField[int](_u.mutation, "priority"); ok {
		_spec.SetField(FieldPriority, field.TypeInt, value)
	}
	if added, ok := _u.mutation.AddedField("priority"); ok {
		value := added.(int)
		_spec.AddField(FieldPriority, field.TypeInt, value)
	}
	if _u.mutation.FieldCleared("priority") {
		_spec.ClearField(FieldPriority, field.TypeInt)
	}
	if value, ok := entbuilder.GetField[float64](_u.mutation, "score"); ok {
		_spec.SetField(FieldScore, field.TypeFloat64, value)
	}
	if added, ok := _u.mutation.AddedField("score"); ok {
		value := added.(float64)
		_spec.AddField(FieldScore, field.TypeFloat64, value)
	}
	if _u.mutation.FieldCleared("score") {
		_spec.ClearField(FieldScore, field.TypeFloat64)
	}
	if value, ok := entbuilder.GetField[time.Time](_u.mutation, "due_date"); ok {
		_spec.SetField(FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.FieldCleared("due_date") {
		_spec.ClearField(FieldDueDate, field.TypeTime)
	}
	if value, ok := entbuilder.GetField[[]string](_u.mutation, "tags2"); ok {
		_spec.SetField(FieldTags2, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedField("tags2"); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, FieldTags2, value.([]string))
		})
	}
	if _u.mutation.FieldCleared("tags2") {
		_spec.ClearField(FieldTags2, field.TypeJSON)
	}
	if value, ok := entbuilder.GetField[map[string]interface{}](_u.mutation, "metadata"); ok {
		_spec.SetField(FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.FieldCleared("metadata") {
		_spec.ClearField(FieldMetadata, field.TypeJSON)
	}
	if value, ok := entbuilder.GetField[uuid.UUID](_u.mutation, "external_id"); ok {
		_spec.SetField(FieldExternalID, field.TypeUUID, value)
	}
	if _u.mutation.FieldCleared("external_id") {
		_spec.ClearField(FieldExternalID, field.TypeUUID)
	}
	if value, ok := entbuilder.GetField[int64](_u.mutation, "duration"); ok {
		_spec.SetField(FieldDuration, field.TypeInt64, value)
	}
	if added, ok := _u.mutation.AddedField("duration"); ok {
		value := added.(int64)
		_spec.AddField(FieldDuration, field.TypeInt64, value)
	}
	if _u.mutation.FieldCleared("duration") {
		_spec.ClearField(FieldDuration, field.TypeInt64)
	}
	if _u.mutation.EdgeCleared("parent") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ParentTable,
			Columns: []string{ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs("parent"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ParentTable,
			Columns: []string{ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EdgeCleared("children") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ChildrenTable,
			Columns: []string{ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEdgeIDs("children"); len(nodes) > 0 && !_u.mutation.EdgeCleared("children") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ChildrenTable,
			Columns: []string{ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs("children"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ChildrenTable,
			Columns: []string{ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EdgeCleared("category") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   CategoryTable,
			Columns: []string{CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs("category"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   CategoryTable,
			Columns: []string{CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.Drv, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{Label: Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{Msg: err.Error(), Wrap: err}
		}
		return 0, err
	}
	_u.mutation.SetDone()
	return _node, nil
}

// TodoUpdateOne is the builder for updating a single Todo entity.
type TodoUpdateOne struct {
	Config
	fields   []string
	hooks    []Hook
	mutation *TodoMutation
}

// NewTodoUpdateOne returns a new TodoUpdateOne initialized with the given config, hooks, and mutation.
func NewTodoUpdateOne(c Config, hooks []Hook, mutation *TodoMutation) *TodoUpdateOne {
	return &TodoUpdateOne{Config: c, hooks: hooks, mutation: mutation}
}

// SetText sets the "text" field.
func (_u *TodoUpdateOne) SetText(v string) *TodoUpdateOne {
	_ = _u.mutation.SetField("text", v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableText(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TodoUpdateOne) SetStatus(v Status) *TodoUpdateOne {
	_ = _u.mutation.SetField("status", v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableStatus(v *Status) *TodoUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TodoUpdateOne) SetPriority(v int) *TodoUpdateOne {
	_ = _u.mutation.ResetField("priority")
	_ = _u.mutation.SetField("priority", v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillablePriority(v *int) *TodoUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TodoUpdateOne) AddPriority(v int) *TodoUpdateOne {
	_ = _u.mutation.AddField("priority", v)
	return _u
}

// ClearPriority clears the value of the "priority" field.
func (_u *TodoUpdateOne) ClearPriority() *TodoUpdateOne {
	_ = _u.mutation.ClearField("priority")
	return _u
}

// SetScore sets the "score" field.
func (_u *TodoUpdateOne) SetScore(v float64) *TodoUpdateOne {
	_ = _u.mutation.ResetField("score")
	_ = _u.mutation.SetField("score", v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableScore(v *float64) *TodoUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *TodoUpdateOne) AddScore(v float64) *TodoUpdateOne {
	_ = _u.mutation.AddField("score", v)
	return _u
}

// ClearScore clears the value of the "score" field.
func (_u *TodoUpdateOne) ClearScore() *TodoUpdateOne {
	_ = _u.mutation.ClearField("score")
	return _u
}

// SetDueDate sets the "due_date" field.
func (_u *TodoUpdateOne) SetDueDate(v time.Time) *TodoUpdateOne {
	_ = _u.mutation.SetField("due_date", v)
	return _u
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableDueDate(v *time.Time) *TodoUpdateOne {
	if v != nil {
		_u.SetDueDate(*v)
	}
	return _u
}

// ClearDueDate clears the value of the "due_date" field.
func (_u *TodoUpdateOne) ClearDueDate() *TodoUpdateOne {
	_ = _u.mutation.ClearField("due_date")
	return _u
}

// SetTags2 sets the "tags2" field.
func (_u *TodoUpdateOne) SetTags2(v []string) *TodoUpdateOne {
	_ = _u.mutation.SetField("tags2", v)
	return _u
}

// AppendTags2 appends value to the "tags2" field.
func (_u *TodoUpdateOne) AppendTags2(v []string) *TodoUpdateOne {
	_ = _u.mutation.AppendField("tags2", v)
	return _u
}

// ClearTags2 clears the value of the "tags2" field.
func (_u *TodoUpdateOne) ClearTags2() *TodoUpdateOne {
	_ = _u.mutation.ClearField("tags2")
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TodoUpdateOne) SetMetadata(v map[string]interface{}) *TodoUpdateOne {
	_ = _u.mutation.SetField("metadata", v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TodoUpdateOne) ClearMetadata() *TodoUpdateOne {
	_ = _u.mutation.ClearField("metadata")
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *TodoUpdateOne) SetExternalID(v uuid.UUID) *TodoUpdateOne {
	_ = _u.mutation.SetField("external_id", v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableExternalID(v *uuid.UUID) *TodoUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// ClearExternalID clears the value of the "external_id" field.
func (_u *TodoUpdateOne) ClearExternalID() *TodoUpdateOne {
	_ = _u.mutation.ClearField("external_id")
	return _u
}

// SetDuration sets the "duration" field.
func (_u *TodoUpdateOne) SetDuration(v int64) *TodoUpdateOne {
	_ = _u.mutation.ResetField("duration")
	_ = _u.mutation.SetField("duration", v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableDuration(v *int64) *TodoUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *TodoUpdateOne) AddDuration(v int64) *TodoUpdateOne {
	_ = _u.mutation.AddField("duration", v)
	return _u
}

// ClearDuration clears the value of the "duration" field.
func (_u *TodoUpdateOne) ClearDuration() *TodoUpdateOne {
	_ = _u.mutation.ClearField("duration")
	return _u
}

// SetParentID sets the "parent" edge to the Todo entity by ID.
func (_u *TodoUpdateOne) SetParentID(id int) *TodoUpdateOne {
	_ = _u.mutation.SetEdgeID("parent", id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Todo entity by ID if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableParentID(id *int) *TodoUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// AddChildIDs adds the "children" edge to the Todo entity by IDs.
func (_u *TodoUpdateOne) AddChildIDs(ids ...int) *TodoUpdateOne {
	_ = _u.mutation.AddEdgeIDs("children", entbuilder.ToAny(ids)...)
	return _u
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *TodoUpdateOne) SetCategoryID(id int) *TodoUpdateOne {
	_ = _u.mutation.SetEdgeID("category", id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableCategoryID(id *int) *TodoUpdateOne {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// Mutation returns the TodoMutation object of the builder.
func (_u *TodoUpdateOne) Mutation() *TodoMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Todo entity.
func (_u *TodoUpdateOne) ClearParent() *TodoUpdateOne {
	_ = _u.mutation.ClearEdge("parent")
	return _u
}

// ClearChildren clears all "children" edges to the Todo entity.
func (_u *TodoUpdateOne) ClearChildren() *TodoUpdateOne {
	_ = _u.mutation.ClearEdge("children")
	return _u
}

// RemoveChildIDs removes the "children" edge to Todo entities by IDs.
func (_u *TodoUpdateOne) RemoveChildIDs(ids ...int) *TodoUpdateOne {
	_ = _u.mutation.RemoveEdgeIDs("children", entbuilder.ToAny(ids)...)
	return _u
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *TodoUpdateOne) ClearCategory() *TodoUpdateOne {
	_ = _u.mutation.ClearEdge("category")
	return _u
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdateOne) Where(ps ...predicate.Todo) *TodoUpdateOne {
	_u.mutation.WhereP(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TodoUpdateOne) Select(field string, fields ...string) *TodoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Todo entity.
func (_u *TodoUpdateOne) Save(ctx context.Context) (*Todo, error) {
	return entbuilder.RunUpdateOne[Todo](ctx, &entbuilder.UpdateState[*TodoMutation]{Hooks: _u.hooks, Mutation: _u.mutation}, _u.sqlSave)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdateOne) SaveX(ctx context.Context) *Todo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TodoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoUpdateOne) check() error {
	if v, ok := entbuilder.GetField[string](_u.mutation, "text"); ok {
		if err := TextValidator(v); err != nil {
			return &ValidationError{Name: "text", Err: fmt.Errorf(`ent: validator failed for field "Todo.text": %w`, err)}
		}
	}
	if v, ok := entbuilder.GetField[Status](_u.mutation, "status"); ok {
		if err := StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", Err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TodoUpdateOne) sqlSave(ctx context.Context) (_node *Todo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(Table, Columns, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", Err: errors.New(`ent: missing "Todo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, FieldID)
		for _, f := range fields {
			if !ValidColumn(f) {
				return nil, &ValidationError{Name: f, Err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.MutationPredicates(); len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := entbuilder.GetField[string](_u.mutation, "text"); ok {
		_spec.SetField(FieldText, field.TypeString, value)
	}
	if value, ok := entbuilder.GetField[Status](_u.mutation, "status"); ok {
		_spec.SetField(FieldStatus, field.TypeEnum, value)
	}
	if value, ok := entbuilder.GetField[int](_u.mutation, "priority"); ok {
		_spec.SetField(FieldPriority, field.TypeInt, value)
	}
	if added, ok := _u.mutation.AddedField("priority"); ok {
		value := added.(int)
		_spec.AddField(FieldPriority, field.TypeInt, value)
	}
	if _u.mutation.FieldCleared("priority") {
		_spec.ClearField(FieldPriority, field.TypeInt)
	}
	if value, ok := entbuilder.GetField[float64](_u.mutation, "score"); ok {
		_spec.SetField(FieldScore, field.TypeFloat64, value)
	}
	if added, ok := _u.mutation.AddedField("score"); ok {
		value := added.(float64)
		_spec.AddField(FieldScore, field.TypeFloat64, value)
	}
	if _u.mutation.FieldCleared("score") {
		_spec.ClearField(FieldScore, field.TypeFloat64)
	}
	if value, ok := entbuilder.GetField[time.Time](_u.mutation, "due_date"); ok {
		_spec.SetField(FieldDueDate, field.TypeTime, value)
	}
	if _u.mutation.FieldCleared("due_date") {
		_spec.ClearField(FieldDueDate, field.TypeTime)
	}
	if value, ok := entbuilder.GetField[[]string](_u.mutation, "tags2"); ok {
		_spec.SetField(FieldTags2, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedField("tags2"); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, FieldTags2, value.([]string))
		})
	}
	if _u.mutation.FieldCleared("tags2") {
		_spec.ClearField(FieldTags2, field.TypeJSON)
	}
	if value, ok := entbuilder.GetField[map[string]interface{}](_u.mutation, "metadata"); ok {
		_spec.SetField(FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.FieldCleared("metadata") {
		_spec.ClearField(FieldMetadata, field.TypeJSON)
	}
	if value, ok := entbuilder.GetField[uuid.UUID](_u.mutation, "external_id"); ok {
		_spec.SetField(FieldExternalID, field.TypeUUID, value)
	}
	if _u.mutation.FieldCleared("external_id") {
		_spec.ClearField(FieldExternalID, field.TypeUUID)
	}
	if value, ok := entbuilder.GetField[int64](_u.mutation, "duration"); ok {
		_spec.SetField(FieldDuration, field.TypeInt64, value)
	}
	if added, ok := _u.mutation.AddedField("duration"); ok {
		value := added.(int64)
		_spec.AddField(FieldDuration, field.TypeInt64, value)
	}
	if _u.mutation.FieldCleared("duration") {
		_spec.ClearField(FieldDuration, field.TypeInt64)
	}
	if _u.mutation.EdgeCleared("parent") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ParentTable,
			Columns: []string{ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs("parent"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ParentTable,
			Columns: []string{ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EdgeCleared("children") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ChildrenTable,
			Columns: []string{ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEdgeIDs("children"); len(nodes) > 0 && !_u.mutation.EdgeCleared("children") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ChildrenTable,
			Columns: []string{ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs("children"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ChildrenTable,
			Columns: []string{ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EdgeCleared("category") {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   CategoryTable,
			Columns: []string{CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EdgeIDs("category"); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   CategoryTable,
			Columns: []string{CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec("id", field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Todo{Config: _u.Config}
	_spec.Assign = _node.AssignValues
	_spec.ScanValues = _node.ScanValues
	if err = sqlgraph.UpdateNode(ctx, _u.Drv, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{Label: Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{Msg: err.Error(), Wrap: err}
		}
		return nil, err
	}
	_u.mutation.SetDone()
	return _node, nil
}
