// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package gqlgo

import (
	"github.com/graphql-go/graphql"
)

// Enum type definitions for graphql-go.
// These map ent enum fields to GraphQL enum types.

// CategoryStatusEnum is the GraphQL enum for Category.status.
var CategoryStatusEnum = graphql.NewEnum(graphql.EnumConfig{
	Name:        "CategoryStatus",
	Description: "CategoryStatus is enum for the field status",
	Values: graphql.EnumValueConfigMap{
		"ENABLED": &graphql.EnumValueConfig{
			Value: "ENABLED",
		},
		"DISABLED": &graphql.EnumValueConfig{
			Value: "DISABLED",
		},
	},
})

// TodoStatusEnum is the GraphQL enum for Todo.status.
var TodoStatusEnum = graphql.NewEnum(graphql.EnumConfig{
	Name:        "TodoStatus",
	Description: "TodoStatus is enum for the field status",
	Values: graphql.EnumValueConfigMap{
		"IN_PROGRESS": &graphql.EnumValueConfig{
			Value: "IN_PROGRESS",
		},
		"COMPLETED": &graphql.EnumValueConfig{
			Value: "COMPLETED",
		},
		"PENDING": &graphql.EnumValueConfig{
			Value: "PENDING",
		},
	},
})
