// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package gqlgo

import (
	"time"

	"entgo.io/contrib/entgqlgo/internal/todo/ent"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/todo"
	"github.com/google/uuid"
)

// CreateCategoryInput represents a mutation input for creating categories.
type CreateCategoryInput struct {
	Text       string
	Status     *category.Status
	Kind       *category.Kind
	ConfigType *category.ConfigType
	Tags       []string
	Config     map[string]string
	ExternalID *uuid.UUID
	Attributes map[string]interface{}
	Payload    []byte
	TodoIDs    []int
}

// Mutate applies the CreateCategoryInput on the CategoryMutation builder.
func (i *CreateCategoryInput) Mutate(m *ent.CategoryMutation) {
	m.SetText(i.Text)
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Kind; v != nil {
		m.SetKind(*v)
	}
	if v := i.ConfigType; v != nil {
		m.SetConfigType(*v)
	}
	if v := i.Tags; v != nil {
		m.SetTags(v)
	}
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if v := i.ExternalID; v != nil {
		m.SetExternalID(*v)
	}
	if v := i.Attributes; v != nil {
		m.SetAttributes(v)
	}
	if v := i.Payload; v != nil {
		m.SetPayload(v)
	}
	if v := i.TodoIDs; len(v) > 0 {
		m.AddTodoIDs(v...)
	}
}

// UpdateCategoryInput represents a mutation input for updating categories.
type UpdateCategoryInput struct {
	Text            *string
	Status          *category.Status
	Kind            *category.Kind
	ClearConfigType bool
	ConfigType      *category.ConfigType
	ClearTags       bool
	Tags            []string
	AppendTags      []string
	ClearConfig     bool
	Config          map[string]string
	ClearExternalID bool
	ExternalID      *uuid.UUID
	ClearAttributes bool
	Attributes      map[string]interface{}
	ClearPayload    bool
	Payload         []byte
	ClearTodos      bool
	AddTodoIDs      []int
	RemoveTodoIDs   []int
}

// Mutate applies the UpdateCategoryInput on the CategoryMutation builder.
func (i *UpdateCategoryInput) Mutate(m *ent.CategoryMutation) {
	if v := i.Text; v != nil {
		m.SetText(*v)
	}
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Kind; v != nil {
		m.SetKind(*v)
	}
	if i.ClearConfigType {
		m.ClearConfigType()
	}
	if v := i.ConfigType; v != nil {
		m.SetConfigType(*v)
	}
	if i.ClearTags {
		m.ClearTags()
	}
	if v := i.Tags; v != nil {
		m.SetTags(v)
	}
	if i.AppendTags != nil {
		m.AppendTags(i.Tags)
	}
	if i.ClearConfig {
		m.ClearConfig()
	}
	if v := i.Config; v != nil {
		m.SetConfig(v)
	}
	if i.ClearExternalID {
		m.ClearExternalID()
	}
	if v := i.ExternalID; v != nil {
		m.SetExternalID(*v)
	}
	if i.ClearAttributes {
		m.ClearAttributes()
	}
	if v := i.Attributes; v != nil {
		m.SetAttributes(v)
	}
	if i.ClearPayload {
		m.ClearPayload()
	}
	if v := i.Payload; v != nil {
		m.SetPayload(v)
	}
	if i.ClearTodos {
		m.ClearTodos()
	}
	if v := i.AddTodoIDs; len(v) > 0 {
		m.AddTodoIDs(v...)
	}
	if v := i.RemoveTodoIDs; len(v) > 0 {
		m.RemoveTodoIDs(v...)
	}
}

// CreateFriendshipInput represents a mutation input for creating friendships.
type CreateFriendshipInput struct {
	TodoID     int
	CategoryID int
}

// Mutate applies the CreateFriendshipInput on the FriendshipMutation builder.
func (i *CreateFriendshipInput) Mutate(m *ent.FriendshipMutation) {
	m.SetTodoID(i.TodoID)
	m.SetCategoryID(i.CategoryID)
}

// CreateTodoInput represents a mutation input for creating todos.
type CreateTodoInput struct {
	Status     todo.Status
	Priority   *int
	Text       string
	Score      *float64
	DueDate    *time.Time
	Tags2      []string
	Metadata   map[string]interface{}
	ExternalID *uuid.UUID
	Duration   *int64
	ParentID   *int
	ChildIDs   []int
	CategoryID *int
}

// Mutate applies the CreateTodoInput on the TodoMutation builder.
func (i *CreateTodoInput) Mutate(m *ent.TodoMutation) {
	m.SetStatus(i.Status)
	if v := i.Priority; v != nil {
		m.SetPriority(*v)
	}
	m.SetText(i.Text)
	if v := i.Score; v != nil {
		m.SetScore(*v)
	}
	if v := i.DueDate; v != nil {
		m.SetDueDate(*v)
	}
	if v := i.Tags2; v != nil {
		m.SetTags2(v)
	}
	if v := i.Metadata; v != nil {
		m.SetMetadata(v)
	}
	if v := i.ExternalID; v != nil {
		m.SetExternalID(*v)
	}
	if v := i.Duration; v != nil {
		m.SetDuration(*v)
	}
	if v := i.ParentID; v != nil {
		m.SetParentID(*v)
	}
	if v := i.ChildIDs; len(v) > 0 {
		m.AddChildIDs(v...)
	}
	if v := i.CategoryID; v != nil {
		m.SetCategoryID(*v)
	}
}

// UpdateTodoInput represents a mutation input for updating todos.
type UpdateTodoInput struct {
	Status          *todo.Status
	Priority        *int
	Text            *string
	ClearScore      bool
	Score           *float64
	ClearDueDate    bool
	DueDate         *time.Time
	ClearTags2      bool
	Tags2           []string
	AppendTags2     []string
	ClearMetadata   bool
	Metadata        map[string]interface{}
	ClearExternalID bool
	ExternalID      *uuid.UUID
	ClearDuration   bool
	Duration        *int64
	ClearParent     bool
	ParentID        *int
	ClearChildren   bool
	AddChildIDs     []int
	RemoveChildIDs  []int
	ClearCategory   bool
	CategoryID      *int
}

// Mutate applies the UpdateTodoInput on the TodoMutation builder.
func (i *UpdateTodoInput) Mutate(m *ent.TodoMutation) {
	if v := i.Status; v != nil {
		m.SetStatus(*v)
	}
	if v := i.Priority; v != nil {
		m.SetPriority(*v)
	}
	if v := i.Text; v != nil {
		m.SetText(*v)
	}
	if i.ClearScore {
		m.ClearScore()
	}
	if v := i.Score; v != nil {
		m.SetScore(*v)
	}
	if i.ClearDueDate {
		m.ClearDueDate()
	}
	if v := i.DueDate; v != nil {
		m.SetDueDate(*v)
	}
	if i.ClearTags2 {
		m.ClearTags2()
	}
	if v := i.Tags2; v != nil {
		m.SetTags2(v)
	}
	if i.AppendTags2 != nil {
		m.AppendTags2(i.Tags2)
	}
	if i.ClearMetadata {
		m.ClearMetadata()
	}
	if v := i.Metadata; v != nil {
		m.SetMetadata(v)
	}
	if i.ClearExternalID {
		m.ClearExternalID()
	}
	if v := i.ExternalID; v != nil {
		m.SetExternalID(*v)
	}
	if i.ClearDuration {
		m.ClearDuration()
	}
	if v := i.Duration; v != nil {
		m.SetDuration(*v)
	}
	if i.ClearParent {
		m.ClearParent()
	}
	if v := i.ParentID; v != nil {
		m.SetParentID(*v)
	}
	if i.ClearChildren {
		m.ClearChildren()
	}
	if v := i.AddChildIDs; len(v) > 0 {
		m.AddChildIDs(v...)
	}
	if v := i.RemoveChildIDs; len(v) > 0 {
		m.RemoveChildIDs(v...)
	}
	if i.ClearCategory {
		m.ClearCategory()
	}
	if v := i.CategoryID; v != nil {
		m.SetCategoryID(*v)
	}
}
