// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package gqlgo

import (
	"fmt"

	"entgo.io/contrib/entgqlgo"
	"entgo.io/contrib/entgqlgo/internal/todo/ent"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/todo"
	"github.com/graphql-go/graphql"
)

// Resolvers contains resolver methods for the GraphQL schema.
type Resolvers struct {
	client *ent.Client
}

// NewResolvers creates a new Resolvers instance.
func NewResolvers(client *ent.Client) *Resolvers {
	return &Resolvers{client: client}
}

// QueryCategories resolves the query for listing Categories.
func (r *Resolvers) QueryCategories(p graphql.ResolveParams) (interface{}, error) {
	query := r.client.Category.Query()

	// Apply eager loading based on GraphQL field selection
	if entgqlgo.HasField(p.Info, "todos") {
		query = query.WithTodos()
	}

	// Apply pagination arguments
	if first, ok := p.Args["first"].(int); ok && first > 0 {
		query = query.Limit(first)
	}
	if offset, ok := p.Args["offset"].(int); ok && offset > 0 {
		query = query.Offset(offset)
	}

	return query.All(p.Context)
}

// QueryCategory resolves the query for a single Category by ID.
func (r *Resolvers) QueryCategory(p graphql.ResolveParams) (interface{}, error) {
	id, ok := p.Args["id"]
	if !ok {
		return nil, fmt.Errorf("id argument is required")
	}

	query := r.client.Category.Query()

	// Apply eager loading based on GraphQL field selection
	if entgqlgo.HasField(p.Info, "todos") {
		query = query.WithTodos()
	}
	idInt, err := toInt(id)
	if err != nil {
		return nil, err
	}
	return query.Where(category.ID(idInt)).Only(p.Context)
}

// CreateCategory resolves the mutation for creating a Category.
func (r *Resolvers) CreateCategory(p graphql.ResolveParams) (interface{}, error) {
	create := r.client.Category.Create()
	if v, ok := p.Args["text"]; ok && v != nil {
		create = create.SetText(v.(string))
	}

	return create.Save(p.Context)
}

// UpdateCategory resolves the mutation for updating a Category.
func (r *Resolvers) UpdateCategory(p graphql.ResolveParams) (interface{}, error) {
	id, ok := p.Args["id"]
	if !ok {
		return nil, fmt.Errorf("id argument is required")
	}
	idInt, err := toInt(id)
	if err != nil {
		return nil, err
	}
	update := r.client.Category.UpdateOneID(idInt)
	if v, ok := p.Args["text"]; ok && v != nil {
		update = update.SetText(v.(string))
	}
	if v, ok := p.Args["status"]; ok && v != nil {
		update = update.SetStatus(v.(category.Status))
	}

	return update.Save(p.Context)
}

// DeleteCategory resolves the mutation for deleting a Category.
func (r *Resolvers) DeleteCategory(p graphql.ResolveParams) (interface{}, error) {
	id, ok := p.Args["id"]
	if !ok {
		return false, fmt.Errorf("id argument is required")
	}
	idInt, err := toInt(id)
	if err != nil {
		return false, err
	}
	err = r.client.Category.DeleteOneID(idInt).Exec(p.Context)
	return err == nil, err
}

// ResolveCategoryTodos resolves the todos edge for Category.
func (r *Resolvers) ResolveCategoryTodos(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Category)
	if !ok {
		return nil, nil
	}

	// Check if edge was already loaded via eager loading
	if edges := source.Edges.Todos; edges != nil {
		return edges, nil
	}

	// Fall back to query
	return source.QueryTodos().All(p.Context)
}

// QueryTodos resolves the query for listing Todos.
func (r *Resolvers) QueryTodos(p graphql.ResolveParams) (interface{}, error) {
	query := r.client.Todo.Query()

	// Apply eager loading based on GraphQL field selection
	if entgqlgo.HasField(p.Info, "parent") {
		query = query.WithParent()
	}
	if entgqlgo.HasField(p.Info, "children") {
		query = query.WithChildren()
	}
	if entgqlgo.HasField(p.Info, "category") {
		query = query.WithCategory()
	}

	// Apply pagination arguments
	if first, ok := p.Args["first"].(int); ok && first > 0 {
		query = query.Limit(first)
	}
	if offset, ok := p.Args["offset"].(int); ok && offset > 0 {
		query = query.Offset(offset)
	}

	return query.All(p.Context)
}

// QueryTodo resolves the query for a single Todo by ID.
func (r *Resolvers) QueryTodo(p graphql.ResolveParams) (interface{}, error) {
	id, ok := p.Args["id"]
	if !ok {
		return nil, fmt.Errorf("id argument is required")
	}

	query := r.client.Todo.Query()

	// Apply eager loading based on GraphQL field selection
	if entgqlgo.HasField(p.Info, "parent") {
		query = query.WithParent()
	}
	if entgqlgo.HasField(p.Info, "children") {
		query = query.WithChildren()
	}
	if entgqlgo.HasField(p.Info, "category") {
		query = query.WithCategory()
	}
	idInt, err := toInt(id)
	if err != nil {
		return nil, err
	}
	return query.Where(todo.ID(idInt)).Only(p.Context)
}

// CreateTodo resolves the mutation for creating a Todo.
func (r *Resolvers) CreateTodo(p graphql.ResolveParams) (interface{}, error) {
	create := r.client.Todo.Create()
	if v, ok := p.Args["status"]; ok && v != nil {
		create = create.SetStatus(v.(todo.Status))
	}
	if v, ok := p.Args["text"]; ok && v != nil {
		create = create.SetText(v.(string))
	}

	return create.Save(p.Context)
}

// UpdateTodo resolves the mutation for updating a Todo.
func (r *Resolvers) UpdateTodo(p graphql.ResolveParams) (interface{}, error) {
	id, ok := p.Args["id"]
	if !ok {
		return nil, fmt.Errorf("id argument is required")
	}
	idInt, err := toInt(id)
	if err != nil {
		return nil, err
	}
	update := r.client.Todo.UpdateOneID(idInt)
	if v, ok := p.Args["status"]; ok && v != nil {
		update = update.SetStatus(v.(todo.Status))
	}
	if v, ok := p.Args["priority"]; ok && v != nil {
		val, err := toInt(v)
		if err != nil {
			return nil, err
		}
		update = update.SetPriority(int(val))
	}
	if v, ok := p.Args["text"]; ok && v != nil {
		update = update.SetText(v.(string))
	}

	return update.Save(p.Context)
}

// DeleteTodo resolves the mutation for deleting a Todo.
func (r *Resolvers) DeleteTodo(p graphql.ResolveParams) (interface{}, error) {
	id, ok := p.Args["id"]
	if !ok {
		return false, fmt.Errorf("id argument is required")
	}
	idInt, err := toInt(id)
	if err != nil {
		return false, err
	}
	err = r.client.Todo.DeleteOneID(idInt).Exec(p.Context)
	return err == nil, err
}

// ResolveTodoParent resolves the parent edge for Todo.
func (r *Resolvers) ResolveTodoParent(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}

	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Parent; edge != nil {
		return edge, nil
	}

	// Fall back to query
	return source.QueryParent().Only(p.Context)
}

// ResolveTodoChildren resolves the children edge for Todo.
func (r *Resolvers) ResolveTodoChildren(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}

	// Check if edge was already loaded via eager loading
	if edges := source.Edges.Children; edges != nil {
		return edges, nil
	}

	// Fall back to query
	return source.QueryChildren().All(p.Context)
}

// ResolveTodoCategory resolves the category edge for Todo.
func (r *Resolvers) ResolveTodoCategory(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}

	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Category; edge != nil {
		return edge, nil
	}

	// Fall back to query
	return source.QueryCategory().Only(p.Context)
}

// Helper functions

// toInt converts various types to int.
func toInt(v interface{}) (int, error) {
	switch val := v.(type) {
	case int:
		return val, nil
	case int64:
		return int(val), nil
	case float64:
		return int(val), nil
	case string:
		var i int
		_, err := fmt.Sscanf(val, "%d", &i)
		return i, err
	default:
		return 0, fmt.Errorf("cannot convert %T to int", v)
	}
}
