// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package gqlgo

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"entgo.io/contrib/entgqlgo/internal/todo/ent"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/todo"
	"github.com/google/uuid"
	"github.com/graphql-go/graphql"
)

// ClientFromContext returns the client stored in the context if present,
// otherwise falls back to the provided client. This enables transactional
// operations when the context carries a transactional client (see WithTx).
func ClientFromContext(ctx context.Context, fallback *ent.Client) *ent.Client {
	if c := ent.FromContext(ctx); c != nil {
		return c
	}
	return fallback
}

// clientFromContext is kept as an internal alias used by generated resolvers.
func clientFromContext(ctx context.Context, fallback *ent.Client) *ent.Client {
	return ClientFromContext(ctx, fallback)
}

// SchemaOption configures the generated schema.
type SchemaOption func(*schemaOptions)

type schemaOptions struct {
	transactions bool
}

// WithTransactions wraps every generated mutation resolver in a database
// transaction. The transactional client is propagated via context, so all ent
// operations inside the resolver participate in the same transaction.
//
// Note: unlike entgql's Transactioner middleware (which wraps the entire
// GraphQL operation in one transaction), each top-level mutation field runs
// in its own transaction, because graphql-go has no operation-level
// middleware. A request with multiple mutation fields runs multiple
// independent transactions.
func WithTransactions() SchemaOption {
	return func(o *schemaOptions) {
		o.transactions = true
	}
}

// WithTx wraps a resolver so it runs inside a transaction opened on client.
// On success the transaction is committed; on error or panic it is rolled back.
// The transactional client is stored in the resolver context and can be
// retrieved with ClientFromContext.
func WithTx(client *ent.Client, resolve graphql.FieldResolveFn) graphql.FieldResolveFn {
	return func(p graphql.ResolveParams) (result interface{}, err error) {
		tx, err := client.Tx(p.Context)
		if err != nil {
			return nil, fmt.Errorf("opening transaction: %w", err)
		}
		defer func() {
			if r := recover(); r != nil {
				_ = tx.Rollback()
				panic(r)
			}
		}()
		p.Context = ent.NewContext(p.Context, tx.Client())
		result, err = resolve(p)
		if err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				err = fmt.Errorf("%w: rolling back transaction: %v", err, rerr)
			}
			return nil, err
		}
		if cerr := tx.Commit(); cerr != nil {
			return nil, fmt.Errorf("committing transaction: %w", cerr)
		}
		return result, nil
	}
}

// maybeWithTx wraps the resolver in a transaction when transactions are enabled.
func maybeWithTx(client *ent.Client, o *schemaOptions, resolve graphql.FieldResolveFn) graphql.FieldResolveFn {
	if o == nil || !o.transactions {
		return resolve
	}
	return WithTx(client, resolve)
}

// SchemaConfig returns the graphql.SchemaConfig used to build the generated schema.
// Callers may modify the returned config before building the schema with
// graphql.NewSchema — e.g. add custom query/mutation fields with
// cfg.Query.AddFieldConfig(...) or attach a Subscription root type.
// opts are applied to configure schema behaviour (e.g. WithTransactions).
func SchemaConfig(client *ent.Client, opts ...SchemaOption) graphql.SchemaConfig {
	o := &schemaOptions{}
	for _, opt := range opts {
		opt(o)
	}
	return graphql.SchemaConfig{
		Query:    newQueryType(client),
		Mutation: newMutationType(client, o),
	}
}

// NewSchema creates a new GraphQL schema with Query and Mutation types.
// The client is used for database operations in resolvers.
// opts are applied to configure schema behaviour (e.g. WithTransactions).
func NewSchema(client *ent.Client, opts ...SchemaOption) (graphql.Schema, error) {
	return graphql.NewSchema(SchemaConfig(client, opts...))
}

// newQueryType creates the root Query type.
func newQueryType(client *ent.Client) *graphql.Object {
	return graphql.NewObject(graphql.ObjectConfig{
		Name: "Query",
		Fields: graphql.Fields{
			"billProducts": &graphql.Field{
				Type: graphql.NewNonNull(graphql.NewList(graphql.NewNonNull(BillProductType))),
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					c := clientFromContext(p.Context, client)
					query := c.BillProduct.Query()
					query = BillProductQueryCollectFields(p.Context, p.Info, query)
					return query.All(p.Context)
				},
			},
			"categories": &graphql.Field{
				Type: graphql.NewNonNull(CategoryConnectionType),
				Args: graphql.FieldConfigArgument{
					"after": &graphql.ArgumentConfig{
						Type:        CursorScalar,
						Description: "Returns the elements in the list that come after the specified cursor.",
					},
					"first": &graphql.ArgumentConfig{
						Type:        graphql.Int,
						Description: "Returns the first _n_ elements from the list.",
					},
					"before": &graphql.ArgumentConfig{
						Type:        CursorScalar,
						Description: "Returns the elements in the list that come before the specified cursor.",
					},
					"last": &graphql.ArgumentConfig{
						Type:        graphql.Int,
						Description: "Returns the last _n_ elements from the list.",
					},
					"orderBy": &graphql.ArgumentConfig{
						Type:        CategoryOrderInputType,
						Description: "Ordering options for Categories returned from the connection.",
					},
					"where": &graphql.ArgumentConfig{
						Type:        CategoryWhereInputType,
						Description: "Filtering options for Categories returned from the connection.",
					},
				},
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					args, err := ParsePaginationArgs(p)
					if err != nil {
						return nil, err
					}
					c := clientFromContext(p.Context, client)
					query := c.Category.Query()
					// Apply where filter.
					if whereArg, ok := p.Args["where"].(map[string]interface{}); ok {
						whereInput, err := ParseCategoryWhereInput(p.Context, whereArg)
						if err != nil {
							return nil, fmt.Errorf("parsing where input: %w", err)
						}
						query, err = whereInput.Filter(query)
						if err != nil {
							return nil, fmt.Errorf("applying where filter: %w", err)
						}
					}
					// Eager-load edges selected under edges { node { ... } }.
					query = CategoryQueryCollectFieldsConnection(p.Context, p.Info, query)
					var order *CategoryOrder
					if orderByArg, ok := p.Args["orderBy"].(map[string]interface{}); ok {
						order, err = ParseCategoryOrder(orderByArg)
						if err != nil {
							return nil, fmt.Errorf("parsing orderBy: %w", err)
						}
					}
					return paginateCategoryQuery(p.Context, query, args.After, args.Before, args.First, args.Last, order)
				},
			},
			"todos": &graphql.Field{
				Type:        graphql.NewNonNull(TodoConnectionType),
				Description: "This is the todo item",
				Args: graphql.FieldConfigArgument{
					"after": &graphql.ArgumentConfig{
						Type:        CursorScalar,
						Description: "Returns the elements in the list that come after the specified cursor.",
					},
					"first": &graphql.ArgumentConfig{
						Type:        graphql.Int,
						Description: "Returns the first _n_ elements from the list.",
					},
					"before": &graphql.ArgumentConfig{
						Type:        CursorScalar,
						Description: "Returns the elements in the list that come before the specified cursor.",
					},
					"last": &graphql.ArgumentConfig{
						Type:        graphql.Int,
						Description: "Returns the last _n_ elements from the list.",
					},
					"orderBy": &graphql.ArgumentConfig{
						Type:        graphql.NewList(graphql.NewNonNull(TodoOrderInputType)),
						Description: "Ordering options for Todos returned from the connection.",
					},
					"where": &graphql.ArgumentConfig{
						Type:        TodoWhereInputType,
						Description: "Filtering options for Todos returned from the connection.",
					},
				},
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					args, err := ParsePaginationArgs(p)
					if err != nil {
						return nil, err
					}
					c := clientFromContext(p.Context, client)
					query := c.Todo.Query()
					// Apply where filter.
					if whereArg, ok := p.Args["where"].(map[string]interface{}); ok {
						whereInput, err := ParseTodoWhereInput(p.Context, whereArg)
						if err != nil {
							return nil, fmt.Errorf("parsing where input: %w", err)
						}
						query, err = whereInput.Filter(query)
						if err != nil {
							return nil, fmt.Errorf("applying where filter: %w", err)
						}
					}
					// Eager-load edges selected under edges { node { ... } }.
					query = TodoQueryCollectFieldsConnection(p.Context, p.Info, query)
					var orders []*TodoOrder
					if orderByArg, ok := p.Args["orderBy"].([]interface{}); ok {
						orders, err = ParseTodoOrderList(orderByArg)
						if err != nil {
							return nil, fmt.Errorf("parsing orderBy: %w", err)
						}
					}
					return paginateTodoQuery(p.Context, query, args.After, args.Before, args.First, args.Last, orders)
				},
			}, "node": &graphql.Field{
				Type: NodeInterface,
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the node.",
					},
				},
				Description: "Fetches an object given its ID.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return nil, nil
					}
					c := clientFromContext(p.Context, client)
					return Noder_(c, p.Context, fmt.Sprint(id))
				},
			},
			"nodes": &graphql.Field{
				Type: graphql.NewNonNull(graphql.NewList(NodeInterface)),
				Args: graphql.FieldConfigArgument{
					"ids": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.NewList(graphql.NewNonNull(graphql.ID))),
						Description: "The IDs of the nodes.",
					},
				},
				Description: "Fetches objects given their IDs.",
				Resolve: func(p graphql.ResolveParams) (interface{}, error) {
					ids, ok := p.Args["ids"].([]interface{})
					if !ok {
						return nil, nil
					}
					c := clientFromContext(p.Context, client)
					return Noders(c, p.Context, ids)
				},
			},
		},
	})
}

// newMutationType creates the root Mutation type.
func newMutationType(client *ent.Client, o *schemaOptions) *graphql.Object {
	return graphql.NewObject(graphql.ObjectConfig{
		Name: "Mutation",
		Fields: graphql.Fields{
			"createCategory": &graphql.Field{
				Type: graphql.NewNonNull(CategoryType),
				Args: graphql.FieldConfigArgument{
					"input": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(CreateCategoryInputType),
						Description: "Input for creating a Category.",
					},
				},
				Description: "Create a new Category.",
				Resolve: maybeWithTx(client, o, func(p graphql.ResolveParams) (interface{}, error) {
					inputArg, ok := p.Args["input"]
					if !ok {
						return nil, fmt.Errorf("input is required")
					}
					inputMap, ok := inputArg.(map[string]interface{})
					if !ok {
						return nil, fmt.Errorf("input must be an object")
					}
					input, err := ParseCreateCategoryInput(inputMap)
					if err != nil {
						return nil, fmt.Errorf("parsing input: %w", err)
					}
					c := clientFromContext(p.Context, client)
					builder := c.Category.Create()
					input.Mutate(builder.Mutation())
					return builder.Save(p.Context)
				}),
			},
			"updateCategory": &graphql.Field{
				Type: graphql.NewNonNull(CategoryType),
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the Category to update.",
					},
					"input": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(UpdateCategoryInputType),
						Description: "Input for updating a Category.",
					},
				},
				Description: "Update an existing Category.",
				Resolve: maybeWithTx(client, o, func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return nil, fmt.Errorf("id is required")
					}
					inputArg, ok := p.Args["input"]
					if !ok {
						return nil, fmt.Errorf("input is required")
					}
					inputMap, ok := inputArg.(map[string]interface{})
					if !ok {
						return nil, fmt.Errorf("input must be an object")
					}
					input, err := ParseUpdateCategoryInput(inputMap)
					if err != nil {
						return nil, fmt.Errorf("parsing input: %w", err)
					}
					c := clientFromContext(p.Context, client)
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return nil, err
					}
					builder := c.Category.UpdateOneID(idInt)
					input.Mutate(builder.Mutation())
					return builder.Save(p.Context)
				}),
			},
			"deleteCategory": &graphql.Field{
				Type: graphql.NewNonNull(graphql.Boolean),
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the Category to delete.",
					},
				},
				Description: "Delete a Category.",
				Resolve: maybeWithTx(client, o, func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return false, fmt.Errorf("id is required")
					}
					c := clientFromContext(p.Context, client)
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return false, err
					}
					err = c.Category.DeleteOneID(idInt).Exec(p.Context)
					return err == nil, err
				}),
			},
			"createFriendship": &graphql.Field{
				Type: graphql.NewNonNull(FriendshipType),
				Args: graphql.FieldConfigArgument{
					"input": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(CreateFriendshipInputType),
						Description: "Input for creating a Friendship.",
					},
				},
				Description: "Create a new Friendship.",
				Resolve: maybeWithTx(client, o, func(p graphql.ResolveParams) (interface{}, error) {
					inputArg, ok := p.Args["input"]
					if !ok {
						return nil, fmt.Errorf("input is required")
					}
					inputMap, ok := inputArg.(map[string]interface{})
					if !ok {
						return nil, fmt.Errorf("input must be an object")
					}
					input, err := ParseCreateFriendshipInput(inputMap)
					if err != nil {
						return nil, fmt.Errorf("parsing input: %w", err)
					}
					c := clientFromContext(p.Context, client)
					builder := c.Friendship.Create()
					input.Mutate(builder.Mutation())
					return builder.Save(p.Context)
				}),
			},
			"createTodo": &graphql.Field{
				Type: graphql.NewNonNull(TodoType),
				Args: graphql.FieldConfigArgument{
					"input": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(CreateTodoInputType),
						Description: "Input for creating a Todo.",
					},
				},
				Description: "Create a new Todo.",
				Resolve: maybeWithTx(client, o, func(p graphql.ResolveParams) (interface{}, error) {
					inputArg, ok := p.Args["input"]
					if !ok {
						return nil, fmt.Errorf("input is required")
					}
					inputMap, ok := inputArg.(map[string]interface{})
					if !ok {
						return nil, fmt.Errorf("input must be an object")
					}
					input, err := ParseCreateTodoInput(inputMap)
					if err != nil {
						return nil, fmt.Errorf("parsing input: %w", err)
					}
					c := clientFromContext(p.Context, client)
					builder := c.Todo.Create()
					input.Mutate(builder.Mutation())
					return builder.Save(p.Context)
				}),
			},
			"updateTodo": &graphql.Field{
				Type: graphql.NewNonNull(TodoType),
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the Todo to update.",
					},
					"input": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(UpdateTodoInputType),
						Description: "Input for updating a Todo.",
					},
				},
				Description: "Update an existing Todo.",
				Resolve: maybeWithTx(client, o, func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return nil, fmt.Errorf("id is required")
					}
					inputArg, ok := p.Args["input"]
					if !ok {
						return nil, fmt.Errorf("input is required")
					}
					inputMap, ok := inputArg.(map[string]interface{})
					if !ok {
						return nil, fmt.Errorf("input must be an object")
					}
					input, err := ParseUpdateTodoInput(inputMap)
					if err != nil {
						return nil, fmt.Errorf("parsing input: %w", err)
					}
					c := clientFromContext(p.Context, client)
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return nil, err
					}
					builder := c.Todo.UpdateOneID(idInt)
					input.Mutate(builder.Mutation())
					return builder.Save(p.Context)
				}),
			},
			"deleteTodo": &graphql.Field{
				Type: graphql.NewNonNull(graphql.Boolean),
				Args: graphql.FieldConfigArgument{
					"id": &graphql.ArgumentConfig{
						Type:        graphql.NewNonNull(graphql.ID),
						Description: "The ID of the Todo to delete.",
					},
				},
				Description: "Delete a Todo.",
				Resolve: maybeWithTx(client, o, func(p graphql.ResolveParams) (interface{}, error) {
					id, ok := p.Args["id"]
					if !ok {
						return false, fmt.Errorf("id is required")
					}
					c := clientFromContext(p.Context, client)
					idInt, err := strconv.Atoi(fmt.Sprint(id))
					if err != nil {
						return false, err
					}
					err = c.Todo.DeleteOneID(idInt).Exec(p.Context)
					return err == nil, err
				}),
			},
		},
	})
}

var (
	// CreateCategoryInputType is the GraphQL input type for creating a Category.
	CreateCategoryInputType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name: "CreateCategoryInput",
		Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"text": &graphql.InputObjectFieldConfig{
					Type: graphql.NewNonNull(graphql.String),
				},
				"status": &graphql.InputObjectFieldConfig{
					Type: CategoryStatusEnum,
				},
				"kind": &graphql.InputObjectFieldConfig{
					Type: CategoryKindEnum,
				},
				"configType": &graphql.InputObjectFieldConfig{
					Type: CategoryConfigTypeEnum,
				},
				"tags": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"config": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("CustomScalarXYZ", graphql.String),
				},
				"externalID": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("UUID", graphql.ID),
				},
				"attributes": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("Map", graphql.String),
				},
				"payload": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("Upload", graphql.String),
				},
				"todoIDs": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(graphql.ID)),
					Description: "IDs of the todos edges.",
				},
			}
		}),
	})
	// UpdateCategoryInputType is the GraphQL input type for updating a Category.
	UpdateCategoryInputType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name: "UpdateCategoryInput",
		Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"text": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"status": &graphql.InputObjectFieldConfig{
					Type: CategoryStatusEnum,
				},
				"kind": &graphql.InputObjectFieldConfig{
					Type: CategoryKindEnum,
				},
				"configType": &graphql.InputObjectFieldConfig{
					Type: CategoryConfigTypeEnum,
				},
				"clearConfigType": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the configType field.",
				},
				"tags": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"clearTags": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the tags field.",
				},
				"config": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("CustomScalarXYZ", graphql.String),
				},
				"clearConfig": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the config field.",
				},
				"externalID": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("UUID", graphql.ID),
				},
				"clearExternalID": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the externalID field.",
				},
				"attributes": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("Map", graphql.String),
				},
				"clearAttributes": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the attributes field.",
				},
				"payload": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("Upload", graphql.String),
				},
				"clearPayload": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the payload field.",
				},
				"addTodoIDs": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(graphql.ID)),
					Description: "IDs to add to the todos edges.",
				},
				"removeTodoIDs": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(graphql.ID)),
					Description: "IDs to remove from the todos edges.",
				},
				"clearTodos": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear all todos edges.",
				},
			}
		}),
	})
	// CreateFriendshipInputType is the GraphQL input type for creating a Friendship.
	CreateFriendshipInputType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name: "CreateFriendshipInput",
		Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"todoID": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewNonNull(graphql.ID),
					Description: "ID of the todo edge.",
				},
				"categoryID": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewNonNull(graphql.ID),
					Description: "ID of the category edge.",
				},
			}
		}),
	})
	// CreateTodoInputType is the GraphQL input type for creating a Todo.
	CreateTodoInputType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name: "CreateTodoInput",
		Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"status": &graphql.InputObjectFieldConfig{
					Type: graphql.NewNonNull(TodoStatusEnum),
				},
				"priority": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"text": &graphql.InputObjectFieldConfig{
					Type: graphql.NewNonNull(graphql.String),
				},
				"score": &graphql.InputObjectFieldConfig{
					Type: graphql.Float,
				},
				"dueDate": &graphql.InputObjectFieldConfig{
					Type: TimeScalar,
				},
				"tags2": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"metadata": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("Map", graphql.String),
				},
				"externalID": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("UUID", graphql.ID),
				},
				"duration": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"parentID": &graphql.InputObjectFieldConfig{
					Type:        graphql.ID,
					Description: "ID of the parent edge.",
				},
				"childIDs": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(graphql.ID)),
					Description: "IDs of the children edges.",
				},
				"categoryID": &graphql.InputObjectFieldConfig{
					Type:        graphql.ID,
					Description: "ID of the category edge.",
				},
			}
		}),
	})
	// UpdateTodoInputType is the GraphQL input type for updating a Todo.
	UpdateTodoInputType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name: "UpdateTodoInput",
		Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"status": &graphql.InputObjectFieldConfig{
					Type: TodoStatusEnum,
				},
				"priority": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"text": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"score": &graphql.InputObjectFieldConfig{
					Type: graphql.Float,
				},
				"clearScore": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the score field.",
				},
				"dueDate": &graphql.InputObjectFieldConfig{
					Type: TimeScalar,
				},
				"clearDueDate": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the dueDate field.",
				},
				"tags2": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"clearTags2": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the tags2 field.",
				},
				"metadata": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("Map", graphql.String),
				},
				"clearMetadata": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the metadata field.",
				},
				"externalID": &graphql.InputObjectFieldConfig{
					Type: customTypeOr("UUID", graphql.ID),
				},
				"clearExternalID": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the externalID field.",
				},
				"duration": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"clearDuration": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the duration field.",
				},
				"parentID": &graphql.InputObjectFieldConfig{
					Type:        graphql.ID,
					Description: "ID of the parent edge.",
				},
				"clearParent": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the parent edge.",
				},
				"addChildIDs": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(graphql.ID)),
					Description: "IDs to add to the children edges.",
				},
				"removeChildIDs": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(graphql.ID)),
					Description: "IDs to remove from the children edges.",
				},
				"clearChildren": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear all children edges.",
				},
				"categoryID": &graphql.InputObjectFieldConfig{
					Type:        graphql.ID,
					Description: "ID of the category edge.",
				},
				"clearCategory": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Clear the category edge.",
				},
			}
		}),
	})
)

// ParseCreateCategoryInput parses a map into CreateCategoryInput.
func ParseCreateCategoryInput(input map[string]interface{}) (*CreateCategoryInput, error) {
	result := &CreateCategoryInput{}
	if v, ok := input["text"]; ok && v != nil {
		if str, ok := v.(string); ok {
			result.Text = str
		}
	}
	if v, ok := input["status"]; ok && v != nil {
		// graphql-go decodes enum input to the typed Go value; fmt.Sprint
		// normalizes both the typed enum and a raw string to its string form.
		str := fmt.Sprint(v)
		val := category.Status(str)
		result.Status = &val
	}
	if v, ok := input["kind"]; ok && v != nil {
		// graphql-go decodes enum input to the typed Go value; fmt.Sprint
		// normalizes both the typed enum and a raw string to its string form.
		str := fmt.Sprint(v)
		val := category.Kind(str)
		result.Kind = &val
	}
	if v, ok := input["configType"]; ok && v != nil {
		// graphql-go decodes enum input to the typed Go value; fmt.Sprint
		// normalizes both the typed enum and a raw string to its string form.
		str := fmt.Sprint(v)
		val := category.ConfigType(str)
		result.ConfigType = &val
	}
	if v, ok := input["tags"]; ok && v != nil {
		switch sv := v.(type) {
		case []string:
			result.Tags = sv
		case []interface{}:
			out := make([]string, 0, len(sv))
			for _, item := range sv {
				if s, ok := item.(string); ok {
					out = append(out, s)
				} else {
					out = append(out, fmt.Sprint(item))
				}
			}
			result.Tags = out
		case string:
			var dec []string
			if err := json.Unmarshal([]byte(sv), &dec); err != nil {
				return nil, fmt.Errorf("field tags: invalid JSON list: %w", err)
			}
			result.Tags = dec
		default:
			return nil, fmt.Errorf("field tags: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["config"]; ok && v != nil {
		switch jv := v.(type) {
		case map[string]string:
			dec := jv
			result.Config = dec
		case string:
			var dec map[string]string
			if err := json.Unmarshal([]byte(jv), &dec); err != nil {
				return nil, fmt.Errorf("field config: invalid JSON: %w", err)
			}
			result.Config = dec
		default:
			raw, err := json.Marshal(jv)
			if err != nil {
				return nil, fmt.Errorf("field config: cannot marshal value: %w", err)
			}
			var dec map[string]string
			if err := json.Unmarshal(raw, &dec); err != nil {
				return nil, fmt.Errorf("field config: invalid JSON: %w", err)
			}
			result.Config = dec
		}
	}
	if v, ok := input["externalID"]; ok && v != nil {
		switch uv := v.(type) {
		case uuid.UUID:
			dv := uv
			result.ExternalID = &dv
		case string:
			uu, err := uuid.Parse(uv)
			if err != nil {
				return nil, fmt.Errorf("field external_id: invalid uuid %q: %w", uv, err)
			}
			dv := uu
			result.ExternalID = &dv
		case [16]byte:
			uu := uuid.UUID(uv)
			dv := uu
			result.ExternalID = &dv
		default:
			return nil, fmt.Errorf("field external_id: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["attributes"]; ok && v != nil {
		switch jv := v.(type) {
		case map[string]interface{}:
			dec := jv
			result.Attributes = dec
		case string:
			var dec map[string]interface{}
			if err := json.Unmarshal([]byte(jv), &dec); err != nil {
				return nil, fmt.Errorf("field attributes: invalid JSON: %w", err)
			}
			result.Attributes = dec
		default:
			raw, err := json.Marshal(jv)
			if err != nil {
				return nil, fmt.Errorf("field attributes: cannot marshal value: %w", err)
			}
			var dec map[string]interface{}
			if err := json.Unmarshal(raw, &dec); err != nil {
				return nil, fmt.Errorf("field attributes: invalid JSON: %w", err)
			}
			result.Attributes = dec
		}
	}
	if v, ok := input["payload"]; ok && v != nil {
		switch bv := v.(type) {
		case []byte:
			result.Payload = bv
		case string:
			if decoded, err := base64.StdEncoding.DecodeString(bv); err == nil {
				result.Payload = decoded
			} else {
				result.Payload = []byte(bv)
			}
		default:
			return nil, fmt.Errorf("field payload: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["todoIDs"]; ok && v != nil {
		if ids, ok := v.([]interface{}); ok {
			for _, idVal := range ids {
				id, err := strconv.Atoi(fmt.Sprint(idVal))
				if err != nil {
					return nil, fmt.Errorf("invalid todoID: %w", err)
				}
				result.TodoIDs = append(result.TodoIDs, id)
			}
		}
	}
	return result, nil
}

// ParseUpdateCategoryInput parses a map into UpdateCategoryInput.
func ParseUpdateCategoryInput(input map[string]interface{}) (*UpdateCategoryInput, error) {
	result := &UpdateCategoryInput{}
	if v, ok := input["text"]; ok && v != nil {
		if str, ok := v.(string); ok {
			s := str
			result.Text = &s
		}
	}
	if v, ok := input["status"]; ok && v != nil {
		// graphql-go decodes enum input to the typed Go value; fmt.Sprint
		// normalizes both the typed enum and a raw string to its string form.
		val := category.Status(fmt.Sprint(v))
		result.Status = &val
	}
	if v, ok := input["kind"]; ok && v != nil {
		// graphql-go decodes enum input to the typed Go value; fmt.Sprint
		// normalizes both the typed enum and a raw string to its string form.
		val := category.Kind(fmt.Sprint(v))
		result.Kind = &val
	}
	if v, ok := input["configType"]; ok && v != nil {
		// graphql-go decodes enum input to the typed Go value; fmt.Sprint
		// normalizes both the typed enum and a raw string to its string form.
		val := category.ConfigType(fmt.Sprint(v))
		result.ConfigType = &val
	}
	if v, ok := input["clearConfigType"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearConfigType = b
		}
	}
	if v, ok := input["tags"]; ok && v != nil {
		switch sv := v.(type) {
		case []string:
			result.Tags = sv
		case []interface{}:
			out := make([]string, 0, len(sv))
			for _, item := range sv {
				if s, ok := item.(string); ok {
					out = append(out, s)
				} else {
					out = append(out, fmt.Sprint(item))
				}
			}
			result.Tags = out
		case string:
			var dec []string
			if err := json.Unmarshal([]byte(sv), &dec); err != nil {
				return nil, fmt.Errorf("field tags: invalid JSON list: %w", err)
			}
			result.Tags = dec
		default:
			return nil, fmt.Errorf("field tags: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["clearTags"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearTags = b
		}
	}
	if v, ok := input["config"]; ok && v != nil {
		switch jv := v.(type) {
		case map[string]string:
			dec := jv
			result.Config = dec
		case string:
			var dec map[string]string
			if err := json.Unmarshal([]byte(jv), &dec); err != nil {
				return nil, fmt.Errorf("field config: invalid JSON: %w", err)
			}
			result.Config = dec
		default:
			raw, err := json.Marshal(jv)
			if err != nil {
				return nil, fmt.Errorf("field config: cannot marshal value: %w", err)
			}
			var dec map[string]string
			if err := json.Unmarshal(raw, &dec); err != nil {
				return nil, fmt.Errorf("field config: invalid JSON: %w", err)
			}
			result.Config = dec
		}
	}
	if v, ok := input["clearConfig"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearConfig = b
		}
	}
	if v, ok := input["externalID"]; ok && v != nil {
		switch uv := v.(type) {
		case uuid.UUID:
			dv := uv
			result.ExternalID = &dv
		case string:
			uu, err := uuid.Parse(uv)
			if err != nil {
				return nil, fmt.Errorf("field external_id: invalid uuid %q: %w", uv, err)
			}
			dv := uu
			result.ExternalID = &dv
		case [16]byte:
			uu := uuid.UUID(uv)
			dv := uu
			result.ExternalID = &dv
		default:
			return nil, fmt.Errorf("field external_id: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["clearExternalID"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearExternalID = b
		}
	}
	if v, ok := input["attributes"]; ok && v != nil {
		switch jv := v.(type) {
		case map[string]interface{}:
			dec := jv
			result.Attributes = dec
		case string:
			var dec map[string]interface{}
			if err := json.Unmarshal([]byte(jv), &dec); err != nil {
				return nil, fmt.Errorf("field attributes: invalid JSON: %w", err)
			}
			result.Attributes = dec
		default:
			raw, err := json.Marshal(jv)
			if err != nil {
				return nil, fmt.Errorf("field attributes: cannot marshal value: %w", err)
			}
			var dec map[string]interface{}
			if err := json.Unmarshal(raw, &dec); err != nil {
				return nil, fmt.Errorf("field attributes: invalid JSON: %w", err)
			}
			result.Attributes = dec
		}
	}
	if v, ok := input["clearAttributes"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearAttributes = b
		}
	}
	if v, ok := input["payload"]; ok && v != nil {
		switch bv := v.(type) {
		case []byte:
			result.Payload = bv
		case string:
			if decoded, err := base64.StdEncoding.DecodeString(bv); err == nil {
				result.Payload = decoded
			} else {
				result.Payload = []byte(bv)
			}
		default:
			return nil, fmt.Errorf("field payload: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["clearPayload"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearPayload = b
		}
	}
	if v, ok := input["addTodoIDs"]; ok && v != nil {
		if ids, ok := v.([]interface{}); ok {
			for _, idVal := range ids {
				id, err := strconv.Atoi(fmt.Sprint(idVal))
				if err != nil {
					return nil, fmt.Errorf("invalid addTodoID: %w", err)
				}
				result.AddTodoIDs = append(result.AddTodoIDs, id)
			}
		}
	}
	if v, ok := input["removeTodoIDs"]; ok && v != nil {
		if ids, ok := v.([]interface{}); ok {
			for _, idVal := range ids {
				id, err := strconv.Atoi(fmt.Sprint(idVal))
				if err != nil {
					return nil, fmt.Errorf("invalid removeTodoID: %w", err)
				}
				result.RemoveTodoIDs = append(result.RemoveTodoIDs, id)
			}
		}
	}
	if v, ok := input["clearTodos"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearTodos = b
		}
	}
	return result, nil
}

// ParseCreateFriendshipInput parses a map into CreateFriendshipInput.
func ParseCreateFriendshipInput(input map[string]interface{}) (*CreateFriendshipInput, error) {
	result := &CreateFriendshipInput{}
	if v, ok := input["todoID"]; ok && v != nil {
		id, err := strconv.Atoi(fmt.Sprint(v))
		if err != nil {
			return nil, fmt.Errorf("invalid todoID: %w", err)
		}
		result.TodoID = id
	}
	if v, ok := input["categoryID"]; ok && v != nil {
		id, err := strconv.Atoi(fmt.Sprint(v))
		if err != nil {
			return nil, fmt.Errorf("invalid categoryID: %w", err)
		}
		result.CategoryID = id
	}
	return result, nil
}

// ParseCreateTodoInput parses a map into CreateTodoInput.
func ParseCreateTodoInput(input map[string]interface{}) (*CreateTodoInput, error) {
	result := &CreateTodoInput{}
	if v, ok := input["status"]; ok && v != nil {
		// graphql-go decodes enum input to the typed Go value; fmt.Sprint
		// normalizes both the typed enum and a raw string to its string form.
		str := fmt.Sprint(v)
		result.Status = todo.Status(str)
	}
	if v, ok := input["priority"]; ok && v != nil {
		switch val := v.(type) {
		case int:
			result.Priority = &val
		case float64:
			i := int(val)
			result.Priority = &i
		}
	}
	if v, ok := input["text"]; ok && v != nil {
		if str, ok := v.(string); ok {
			result.Text = str
		}
	}
	if v, ok := input["score"]; ok && v != nil {
		switch nv := v.(type) {
		case int:
			cv := float64(nv)
			dv := cv
			result.Score = &dv
		case int64:
			cv := float64(nv)
			dv := cv
			result.Score = &dv
		case float64:
			cv := float64(nv)
			dv := cv
			result.Score = &dv
		case json.Number:
			fv, err := nv.Float64()
			if err != nil {
				return nil, fmt.Errorf("field score: invalid number %q: %w", nv.String(), err)
			}
			cv := float64(fv)
			dv := cv
			result.Score = &dv
		case string:
			fv, err := strconv.ParseFloat(nv, 64)
			if err != nil {
				return nil, fmt.Errorf("field score: invalid number %q: %w", nv, err)
			}
			cv := float64(fv)
			dv := cv
			result.Score = &dv
		default:
			return nil, fmt.Errorf("field score: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["dueDate"]; ok && v != nil {
		switch tv := v.(type) {
		case time.Time:
			dv := tv
			result.DueDate = &dv
		case string:
			tt, err := time.Parse(time.RFC3339, tv)
			if err != nil {
				return nil, fmt.Errorf("field due_date: invalid time %q: %w", tv, err)
			}
			dv := tt
			result.DueDate = &dv
		default:
			return nil, fmt.Errorf("field due_date: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["tags2"]; ok && v != nil {
		switch sv := v.(type) {
		case []string:
			result.Tags2 = sv
		case []interface{}:
			out := make([]string, 0, len(sv))
			for _, item := range sv {
				if s, ok := item.(string); ok {
					out = append(out, s)
				} else {
					out = append(out, fmt.Sprint(item))
				}
			}
			result.Tags2 = out
		case string:
			var dec []string
			if err := json.Unmarshal([]byte(sv), &dec); err != nil {
				return nil, fmt.Errorf("field tags2: invalid JSON list: %w", err)
			}
			result.Tags2 = dec
		default:
			return nil, fmt.Errorf("field tags2: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["metadata"]; ok && v != nil {
		switch jv := v.(type) {
		case map[string]interface{}:
			dec := jv
			result.Metadata = dec
		case string:
			var dec map[string]interface{}
			if err := json.Unmarshal([]byte(jv), &dec); err != nil {
				return nil, fmt.Errorf("field metadata: invalid JSON: %w", err)
			}
			result.Metadata = dec
		default:
			raw, err := json.Marshal(jv)
			if err != nil {
				return nil, fmt.Errorf("field metadata: cannot marshal value: %w", err)
			}
			var dec map[string]interface{}
			if err := json.Unmarshal(raw, &dec); err != nil {
				return nil, fmt.Errorf("field metadata: invalid JSON: %w", err)
			}
			result.Metadata = dec
		}
	}
	if v, ok := input["externalID"]; ok && v != nil {
		switch uv := v.(type) {
		case uuid.UUID:
			dv := uv
			result.ExternalID = &dv
		case string:
			uu, err := uuid.Parse(uv)
			if err != nil {
				return nil, fmt.Errorf("field external_id: invalid uuid %q: %w", uv, err)
			}
			dv := uu
			result.ExternalID = &dv
		case [16]byte:
			uu := uuid.UUID(uv)
			dv := uu
			result.ExternalID = &dv
		default:
			return nil, fmt.Errorf("field external_id: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["duration"]; ok && v != nil {
		switch nv := v.(type) {
		case int:
			cv := int64(nv)
			dv := cv
			result.Duration = &dv
		case int64:
			cv := int64(nv)
			dv := cv
			result.Duration = &dv
		case float64:
			cv := int64(nv)
			dv := cv
			result.Duration = &dv
		case json.Number:
			fv, err := nv.Float64()
			if err != nil {
				return nil, fmt.Errorf("field duration: invalid number %q: %w", nv.String(), err)
			}
			cv := int64(fv)
			dv := cv
			result.Duration = &dv
		case string:
			fv, err := strconv.ParseFloat(nv, 64)
			if err != nil {
				return nil, fmt.Errorf("field duration: invalid number %q: %w", nv, err)
			}
			cv := int64(fv)
			dv := cv
			result.Duration = &dv
		default:
			return nil, fmt.Errorf("field duration: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["parentID"]; ok && v != nil {
		id, err := strconv.Atoi(fmt.Sprint(v))
		if err != nil {
			return nil, fmt.Errorf("invalid parentID: %w", err)
		}
		result.ParentID = &id
	}
	if v, ok := input["childIDs"]; ok && v != nil {
		if ids, ok := v.([]interface{}); ok {
			for _, idVal := range ids {
				id, err := strconv.Atoi(fmt.Sprint(idVal))
				if err != nil {
					return nil, fmt.Errorf("invalid childID: %w", err)
				}
				result.ChildIDs = append(result.ChildIDs, id)
			}
		}
	}
	if v, ok := input["categoryID"]; ok && v != nil {
		id, err := strconv.Atoi(fmt.Sprint(v))
		if err != nil {
			return nil, fmt.Errorf("invalid categoryID: %w", err)
		}
		result.CategoryID = &id
	}
	return result, nil
}

// ParseUpdateTodoInput parses a map into UpdateTodoInput.
func ParseUpdateTodoInput(input map[string]interface{}) (*UpdateTodoInput, error) {
	result := &UpdateTodoInput{}
	if v, ok := input["status"]; ok && v != nil {
		// graphql-go decodes enum input to the typed Go value; fmt.Sprint
		// normalizes both the typed enum and a raw string to its string form.
		val := todo.Status(fmt.Sprint(v))
		result.Status = &val
	}
	if v, ok := input["priority"]; ok && v != nil {
		switch val := v.(type) {
		case int:
			i := val
			result.Priority = &i
		case float64:
			i := int(val)
			result.Priority = &i
		}
	}
	if v, ok := input["text"]; ok && v != nil {
		if str, ok := v.(string); ok {
			s := str
			result.Text = &s
		}
	}
	if v, ok := input["score"]; ok && v != nil {
		switch nv := v.(type) {
		case int:
			cv := float64(nv)
			dv := cv
			result.Score = &dv
		case int64:
			cv := float64(nv)
			dv := cv
			result.Score = &dv
		case float64:
			cv := float64(nv)
			dv := cv
			result.Score = &dv
		case json.Number:
			fv, err := nv.Float64()
			if err != nil {
				return nil, fmt.Errorf("field score: invalid number %q: %w", nv.String(), err)
			}
			cv := float64(fv)
			dv := cv
			result.Score = &dv
		case string:
			fv, err := strconv.ParseFloat(nv, 64)
			if err != nil {
				return nil, fmt.Errorf("field score: invalid number %q: %w", nv, err)
			}
			cv := float64(fv)
			dv := cv
			result.Score = &dv
		default:
			return nil, fmt.Errorf("field score: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["clearScore"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearScore = b
		}
	}
	if v, ok := input["dueDate"]; ok && v != nil {
		switch tv := v.(type) {
		case time.Time:
			dv := tv
			result.DueDate = &dv
		case string:
			tt, err := time.Parse(time.RFC3339, tv)
			if err != nil {
				return nil, fmt.Errorf("field due_date: invalid time %q: %w", tv, err)
			}
			dv := tt
			result.DueDate = &dv
		default:
			return nil, fmt.Errorf("field due_date: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["clearDueDate"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearDueDate = b
		}
	}
	if v, ok := input["tags2"]; ok && v != nil {
		switch sv := v.(type) {
		case []string:
			result.Tags2 = sv
		case []interface{}:
			out := make([]string, 0, len(sv))
			for _, item := range sv {
				if s, ok := item.(string); ok {
					out = append(out, s)
				} else {
					out = append(out, fmt.Sprint(item))
				}
			}
			result.Tags2 = out
		case string:
			var dec []string
			if err := json.Unmarshal([]byte(sv), &dec); err != nil {
				return nil, fmt.Errorf("field tags2: invalid JSON list: %w", err)
			}
			result.Tags2 = dec
		default:
			return nil, fmt.Errorf("field tags2: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["clearTags2"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearTags2 = b
		}
	}
	if v, ok := input["metadata"]; ok && v != nil {
		switch jv := v.(type) {
		case map[string]interface{}:
			dec := jv
			result.Metadata = dec
		case string:
			var dec map[string]interface{}
			if err := json.Unmarshal([]byte(jv), &dec); err != nil {
				return nil, fmt.Errorf("field metadata: invalid JSON: %w", err)
			}
			result.Metadata = dec
		default:
			raw, err := json.Marshal(jv)
			if err != nil {
				return nil, fmt.Errorf("field metadata: cannot marshal value: %w", err)
			}
			var dec map[string]interface{}
			if err := json.Unmarshal(raw, &dec); err != nil {
				return nil, fmt.Errorf("field metadata: invalid JSON: %w", err)
			}
			result.Metadata = dec
		}
	}
	if v, ok := input["clearMetadata"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearMetadata = b
		}
	}
	if v, ok := input["externalID"]; ok && v != nil {
		switch uv := v.(type) {
		case uuid.UUID:
			dv := uv
			result.ExternalID = &dv
		case string:
			uu, err := uuid.Parse(uv)
			if err != nil {
				return nil, fmt.Errorf("field external_id: invalid uuid %q: %w", uv, err)
			}
			dv := uu
			result.ExternalID = &dv
		case [16]byte:
			uu := uuid.UUID(uv)
			dv := uu
			result.ExternalID = &dv
		default:
			return nil, fmt.Errorf("field external_id: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["clearExternalID"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearExternalID = b
		}
	}
	if v, ok := input["duration"]; ok && v != nil {
		switch nv := v.(type) {
		case int:
			cv := int64(nv)
			dv := cv
			result.Duration = &dv
		case int64:
			cv := int64(nv)
			dv := cv
			result.Duration = &dv
		case float64:
			cv := int64(nv)
			dv := cv
			result.Duration = &dv
		case json.Number:
			fv, err := nv.Float64()
			if err != nil {
				return nil, fmt.Errorf("field duration: invalid number %q: %w", nv.String(), err)
			}
			cv := int64(fv)
			dv := cv
			result.Duration = &dv
		case string:
			fv, err := strconv.ParseFloat(nv, 64)
			if err != nil {
				return nil, fmt.Errorf("field duration: invalid number %q: %w", nv, err)
			}
			cv := int64(fv)
			dv := cv
			result.Duration = &dv
		default:
			return nil, fmt.Errorf("field duration: invalid value %v (%T)", v, v)
		}
	}
	if v, ok := input["clearDuration"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearDuration = b
		}
	}
	if v, ok := input["parentID"]; ok && v != nil {
		id, err := strconv.Atoi(fmt.Sprint(v))
		if err != nil {
			return nil, fmt.Errorf("invalid parentID: %w", err)
		}
		result.ParentID = &id
	}
	if v, ok := input["clearParent"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearParent = b
		}
	}
	if v, ok := input["addChildIDs"]; ok && v != nil {
		if ids, ok := v.([]interface{}); ok {
			for _, idVal := range ids {
				id, err := strconv.Atoi(fmt.Sprint(idVal))
				if err != nil {
					return nil, fmt.Errorf("invalid addChildID: %w", err)
				}
				result.AddChildIDs = append(result.AddChildIDs, id)
			}
		}
	}
	if v, ok := input["removeChildIDs"]; ok && v != nil {
		if ids, ok := v.([]interface{}); ok {
			for _, idVal := range ids {
				id, err := strconv.Atoi(fmt.Sprint(idVal))
				if err != nil {
					return nil, fmt.Errorf("invalid removeChildID: %w", err)
				}
				result.RemoveChildIDs = append(result.RemoveChildIDs, id)
			}
		}
	}
	if v, ok := input["clearChildren"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearChildren = b
		}
	}
	if v, ok := input["categoryID"]; ok && v != nil {
		id, err := strconv.Atoi(fmt.Sprint(v))
		if err != nil {
			return nil, fmt.Errorf("invalid categoryID: %w", err)
		}
		result.CategoryID = &id
	}
	if v, ok := input["clearCategory"]; ok {
		if b, ok := v.(bool); ok {
			result.ClearCategory = b
		}
	}
	return result, nil
}
