// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package gqlgo

import (
	"errors"
	"fmt"
	"time"

	"entgo.io/contrib/entgqlgo/internal/todo/ent"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/billproduct"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/predicate"
	"entgo.io/contrib/entgqlgo/internal/todo/ent/todo"

	"github.com/graphql-go/graphql"
)

// WhereInput GraphQL InputObject types for filtering
var (

	// BillProductWhereInputType is the GraphQL InputObject for filtering BillProduct queries.
	BillProductWhereInputType *graphql.InputObject

	// CategoryWhereInputType is the GraphQL InputObject for filtering Category queries.
	CategoryWhereInputType *graphql.InputObject

	// TodoWhereInputType is the GraphQL InputObject for filtering Todo queries.
	TodoWhereInputType *graphql.InputObject
)

func init() {

	BillProductWhereInputType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name:        "BillProductWhereInput",
		Description: "BillProductWhereInput is used for filtering BillProduct objects.",
		Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"not": &graphql.InputObjectFieldConfig{
					Type:        BillProductWhereInputType,
					Description: "Logical NOT of the condition.",
				},
				"and": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(BillProductWhereInputType)),
					Description: "Logical AND of conditions.",
				},
				"or": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(BillProductWhereInputType)),
					Description: "Logical OR of conditions.",
				},
				"id": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.ID)),
				},
				"idNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.ID)),
				},
				"idGT": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idLT": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"name": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"nameNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"nameGT": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameLT": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameContains": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameHasPrefix": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameHasSuffix": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameEqualFold": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"nameContainsFold": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"sku": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"skuNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"skuGT": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuLT": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuContains": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuHasPrefix": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuHasSuffix": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuEqualFold": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"skuContainsFold": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"quantity": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"quantityNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"quantityIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.Int)),
				},
				"quantityNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.Int)),
				},
				"quantityGT": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"quantityGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"quantityLT": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"quantityLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
			}
		}),
	})

	CategoryWhereInputType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name:        "CategoryWhereInput",
		Description: "CategoryWhereInput is used for filtering Category objects.",
		Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"not": &graphql.InputObjectFieldConfig{
					Type:        CategoryWhereInputType,
					Description: "Logical NOT of the condition.",
				},
				"and": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(CategoryWhereInputType)),
					Description: "Logical AND of conditions.",
				},
				"or": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(CategoryWhereInputType)),
					Description: "Logical OR of conditions.",
				},
				"id": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.ID)),
				},
				"idNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.ID)),
				},
				"idGT": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idLT": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"text": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"textNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"textGT": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textLT": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textContains": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textHasPrefix": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textHasSuffix": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textEqualFold": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textContainsFold": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"status": &graphql.InputObjectFieldConfig{
					Type: CategoryStatusEnum,
				},
				"statusNEQ": &graphql.InputObjectFieldConfig{
					Type: CategoryStatusEnum,
				},
				"statusIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(CategoryStatusEnum)),
				},
				"statusNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(CategoryStatusEnum)),
				},
				"hasTodos": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Check if todos edge exists.",
				},
				"hasTodosWith": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(TodoWhereInputType)),
					Description: "Filter by todos edge with conditions.",
				},
			}
		}),
	})

	TodoWhereInputType = graphql.NewInputObject(graphql.InputObjectConfig{
		Name:        "TodoWhereInput",
		Description: "TodoWhereInput is used for filtering Todo objects.",
		Fields: graphql.InputObjectConfigFieldMapThunk(func() graphql.InputObjectConfigFieldMap {
			return graphql.InputObjectConfigFieldMap{
				"not": &graphql.InputObjectFieldConfig{
					Type:        TodoWhereInputType,
					Description: "Logical NOT of the condition.",
				},
				"and": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(TodoWhereInputType)),
					Description: "Logical AND of conditions.",
				},
				"or": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(TodoWhereInputType)),
					Description: "Logical OR of conditions.",
				},
				"id": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.ID)),
				},
				"idNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.ID)),
				},
				"idGT": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idLT": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"idLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.ID,
				},
				"createdAt": &graphql.InputObjectFieldConfig{
					Type: TimeScalar,
				},
				"createdAtNEQ": &graphql.InputObjectFieldConfig{
					Type: TimeScalar,
				},
				"createdAtIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(TimeScalar)),
				},
				"createdAtNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(TimeScalar)),
				},
				"createdAtGT": &graphql.InputObjectFieldConfig{
					Type: TimeScalar,
				},
				"createdAtGTE": &graphql.InputObjectFieldConfig{
					Type: TimeScalar,
				},
				"createdAtLT": &graphql.InputObjectFieldConfig{
					Type: TimeScalar,
				},
				"createdAtLTE": &graphql.InputObjectFieldConfig{
					Type: TimeScalar,
				},
				"status": &graphql.InputObjectFieldConfig{
					Type: TodoStatusEnum,
				},
				"statusNEQ": &graphql.InputObjectFieldConfig{
					Type: TodoStatusEnum,
				},
				"statusIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(TodoStatusEnum)),
				},
				"statusNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(TodoStatusEnum)),
				},
				"priority": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"priorityNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"priorityIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.Int)),
				},
				"priorityNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.Int)),
				},
				"priorityGT": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"priorityGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"priorityLT": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"priorityLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.Int,
				},
				"text": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textNEQ": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"textNotIn": &graphql.InputObjectFieldConfig{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"textGT": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textGTE": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textLT": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textLTE": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textContains": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textHasPrefix": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textHasSuffix": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textEqualFold": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"textContainsFold": &graphql.InputObjectFieldConfig{
					Type: graphql.String,
				},
				"hasParent": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Check if parent edge exists.",
				},
				"hasParentWith": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(TodoWhereInputType)),
					Description: "Filter by parent edge with conditions.",
				},
				"hasChildren": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Check if children edge exists.",
				},
				"hasChildrenWith": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(TodoWhereInputType)),
					Description: "Filter by children edge with conditions.",
				},
				"hasCategory": &graphql.InputObjectFieldConfig{
					Type:        graphql.Boolean,
					Description: "Check if category edge exists.",
				},
				"hasCategoryWith": &graphql.InputObjectFieldConfig{
					Type:        graphql.NewList(graphql.NewNonNull(CategoryWhereInputType)),
					Description: "Filter by category edge with conditions.",
				},
			}
		}),
	})
}

// BillProductWhereInput represents a where input for filtering BillProduct queries.
type BillProductWhereInput struct {
	Predicates []predicate.BillProduct  `json:"-"`
	Not        *BillProductWhereInput   `json:"not,omitempty"`
	Or         []*BillProductWhereInput `json:"or,omitempty"`
	And        []*BillProductWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *int  `json:"id,omitempty"`
	IDNEQ   *int  `json:"idNEQ,omitempty"`
	IDIn    []int `json:"idIn,omitempty"`
	IDNotIn []int `json:"idNotIn,omitempty"`
	IDGT    *int  `json:"idGT,omitempty"`
	IDGTE   *int  `json:"idGTE,omitempty"`
	IDLT    *int  `json:"idLT,omitempty"`
	IDLTE   *int  `json:"idLTE,omitempty"`

	// "name" field predicates.
	Name             *string  `json:"name,omitempty"`
	NameNEQ          *string  `json:"nameNEQ,omitempty"`
	NameIn           []string `json:"nameIn,omitempty"`
	NameNotIn        []string `json:"nameNotIn,omitempty"`
	NameGT           *string  `json:"nameGT,omitempty"`
	NameGTE          *string  `json:"nameGTE,omitempty"`
	NameLT           *string  `json:"nameLT,omitempty"`
	NameLTE          *string  `json:"nameLTE,omitempty"`
	NameContains     *string  `json:"nameContains,omitempty"`
	NameHasPrefix    *string  `json:"nameHasPrefix,omitempty"`
	NameHasSuffix    *string  `json:"nameHasSuffix,omitempty"`
	NameEqualFold    *string  `json:"nameEqualFold,omitempty"`
	NameContainsFold *string  `json:"nameContainsFold,omitempty"`

	// "sku" field predicates.
	Sku             *string  `json:"sku,omitempty"`
	SkuNEQ          *string  `json:"skuNEQ,omitempty"`
	SkuIn           []string `json:"skuIn,omitempty"`
	SkuNotIn        []string `json:"skuNotIn,omitempty"`
	SkuGT           *string  `json:"skuGT,omitempty"`
	SkuGTE          *string  `json:"skuGTE,omitempty"`
	SkuLT           *string  `json:"skuLT,omitempty"`
	SkuLTE          *string  `json:"skuLTE,omitempty"`
	SkuContains     *string  `json:"skuContains,omitempty"`
	SkuHasPrefix    *string  `json:"skuHasPrefix,omitempty"`
	SkuHasSuffix    *string  `json:"skuHasSuffix,omitempty"`
	SkuEqualFold    *string  `json:"skuEqualFold,omitempty"`
	SkuContainsFold *string  `json:"skuContainsFold,omitempty"`

	// "quantity" field predicates.
	Quantity      *int  `json:"quantity,omitempty"`
	QuantityNEQ   *int  `json:"quantityNEQ,omitempty"`
	QuantityIn    []int `json:"quantityIn,omitempty"`
	QuantityNotIn []int `json:"quantityNotIn,omitempty"`
	QuantityGT    *int  `json:"quantityGT,omitempty"`
	QuantityGTE   *int  `json:"quantityGTE,omitempty"`
	QuantityLT    *int  `json:"quantityLT,omitempty"`
	QuantityLTE   *int  `json:"quantityLTE,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *BillProductWhereInput) AddPredicates(predicates ...predicate.BillProduct) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the BillProductWhereInput filter on the BillProductQuery builder.
func (i *BillProductWhereInput) Filter(q *ent.BillProductQuery) (*ent.BillProductQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyBillProductWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyBillProductWhereInput is returned in case the BillProductWhereInput is empty.
var ErrEmptyBillProductWhereInput = errors.New("gqlgo: empty predicate BillProductWhereInput")

// P returns a predicate for filtering billproducts.
// An error is returned if the input is empty or invalid.
func (i *BillProductWhereInput) P() (predicate.BillProduct, error) {
	var predicates []predicate.BillProduct
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, billproduct.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.BillProduct, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, billproduct.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.BillProduct, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, billproduct.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, billproduct.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, billproduct.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, billproduct.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, billproduct.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, billproduct.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, billproduct.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, billproduct.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, billproduct.IDLTE(*i.IDLTE))
	}
	if i.Name != nil {
		predicates = append(predicates, billproduct.NameEQ(*i.Name))
	}
	if i.NameNEQ != nil {
		predicates = append(predicates, billproduct.NameNEQ(*i.NameNEQ))
	}
	if len(i.NameIn) > 0 {
		predicates = append(predicates, billproduct.NameIn(i.NameIn...))
	}
	if len(i.NameNotIn) > 0 {
		predicates = append(predicates, billproduct.NameNotIn(i.NameNotIn...))
	}
	if i.NameGT != nil {
		predicates = append(predicates, billproduct.NameGT(*i.NameGT))
	}
	if i.NameGTE != nil {
		predicates = append(predicates, billproduct.NameGTE(*i.NameGTE))
	}
	if i.NameLT != nil {
		predicates = append(predicates, billproduct.NameLT(*i.NameLT))
	}
	if i.NameLTE != nil {
		predicates = append(predicates, billproduct.NameLTE(*i.NameLTE))
	}
	if i.NameContains != nil {
		predicates = append(predicates, billproduct.NameContains(*i.NameContains))
	}
	if i.NameHasPrefix != nil {
		predicates = append(predicates, billproduct.NameHasPrefix(*i.NameHasPrefix))
	}
	if i.NameHasSuffix != nil {
		predicates = append(predicates, billproduct.NameHasSuffix(*i.NameHasSuffix))
	}
	if i.NameEqualFold != nil {
		predicates = append(predicates, billproduct.NameEqualFold(*i.NameEqualFold))
	}
	if i.NameContainsFold != nil {
		predicates = append(predicates, billproduct.NameContainsFold(*i.NameContainsFold))
	}
	if i.Sku != nil {
		predicates = append(predicates, billproduct.SkuEQ(*i.Sku))
	}
	if i.SkuNEQ != nil {
		predicates = append(predicates, billproduct.SkuNEQ(*i.SkuNEQ))
	}
	if len(i.SkuIn) > 0 {
		predicates = append(predicates, billproduct.SkuIn(i.SkuIn...))
	}
	if len(i.SkuNotIn) > 0 {
		predicates = append(predicates, billproduct.SkuNotIn(i.SkuNotIn...))
	}
	if i.SkuGT != nil {
		predicates = append(predicates, billproduct.SkuGT(*i.SkuGT))
	}
	if i.SkuGTE != nil {
		predicates = append(predicates, billproduct.SkuGTE(*i.SkuGTE))
	}
	if i.SkuLT != nil {
		predicates = append(predicates, billproduct.SkuLT(*i.SkuLT))
	}
	if i.SkuLTE != nil {
		predicates = append(predicates, billproduct.SkuLTE(*i.SkuLTE))
	}
	if i.SkuContains != nil {
		predicates = append(predicates, billproduct.SkuContains(*i.SkuContains))
	}
	if i.SkuHasPrefix != nil {
		predicates = append(predicates, billproduct.SkuHasPrefix(*i.SkuHasPrefix))
	}
	if i.SkuHasSuffix != nil {
		predicates = append(predicates, billproduct.SkuHasSuffix(*i.SkuHasSuffix))
	}
	if i.SkuEqualFold != nil {
		predicates = append(predicates, billproduct.SkuEqualFold(*i.SkuEqualFold))
	}
	if i.SkuContainsFold != nil {
		predicates = append(predicates, billproduct.SkuContainsFold(*i.SkuContainsFold))
	}
	if i.Quantity != nil {
		predicates = append(predicates, billproduct.QuantityEQ(*i.Quantity))
	}
	if i.QuantityNEQ != nil {
		predicates = append(predicates, billproduct.QuantityNEQ(*i.QuantityNEQ))
	}
	if len(i.QuantityIn) > 0 {
		predicates = append(predicates, billproduct.QuantityIn(i.QuantityIn...))
	}
	if len(i.QuantityNotIn) > 0 {
		predicates = append(predicates, billproduct.QuantityNotIn(i.QuantityNotIn...))
	}
	if i.QuantityGT != nil {
		predicates = append(predicates, billproduct.QuantityGT(*i.QuantityGT))
	}
	if i.QuantityGTE != nil {
		predicates = append(predicates, billproduct.QuantityGTE(*i.QuantityGTE))
	}
	if i.QuantityLT != nil {
		predicates = append(predicates, billproduct.QuantityLT(*i.QuantityLT))
	}
	if i.QuantityLTE != nil {
		predicates = append(predicates, billproduct.QuantityLTE(*i.QuantityLTE))
	}

	switch len(predicates) {
	case 1:
		return predicates[0], nil
	default:
		return billproduct.And(predicates...), nil
	}
}

// ParseBillProductWhereInput converts a map[string]interface{} from GraphQL into a typed BillProductWhereInput.
func ParseBillProductWhereInput(m map[string]interface{}) (*BillProductWhereInput, error) {
	if m == nil {
		return nil, nil
	}
	input := &BillProductWhereInput{}

	// Parse not
	if v, ok := m["not"]; ok && v != nil {
		if notMap, ok := v.(map[string]interface{}); ok {
			notInput, err := ParseBillProductWhereInput(notMap)
			if err != nil {
				return nil, fmt.Errorf("parsing 'not': %w", err)
			}
			input.Not = notInput
		}
	}

	// Parse and
	if v, ok := m["and"]; ok && v != nil {
		if andSlice, ok := v.([]interface{}); ok {
			for i, item := range andSlice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					andInput, err := ParseBillProductWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'and[%d]': %w", i, err)
					}
					input.And = append(input.And, andInput)
				}
			}
		}
	}

	// Parse or
	if v, ok := m["or"]; ok && v != nil {
		if orSlice, ok := v.([]interface{}); ok {
			for i, item := range orSlice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					orInput, err := ParseBillProductWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'or[%d]': %w", i, err)
					}
					input.Or = append(input.Or, orInput)
				}
			}
		}
	}
	// Parse id
	if v, ok := m["id"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.ID = &val
		}
	}
	// Parse idNEQ
	if v, ok := m["idNEQ"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDNEQ = &val
		}
	}
	// Parse idIn
	if v, ok := m["idIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.IDIn = append(input.IDIn, int(i))
				}
			}
		}
	}
	// Parse idNotIn
	if v, ok := m["idNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.IDNotIn = append(input.IDNotIn, int(i))
				}
			}
		}
	}
	// Parse idGT
	if v, ok := m["idGT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDGT = &val
		}
	}
	// Parse idGTE
	if v, ok := m["idGTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDGTE = &val
		}
	}
	// Parse idLT
	if v, ok := m["idLT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDLT = &val
		}
	}
	// Parse idLTE
	if v, ok := m["idLTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDLTE = &val
		}
	}
	// Parse name
	if v, ok := m["name"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.Name = &s
		}
	}
	// Parse nameNEQ
	if v, ok := m["nameNEQ"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameNEQ = &s
		}
	}
	// Parse nameIn
	if v, ok := m["nameIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.NameIn = append(input.NameIn, s)
				}
			}
		}
	}
	// Parse nameNotIn
	if v, ok := m["nameNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.NameNotIn = append(input.NameNotIn, s)
				}
			}
		}
	}
	// Parse nameGT
	if v, ok := m["nameGT"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameGT = &s
		}
	}
	// Parse nameGTE
	if v, ok := m["nameGTE"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameGTE = &s
		}
	}
	// Parse nameLT
	if v, ok := m["nameLT"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameLT = &s
		}
	}
	// Parse nameLTE
	if v, ok := m["nameLTE"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameLTE = &s
		}
	}
	// Parse nameContains
	if v, ok := m["nameContains"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameContains = &s
		}
	}
	// Parse nameHasPrefix
	if v, ok := m["nameHasPrefix"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameHasPrefix = &s
		}
	}
	// Parse nameHasSuffix
	if v, ok := m["nameHasSuffix"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameHasSuffix = &s
		}
	}
	// Parse nameEqualFold
	if v, ok := m["nameEqualFold"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameEqualFold = &s
		}
	}
	// Parse nameContainsFold
	if v, ok := m["nameContainsFold"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.NameContainsFold = &s
		}
	}
	// Parse sku
	if v, ok := m["sku"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.Sku = &s
		}
	}
	// Parse skuNEQ
	if v, ok := m["skuNEQ"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuNEQ = &s
		}
	}
	// Parse skuIn
	if v, ok := m["skuIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.SkuIn = append(input.SkuIn, s)
				}
			}
		}
	}
	// Parse skuNotIn
	if v, ok := m["skuNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.SkuNotIn = append(input.SkuNotIn, s)
				}
			}
		}
	}
	// Parse skuGT
	if v, ok := m["skuGT"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuGT = &s
		}
	}
	// Parse skuGTE
	if v, ok := m["skuGTE"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuGTE = &s
		}
	}
	// Parse skuLT
	if v, ok := m["skuLT"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuLT = &s
		}
	}
	// Parse skuLTE
	if v, ok := m["skuLTE"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuLTE = &s
		}
	}
	// Parse skuContains
	if v, ok := m["skuContains"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuContains = &s
		}
	}
	// Parse skuHasPrefix
	if v, ok := m["skuHasPrefix"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuHasPrefix = &s
		}
	}
	// Parse skuHasSuffix
	if v, ok := m["skuHasSuffix"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuHasSuffix = &s
		}
	}
	// Parse skuEqualFold
	if v, ok := m["skuEqualFold"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuEqualFold = &s
		}
	}
	// Parse skuContainsFold
	if v, ok := m["skuContainsFold"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.SkuContainsFold = &s
		}
	}
	// Parse quantity
	if v, ok := m["quantity"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.Quantity = &val
		}
	}
	// Parse quantityNEQ
	if v, ok := m["quantityNEQ"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.QuantityNEQ = &val
		}
	}
	// Parse quantityIn
	if v, ok := m["quantityIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.QuantityIn = append(input.QuantityIn, int(i))
				}
			}
		}
	}
	// Parse quantityNotIn
	if v, ok := m["quantityNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.QuantityNotIn = append(input.QuantityNotIn, int(i))
				}
			}
		}
	}
	// Parse quantityGT
	if v, ok := m["quantityGT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.QuantityGT = &val
		}
	}
	// Parse quantityGTE
	if v, ok := m["quantityGTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.QuantityGTE = &val
		}
	}
	// Parse quantityLT
	if v, ok := m["quantityLT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.QuantityLT = &val
		}
	}
	// Parse quantityLTE
	if v, ok := m["quantityLTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.QuantityLTE = &val
		}
	}

	return input, nil
}

// CategoryWhereInput represents a where input for filtering Category queries.
type CategoryWhereInput struct {
	Predicates []predicate.Category  `json:"-"`
	Not        *CategoryWhereInput   `json:"not,omitempty"`
	Or         []*CategoryWhereInput `json:"or,omitempty"`
	And        []*CategoryWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *int  `json:"id,omitempty"`
	IDNEQ   *int  `json:"idNEQ,omitempty"`
	IDIn    []int `json:"idIn,omitempty"`
	IDNotIn []int `json:"idNotIn,omitempty"`
	IDGT    *int  `json:"idGT,omitempty"`
	IDGTE   *int  `json:"idGTE,omitempty"`
	IDLT    *int  `json:"idLT,omitempty"`
	IDLTE   *int  `json:"idLTE,omitempty"`

	// "text" field predicates.
	Text             *string  `json:"text,omitempty"`
	TextNEQ          *string  `json:"textNEQ,omitempty"`
	TextIn           []string `json:"textIn,omitempty"`
	TextNotIn        []string `json:"textNotIn,omitempty"`
	TextGT           *string  `json:"textGT,omitempty"`
	TextGTE          *string  `json:"textGTE,omitempty"`
	TextLT           *string  `json:"textLT,omitempty"`
	TextLTE          *string  `json:"textLTE,omitempty"`
	TextContains     *string  `json:"textContains,omitempty"`
	TextHasPrefix    *string  `json:"textHasPrefix,omitempty"`
	TextHasSuffix    *string  `json:"textHasSuffix,omitempty"`
	TextEqualFold    *string  `json:"textEqualFold,omitempty"`
	TextContainsFold *string  `json:"textContainsFold,omitempty"`

	// "status" field predicates.
	Status      *category.Status  `json:"status,omitempty"`
	StatusNEQ   *category.Status  `json:"statusNEQ,omitempty"`
	StatusIn    []category.Status `json:"statusIn,omitempty"`
	StatusNotIn []category.Status `json:"statusNotIn,omitempty"`

	// "todos" edge predicates.
	HasTodos     *bool             `json:"hasTodos,omitempty"`
	HasTodosWith []*TodoWhereInput `json:"hasTodosWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *CategoryWhereInput) AddPredicates(predicates ...predicate.Category) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the CategoryWhereInput filter on the CategoryQuery builder.
func (i *CategoryWhereInput) Filter(q *ent.CategoryQuery) (*ent.CategoryQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyCategoryWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyCategoryWhereInput is returned in case the CategoryWhereInput is empty.
var ErrEmptyCategoryWhereInput = errors.New("gqlgo: empty predicate CategoryWhereInput")

// P returns a predicate for filtering categories.
// An error is returned if the input is empty or invalid.
func (i *CategoryWhereInput) P() (predicate.Category, error) {
	var predicates []predicate.Category
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, category.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Category, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, category.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Category, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, category.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, category.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, category.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, category.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, category.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, category.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, category.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, category.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, category.IDLTE(*i.IDLTE))
	}
	if i.Text != nil {
		predicates = append(predicates, category.TextEQ(*i.Text))
	}
	if i.TextNEQ != nil {
		predicates = append(predicates, category.TextNEQ(*i.TextNEQ))
	}
	if len(i.TextIn) > 0 {
		predicates = append(predicates, category.TextIn(i.TextIn...))
	}
	if len(i.TextNotIn) > 0 {
		predicates = append(predicates, category.TextNotIn(i.TextNotIn...))
	}
	if i.TextGT != nil {
		predicates = append(predicates, category.TextGT(*i.TextGT))
	}
	if i.TextGTE != nil {
		predicates = append(predicates, category.TextGTE(*i.TextGTE))
	}
	if i.TextLT != nil {
		predicates = append(predicates, category.TextLT(*i.TextLT))
	}
	if i.TextLTE != nil {
		predicates = append(predicates, category.TextLTE(*i.TextLTE))
	}
	if i.TextContains != nil {
		predicates = append(predicates, category.TextContains(*i.TextContains))
	}
	if i.TextHasPrefix != nil {
		predicates = append(predicates, category.TextHasPrefix(*i.TextHasPrefix))
	}
	if i.TextHasSuffix != nil {
		predicates = append(predicates, category.TextHasSuffix(*i.TextHasSuffix))
	}
	if i.TextEqualFold != nil {
		predicates = append(predicates, category.TextEqualFold(*i.TextEqualFold))
	}
	if i.TextContainsFold != nil {
		predicates = append(predicates, category.TextContainsFold(*i.TextContainsFold))
	}
	if i.Status != nil {
		predicates = append(predicates, category.StatusEQ(*i.Status))
	}
	if i.StatusNEQ != nil {
		predicates = append(predicates, category.StatusNEQ(*i.StatusNEQ))
	}
	if len(i.StatusIn) > 0 {
		predicates = append(predicates, category.StatusIn(i.StatusIn...))
	}
	if len(i.StatusNotIn) > 0 {
		predicates = append(predicates, category.StatusNotIn(i.StatusNotIn...))
	}

	if i.HasTodos != nil {
		p := category.HasTodos()
		if !*i.HasTodos {
			p = category.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasTodosWith) > 0 {
		with := make([]predicate.Todo, 0, len(i.HasTodosWith))
		for _, w := range i.HasTodosWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasTodosWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, category.HasTodosWith(with...))
	}
	switch len(predicates) {
	case 1:
		return predicates[0], nil
	default:
		return category.And(predicates...), nil
	}
}

// ParseCategoryWhereInput converts a map[string]interface{} from GraphQL into a typed CategoryWhereInput.
func ParseCategoryWhereInput(m map[string]interface{}) (*CategoryWhereInput, error) {
	if m == nil {
		return nil, nil
	}
	input := &CategoryWhereInput{}

	// Parse not
	if v, ok := m["not"]; ok && v != nil {
		if notMap, ok := v.(map[string]interface{}); ok {
			notInput, err := ParseCategoryWhereInput(notMap)
			if err != nil {
				return nil, fmt.Errorf("parsing 'not': %w", err)
			}
			input.Not = notInput
		}
	}

	// Parse and
	if v, ok := m["and"]; ok && v != nil {
		if andSlice, ok := v.([]interface{}); ok {
			for i, item := range andSlice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					andInput, err := ParseCategoryWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'and[%d]': %w", i, err)
					}
					input.And = append(input.And, andInput)
				}
			}
		}
	}

	// Parse or
	if v, ok := m["or"]; ok && v != nil {
		if orSlice, ok := v.([]interface{}); ok {
			for i, item := range orSlice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					orInput, err := ParseCategoryWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'or[%d]': %w", i, err)
					}
					input.Or = append(input.Or, orInput)
				}
			}
		}
	}
	// Parse id
	if v, ok := m["id"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.ID = &val
		}
	}
	// Parse idNEQ
	if v, ok := m["idNEQ"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDNEQ = &val
		}
	}
	// Parse idIn
	if v, ok := m["idIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.IDIn = append(input.IDIn, int(i))
				}
			}
		}
	}
	// Parse idNotIn
	if v, ok := m["idNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.IDNotIn = append(input.IDNotIn, int(i))
				}
			}
		}
	}
	// Parse idGT
	if v, ok := m["idGT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDGT = &val
		}
	}
	// Parse idGTE
	if v, ok := m["idGTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDGTE = &val
		}
	}
	// Parse idLT
	if v, ok := m["idLT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDLT = &val
		}
	}
	// Parse idLTE
	if v, ok := m["idLTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDLTE = &val
		}
	}
	// Parse text
	if v, ok := m["text"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.Text = &s
		}
	}
	// Parse textNEQ
	if v, ok := m["textNEQ"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextNEQ = &s
		}
	}
	// Parse textIn
	if v, ok := m["textIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.TextIn = append(input.TextIn, s)
				}
			}
		}
	}
	// Parse textNotIn
	if v, ok := m["textNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.TextNotIn = append(input.TextNotIn, s)
				}
			}
		}
	}
	// Parse textGT
	if v, ok := m["textGT"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextGT = &s
		}
	}
	// Parse textGTE
	if v, ok := m["textGTE"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextGTE = &s
		}
	}
	// Parse textLT
	if v, ok := m["textLT"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextLT = &s
		}
	}
	// Parse textLTE
	if v, ok := m["textLTE"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextLTE = &s
		}
	}
	// Parse textContains
	if v, ok := m["textContains"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextContains = &s
		}
	}
	// Parse textHasPrefix
	if v, ok := m["textHasPrefix"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextHasPrefix = &s
		}
	}
	// Parse textHasSuffix
	if v, ok := m["textHasSuffix"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextHasSuffix = &s
		}
	}
	// Parse textEqualFold
	if v, ok := m["textEqualFold"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextEqualFold = &s
		}
	}
	// Parse textContainsFold
	if v, ok := m["textContainsFold"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextContainsFold = &s
		}
	}
	// Parse status
	if v, ok := m["status"]; ok && v != nil {
		if s, ok := v.(string); ok {
			val := category.Status(s)
			input.Status = &val
		}
	}
	// Parse statusNEQ
	if v, ok := m["statusNEQ"]; ok && v != nil {
		if s, ok := v.(string); ok {
			val := category.Status(s)
			input.StatusNEQ = &val
		}
	}
	// Parse statusIn
	if v, ok := m["statusIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.StatusIn = append(input.StatusIn, category.Status(s))
				}
			}
		}
	}
	// Parse statusNotIn
	if v, ok := m["statusNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.StatusNotIn = append(input.StatusNotIn, category.Status(s))
				}
			}
		}
	}
	// Parse hasTodos
	if v, ok := m["hasTodos"]; ok && v != nil {
		if b, ok := v.(bool); ok {
			input.HasTodos = &b
		}
	}
	// Parse hasTodosWith
	if v, ok := m["hasTodosWith"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for i, item := range slice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					withInput, err := ParseTodoWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'hasTodosWith[%d]': %w", i, err)
					}
					input.HasTodosWith = append(input.HasTodosWith, withInput)
				}
			}
		}
	}

	return input, nil
}

// TodoWhereInput represents a where input for filtering Todo queries.
type TodoWhereInput struct {
	Predicates []predicate.Todo  `json:"-"`
	Not        *TodoWhereInput   `json:"not,omitempty"`
	Or         []*TodoWhereInput `json:"or,omitempty"`
	And        []*TodoWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *int  `json:"id,omitempty"`
	IDNEQ   *int  `json:"idNEQ,omitempty"`
	IDIn    []int `json:"idIn,omitempty"`
	IDNotIn []int `json:"idNotIn,omitempty"`
	IDGT    *int  `json:"idGT,omitempty"`
	IDGTE   *int  `json:"idGTE,omitempty"`
	IDLT    *int  `json:"idLT,omitempty"`
	IDLTE   *int  `json:"idLTE,omitempty"`

	// "created_at" field predicates.
	CreatedAt      *time.Time  `json:"createdAt,omitempty"`
	CreatedAtNEQ   *time.Time  `json:"createdAtNEQ,omitempty"`
	CreatedAtIn    []time.Time `json:"createdAtIn,omitempty"`
	CreatedAtNotIn []time.Time `json:"createdAtNotIn,omitempty"`
	CreatedAtGT    *time.Time  `json:"createdAtGT,omitempty"`
	CreatedAtGTE   *time.Time  `json:"createdAtGTE,omitempty"`
	CreatedAtLT    *time.Time  `json:"createdAtLT,omitempty"`
	CreatedAtLTE   *time.Time  `json:"createdAtLTE,omitempty"`

	// "status" field predicates.
	Status      *todo.Status  `json:"status,omitempty"`
	StatusNEQ   *todo.Status  `json:"statusNEQ,omitempty"`
	StatusIn    []todo.Status `json:"statusIn,omitempty"`
	StatusNotIn []todo.Status `json:"statusNotIn,omitempty"`

	// "priority" field predicates.
	Priority      *int  `json:"priority,omitempty"`
	PriorityNEQ   *int  `json:"priorityNEQ,omitempty"`
	PriorityIn    []int `json:"priorityIn,omitempty"`
	PriorityNotIn []int `json:"priorityNotIn,omitempty"`
	PriorityGT    *int  `json:"priorityGT,omitempty"`
	PriorityGTE   *int  `json:"priorityGTE,omitempty"`
	PriorityLT    *int  `json:"priorityLT,omitempty"`
	PriorityLTE   *int  `json:"priorityLTE,omitempty"`

	// "text" field predicates.
	Text             *string  `json:"text,omitempty"`
	TextNEQ          *string  `json:"textNEQ,omitempty"`
	TextIn           []string `json:"textIn,omitempty"`
	TextNotIn        []string `json:"textNotIn,omitempty"`
	TextGT           *string  `json:"textGT,omitempty"`
	TextGTE          *string  `json:"textGTE,omitempty"`
	TextLT           *string  `json:"textLT,omitempty"`
	TextLTE          *string  `json:"textLTE,omitempty"`
	TextContains     *string  `json:"textContains,omitempty"`
	TextHasPrefix    *string  `json:"textHasPrefix,omitempty"`
	TextHasSuffix    *string  `json:"textHasSuffix,omitempty"`
	TextEqualFold    *string  `json:"textEqualFold,omitempty"`
	TextContainsFold *string  `json:"textContainsFold,omitempty"`

	// "parent" edge predicates.
	HasParent     *bool             `json:"hasParent,omitempty"`
	HasParentWith []*TodoWhereInput `json:"hasParentWith,omitempty"`

	// "children" edge predicates.
	HasChildren     *bool             `json:"hasChildren,omitempty"`
	HasChildrenWith []*TodoWhereInput `json:"hasChildrenWith,omitempty"`

	// "category" edge predicates.
	HasCategory     *bool                 `json:"hasCategory,omitempty"`
	HasCategoryWith []*CategoryWhereInput `json:"hasCategoryWith,omitempty"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *TodoWhereInput) AddPredicates(predicates ...predicate.Todo) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the TodoWhereInput filter on the TodoQuery builder.
func (i *TodoWhereInput) Filter(q *ent.TodoQuery) (*ent.TodoQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyTodoWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyTodoWhereInput is returned in case the TodoWhereInput is empty.
var ErrEmptyTodoWhereInput = errors.New("gqlgo: empty predicate TodoWhereInput")

// P returns a predicate for filtering todos.
// An error is returned if the input is empty or invalid.
func (i *TodoWhereInput) P() (predicate.Todo, error) {
	var predicates []predicate.Todo
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, todo.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.Todo, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, todo.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.Todo, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, todo.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, todo.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, todo.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, todo.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, todo.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, todo.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, todo.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, todo.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, todo.IDLTE(*i.IDLTE))
	}
	if i.CreatedAt != nil {
		predicates = append(predicates, todo.CreatedAtEQ(*i.CreatedAt))
	}
	if i.CreatedAtNEQ != nil {
		predicates = append(predicates, todo.CreatedAtNEQ(*i.CreatedAtNEQ))
	}
	if len(i.CreatedAtIn) > 0 {
		predicates = append(predicates, todo.CreatedAtIn(i.CreatedAtIn...))
	}
	if len(i.CreatedAtNotIn) > 0 {
		predicates = append(predicates, todo.CreatedAtNotIn(i.CreatedAtNotIn...))
	}
	if i.CreatedAtGT != nil {
		predicates = append(predicates, todo.CreatedAtGT(*i.CreatedAtGT))
	}
	if i.CreatedAtGTE != nil {
		predicates = append(predicates, todo.CreatedAtGTE(*i.CreatedAtGTE))
	}
	if i.CreatedAtLT != nil {
		predicates = append(predicates, todo.CreatedAtLT(*i.CreatedAtLT))
	}
	if i.CreatedAtLTE != nil {
		predicates = append(predicates, todo.CreatedAtLTE(*i.CreatedAtLTE))
	}
	if i.Status != nil {
		predicates = append(predicates, todo.StatusEQ(*i.Status))
	}
	if i.StatusNEQ != nil {
		predicates = append(predicates, todo.StatusNEQ(*i.StatusNEQ))
	}
	if len(i.StatusIn) > 0 {
		predicates = append(predicates, todo.StatusIn(i.StatusIn...))
	}
	if len(i.StatusNotIn) > 0 {
		predicates = append(predicates, todo.StatusNotIn(i.StatusNotIn...))
	}
	if i.Priority != nil {
		predicates = append(predicates, todo.PriorityEQ(*i.Priority))
	}
	if i.PriorityNEQ != nil {
		predicates = append(predicates, todo.PriorityNEQ(*i.PriorityNEQ))
	}
	if len(i.PriorityIn) > 0 {
		predicates = append(predicates, todo.PriorityIn(i.PriorityIn...))
	}
	if len(i.PriorityNotIn) > 0 {
		predicates = append(predicates, todo.PriorityNotIn(i.PriorityNotIn...))
	}
	if i.PriorityGT != nil {
		predicates = append(predicates, todo.PriorityGT(*i.PriorityGT))
	}
	if i.PriorityGTE != nil {
		predicates = append(predicates, todo.PriorityGTE(*i.PriorityGTE))
	}
	if i.PriorityLT != nil {
		predicates = append(predicates, todo.PriorityLT(*i.PriorityLT))
	}
	if i.PriorityLTE != nil {
		predicates = append(predicates, todo.PriorityLTE(*i.PriorityLTE))
	}
	if i.Text != nil {
		predicates = append(predicates, todo.TextEQ(*i.Text))
	}
	if i.TextNEQ != nil {
		predicates = append(predicates, todo.TextNEQ(*i.TextNEQ))
	}
	if len(i.TextIn) > 0 {
		predicates = append(predicates, todo.TextIn(i.TextIn...))
	}
	if len(i.TextNotIn) > 0 {
		predicates = append(predicates, todo.TextNotIn(i.TextNotIn...))
	}
	if i.TextGT != nil {
		predicates = append(predicates, todo.TextGT(*i.TextGT))
	}
	if i.TextGTE != nil {
		predicates = append(predicates, todo.TextGTE(*i.TextGTE))
	}
	if i.TextLT != nil {
		predicates = append(predicates, todo.TextLT(*i.TextLT))
	}
	if i.TextLTE != nil {
		predicates = append(predicates, todo.TextLTE(*i.TextLTE))
	}
	if i.TextContains != nil {
		predicates = append(predicates, todo.TextContains(*i.TextContains))
	}
	if i.TextHasPrefix != nil {
		predicates = append(predicates, todo.TextHasPrefix(*i.TextHasPrefix))
	}
	if i.TextHasSuffix != nil {
		predicates = append(predicates, todo.TextHasSuffix(*i.TextHasSuffix))
	}
	if i.TextEqualFold != nil {
		predicates = append(predicates, todo.TextEqualFold(*i.TextEqualFold))
	}
	if i.TextContainsFold != nil {
		predicates = append(predicates, todo.TextContainsFold(*i.TextContainsFold))
	}

	if i.HasParent != nil {
		p := todo.HasParent()
		if !*i.HasParent {
			p = todo.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasParentWith) > 0 {
		with := make([]predicate.Todo, 0, len(i.HasParentWith))
		for _, w := range i.HasParentWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasParentWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, todo.HasParentWith(with...))
	}
	if i.HasChildren != nil {
		p := todo.HasChildren()
		if !*i.HasChildren {
			p = todo.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasChildrenWith) > 0 {
		with := make([]predicate.Todo, 0, len(i.HasChildrenWith))
		for _, w := range i.HasChildrenWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasChildrenWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, todo.HasChildrenWith(with...))
	}
	if i.HasCategory != nil {
		p := todo.HasCategory()
		if !*i.HasCategory {
			p = todo.Not(p)
		}
		predicates = append(predicates, p)
	}
	if len(i.HasCategoryWith) > 0 {
		with := make([]predicate.Category, 0, len(i.HasCategoryWith))
		for _, w := range i.HasCategoryWith {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'HasCategoryWith'", err)
			}
			with = append(with, p)
		}
		predicates = append(predicates, todo.HasCategoryWith(with...))
	}
	switch len(predicates) {
	case 1:
		return predicates[0], nil
	default:
		return todo.And(predicates...), nil
	}
}

// ParseTodoWhereInput converts a map[string]interface{} from GraphQL into a typed TodoWhereInput.
func ParseTodoWhereInput(m map[string]interface{}) (*TodoWhereInput, error) {
	if m == nil {
		return nil, nil
	}
	input := &TodoWhereInput{}

	// Parse not
	if v, ok := m["not"]; ok && v != nil {
		if notMap, ok := v.(map[string]interface{}); ok {
			notInput, err := ParseTodoWhereInput(notMap)
			if err != nil {
				return nil, fmt.Errorf("parsing 'not': %w", err)
			}
			input.Not = notInput
		}
	}

	// Parse and
	if v, ok := m["and"]; ok && v != nil {
		if andSlice, ok := v.([]interface{}); ok {
			for i, item := range andSlice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					andInput, err := ParseTodoWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'and[%d]': %w", i, err)
					}
					input.And = append(input.And, andInput)
				}
			}
		}
	}

	// Parse or
	if v, ok := m["or"]; ok && v != nil {
		if orSlice, ok := v.([]interface{}); ok {
			for i, item := range orSlice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					orInput, err := ParseTodoWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'or[%d]': %w", i, err)
					}
					input.Or = append(input.Or, orInput)
				}
			}
		}
	}
	// Parse id
	if v, ok := m["id"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.ID = &val
		}
	}
	// Parse idNEQ
	if v, ok := m["idNEQ"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDNEQ = &val
		}
	}
	// Parse idIn
	if v, ok := m["idIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.IDIn = append(input.IDIn, int(i))
				}
			}
		}
	}
	// Parse idNotIn
	if v, ok := m["idNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.IDNotIn = append(input.IDNotIn, int(i))
				}
			}
		}
	}
	// Parse idGT
	if v, ok := m["idGT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDGT = &val
		}
	}
	// Parse idGTE
	if v, ok := m["idGTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDGTE = &val
		}
	}
	// Parse idLT
	if v, ok := m["idLT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDLT = &val
		}
	}
	// Parse idLTE
	if v, ok := m["idLTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.IDLTE = &val
		}
	}
	// Parse createdAt
	if v, ok := m["createdAt"]; ok && v != nil {
		if t, ok := v.(time.Time); ok {
			input.CreatedAt = &t
		}
	}
	// Parse createdAtNEQ
	if v, ok := m["createdAtNEQ"]; ok && v != nil {
		if t, ok := v.(time.Time); ok {
			input.CreatedAtNEQ = &t
		}
	}
	// Parse createdAtIn
	if v, ok := m["createdAtIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if t, ok := item.(time.Time); ok {
					input.CreatedAtIn = append(input.CreatedAtIn, t)
				}
			}
		}
	}
	// Parse createdAtNotIn
	if v, ok := m["createdAtNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if t, ok := item.(time.Time); ok {
					input.CreatedAtNotIn = append(input.CreatedAtNotIn, t)
				}
			}
		}
	}
	// Parse createdAtGT
	if v, ok := m["createdAtGT"]; ok && v != nil {
		if t, ok := v.(time.Time); ok {
			input.CreatedAtGT = &t
		}
	}
	// Parse createdAtGTE
	if v, ok := m["createdAtGTE"]; ok && v != nil {
		if t, ok := v.(time.Time); ok {
			input.CreatedAtGTE = &t
		}
	}
	// Parse createdAtLT
	if v, ok := m["createdAtLT"]; ok && v != nil {
		if t, ok := v.(time.Time); ok {
			input.CreatedAtLT = &t
		}
	}
	// Parse createdAtLTE
	if v, ok := m["createdAtLTE"]; ok && v != nil {
		if t, ok := v.(time.Time); ok {
			input.CreatedAtLTE = &t
		}
	}
	// Parse status
	if v, ok := m["status"]; ok && v != nil {
		if s, ok := v.(string); ok {
			val := todo.Status(s)
			input.Status = &val
		}
	}
	// Parse statusNEQ
	if v, ok := m["statusNEQ"]; ok && v != nil {
		if s, ok := v.(string); ok {
			val := todo.Status(s)
			input.StatusNEQ = &val
		}
	}
	// Parse statusIn
	if v, ok := m["statusIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.StatusIn = append(input.StatusIn, todo.Status(s))
				}
			}
		}
	}
	// Parse statusNotIn
	if v, ok := m["statusNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.StatusNotIn = append(input.StatusNotIn, todo.Status(s))
				}
			}
		}
	}
	// Parse priority
	if v, ok := m["priority"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.Priority = &val
		}
	}
	// Parse priorityNEQ
	if v, ok := m["priorityNEQ"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.PriorityNEQ = &val
		}
	}
	// Parse priorityIn
	if v, ok := m["priorityIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.PriorityIn = append(input.PriorityIn, int(i))
				}
			}
		}
	}
	// Parse priorityNotIn
	if v, ok := m["priorityNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if i, ok := item.(int); ok {
					input.PriorityNotIn = append(input.PriorityNotIn, int(i))
				}
			}
		}
	}
	// Parse priorityGT
	if v, ok := m["priorityGT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.PriorityGT = &val
		}
	}
	// Parse priorityGTE
	if v, ok := m["priorityGTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.PriorityGTE = &val
		}
	}
	// Parse priorityLT
	if v, ok := m["priorityLT"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.PriorityLT = &val
		}
	}
	// Parse priorityLTE
	if v, ok := m["priorityLTE"]; ok && v != nil {
		if i, ok := v.(int); ok {
			val := int(i)
			input.PriorityLTE = &val
		}
	}
	// Parse text
	if v, ok := m["text"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.Text = &s
		}
	}
	// Parse textNEQ
	if v, ok := m["textNEQ"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextNEQ = &s
		}
	}
	// Parse textIn
	if v, ok := m["textIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.TextIn = append(input.TextIn, s)
				}
			}
		}
	}
	// Parse textNotIn
	if v, ok := m["textNotIn"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for _, item := range slice {
				if s, ok := item.(string); ok {
					input.TextNotIn = append(input.TextNotIn, s)
				}
			}
		}
	}
	// Parse textGT
	if v, ok := m["textGT"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextGT = &s
		}
	}
	// Parse textGTE
	if v, ok := m["textGTE"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextGTE = &s
		}
	}
	// Parse textLT
	if v, ok := m["textLT"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextLT = &s
		}
	}
	// Parse textLTE
	if v, ok := m["textLTE"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextLTE = &s
		}
	}
	// Parse textContains
	if v, ok := m["textContains"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextContains = &s
		}
	}
	// Parse textHasPrefix
	if v, ok := m["textHasPrefix"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextHasPrefix = &s
		}
	}
	// Parse textHasSuffix
	if v, ok := m["textHasSuffix"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextHasSuffix = &s
		}
	}
	// Parse textEqualFold
	if v, ok := m["textEqualFold"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextEqualFold = &s
		}
	}
	// Parse textContainsFold
	if v, ok := m["textContainsFold"]; ok && v != nil {
		if s, ok := v.(string); ok {
			input.TextContainsFold = &s
		}
	}
	// Parse hasParent
	if v, ok := m["hasParent"]; ok && v != nil {
		if b, ok := v.(bool); ok {
			input.HasParent = &b
		}
	}
	// Parse hasParentWith
	if v, ok := m["hasParentWith"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for i, item := range slice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					withInput, err := ParseTodoWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'hasParentWith[%d]': %w", i, err)
					}
					input.HasParentWith = append(input.HasParentWith, withInput)
				}
			}
		}
	}
	// Parse hasChildren
	if v, ok := m["hasChildren"]; ok && v != nil {
		if b, ok := v.(bool); ok {
			input.HasChildren = &b
		}
	}
	// Parse hasChildrenWith
	if v, ok := m["hasChildrenWith"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for i, item := range slice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					withInput, err := ParseTodoWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'hasChildrenWith[%d]': %w", i, err)
					}
					input.HasChildrenWith = append(input.HasChildrenWith, withInput)
				}
			}
		}
	}
	// Parse hasCategory
	if v, ok := m["hasCategory"]; ok && v != nil {
		if b, ok := v.(bool); ok {
			input.HasCategory = &b
		}
	}
	// Parse hasCategoryWith
	if v, ok := m["hasCategoryWith"]; ok && v != nil {
		if slice, ok := v.([]interface{}); ok {
			for i, item := range slice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					withInput, err := ParseCategoryWhereInput(itemMap)
					if err != nil {
						return nil, fmt.Errorf("parsing 'hasCategoryWith[%d]': %w", i, err)
					}
					input.HasCategoryWith = append(input.HasCategoryWith, withInput)
				}
			}
		}
	}

	return input, nil
}
