// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in entgo.io/contrib/entgqlgo/internal/parity/ent/runtime.go

const (
	Version = "v0.14.4" // Version of ent codegen.
)
