// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package ent

import (
	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/edges"
	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/todo"
)

// Type aliases — public consumer-facing names continue resolving here
// while the underlying types live in the per-entity sub-package.
type (
	TodoClient     = todo.TodoClient
	TodoQuery      = todo.TodoQuery
	TodoMutation   = todo.TodoMutation
	TodoCreate     = todo.TodoCreate
	TodoCreateBulk = todo.TodoCreateBulk
	TodoUpdate     = todo.TodoUpdate
	TodoUpdateOne  = todo.TodoUpdateOne
	TodoDelete     = todo.TodoDelete
	TodoDeleteOne  = todo.TodoDeleteOne
	TodoGroupBy    = todo.TodoGroupBy
	TodoSelect     = todo.TodoSelect
	TodoStatus     = todo.Status
)

// Constructor aliases — the sub-package's New<X> stays the source of truth.
var (
	NewTodoClient = todo.NewTodoClient
)

// WithTodoParent forwards to edges.WithTodoParent — body hoisted to gen/edges/todo.go for build parallelism.
var WithTodoParent = edges.WithTodoParent

// QueryTodoParent forwards to edges.QueryTodoParent.
var QueryTodoParent = edges.QueryTodoParent

// QueryTodoParentFromQuery forwards to edges.QueryTodoParentFromQuery.
var QueryTodoParentFromQuery = edges.QueryTodoParentFromQuery

// WithTodoChildren forwards to edges.WithTodoChildren — body hoisted to gen/edges/todo.go for build parallelism.
var WithTodoChildren = edges.WithTodoChildren

// WithNamedTodoChildren forwards to edges.WithNamedTodoChildren.
var WithNamedTodoChildren = edges.WithNamedTodoChildren

// QueryTodoChildren forwards to edges.QueryTodoChildren.
var QueryTodoChildren = edges.QueryTodoChildren

// QueryTodoChildrenFromQuery forwards to edges.QueryTodoChildrenFromQuery.
var QueryTodoChildrenFromQuery = edges.QueryTodoChildrenFromQuery

// WithTodoCategory forwards to edges.WithTodoCategory — body hoisted to gen/edges/todo.go for build parallelism.
var WithTodoCategory = edges.WithTodoCategory

// QueryTodoCategory forwards to edges.QueryTodoCategory.
var QueryTodoCategory = edges.QueryTodoCategory

// QueryTodoCategoryFromQuery forwards to edges.QueryTodoCategoryFromQuery.
var QueryTodoCategoryFromQuery = edges.QueryTodoCategoryFromQuery
