// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package category

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/predicate"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
)

// CategoryQuery is the builder for querying Category entities.
type CategoryQuery struct {
	Config
	entbuilder.QueryState[predicate.Category]
	order        []OrderOption
	eagerLoaders map[string]func(context.Context, []*Category) error
}

// StoreEager registers an eager-load callback for the given edge name.
// Exposed for the root facade's With<Entity><Edge> free functions.
func (_q *CategoryQuery) StoreEager(name string, loader func(context.Context, []*Category) error) *CategoryQuery {
	if _q.eagerLoaders == nil {
		_q.eagerLoaders = make(map[string]func(context.Context, []*Category) error)
	}
	_q.eagerLoaders[name] = loader
	return _q
}

// EagerLoaders returns the registered eager-load callbacks (read-only).
// Used by the sub-package's All() (Task 13) and by root facade utilities.
func (_q *CategoryQuery) EagerLoaders() map[string]func(context.Context, []*Category) error {
	return _q.eagerLoaders
}

// Where adds a new predicate for the CategoryQuery builder.
func (_q *CategoryQuery) Where(ps ...predicate.Category) *CategoryQuery {
	_q.AddPredicates(ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CategoryQuery) Limit(limit int) *CategoryQuery {
	_q.SetLimit(limit)
	return _q
}

// Offset to start from.
func (_q *CategoryQuery) Offset(offset int) *CategoryQuery {
	_q.SetOffset(offset)
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CategoryQuery) Unique(unique bool) *CategoryQuery {
	_q.SetUnique(unique)
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CategoryQuery) Order(o ...OrderOption) *CategoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first Category entity from the query.
// Returns a *NotFoundError when no Category was found.
func (_q *CategoryQuery) First(ctx context.Context) (*Category, error) {
	_q.Limit(1)
	return entbuilder.RunFirst[*Category, []*Category](ctx, _q, _q.Ctx, ent.OpQueryFirst, Label, _q.QueryState.Inters, _q.prepareQuery, func(ctx context.Context) ([]*Category, error) { return _q.sqlAll(ctx) }, func(label string) error { return &NotFoundError{Label: label} })
}

// FirstX is like First, but panics if an error occurs.
func (_q *CategoryQuery) FirstX(ctx context.Context) *Category {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Category ID from the query.
// Returns a *NotFoundError when no Category ID was found.
func (_q *CategoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.Ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{Label: Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *CategoryQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Category entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Category entity is found.
// Returns a *NotFoundError when no Category entities are found.
func (_q *CategoryQuery) Only(ctx context.Context) (*Category, error) {
	_q.Limit(2)
	return entbuilder.RunOnly[*Category, []*Category](ctx, _q, _q.Ctx, ent.OpQueryOnly, Label, _q.QueryState.Inters, _q.prepareQuery, func(ctx context.Context) ([]*Category, error) { return _q.sqlAll(ctx) }, func(label string) error { return &NotFoundError{Label: label} }, func(label string) error { return &NotSingularError{Label: label} })
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CategoryQuery) OnlyX(ctx context.Context) *Category {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Category ID in the query.
// Returns a *NotSingularError when more than one Category ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *CategoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.Ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{Label: Label}
	default:
		err = &NotSingularError{Label: Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *CategoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Categories.
func (_q *CategoryQuery) All(ctx context.Context) ([]*Category, error) {
	return entbuilder.RunAll[[]*Category](ctx, _q, _q.Ctx, ent.OpQueryAll, _q.QueryState.Inters, _q.prepareQuery, func(ctx context.Context) ([]*Category, error) { return _q.sqlAll(ctx) })
}

// AllX is like All, but panics if an error occurs.
func (_q *CategoryQuery) AllX(ctx context.Context) []*Category {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Category IDs.
func (_q *CategoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.Ctx.Unique == nil && _q.Path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.Ctx, ent.OpQueryIDs)
	if err = _q.Select(FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *CategoryQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *CategoryQuery) Count(ctx context.Context) (int, error) {
	return entbuilder.RunCount(ctx, _q, _q.Ctx, ent.OpQueryCount, _q.QueryState.Inters, _q.prepareQuery, _q.sqlCount)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CategoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.Ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CategoryQuery) Clone() *CategoryQuery {
	if _q == nil {
		return nil
	}
	return &CategoryQuery{
		Config:       _q.Config,
		QueryState:   *_q.QueryState.Clone(),
		order:        append([]OrderOption{}, _q.order...),
		eagerLoaders: cloneEagerLoadersCategory(_q.eagerLoaders),
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Category.Query().
//		GroupBy(FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CategoryQuery) GroupBy(field string, fields ...string) *CategoryGroupBy {
	_q.Ctx.Fields = append([]string{field}, fields...)
	grbuild := &CategoryGroupBy{build: _q}
	grbuild.Flds = &_q.Ctx.Fields
	grbuild.Label = Label
	grbuild.ScanFn = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Category.Query().
//		Select(FieldName).
//		Scan(ctx, &v)
func (_q *CategoryQuery) Select(fields ...string) *CategorySelect {
	_q.Ctx.Fields = append(_q.Ctx.Fields, fields...)
	sbuild := &CategorySelect{CategoryQuery: _q}
	sbuild.Label = Label
	sbuild.Flds, sbuild.ScanFn = &_q.Ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CategorySelect configured with the given aggregations.
func (_q *CategoryQuery) Aggregate(fns ...AggregateFunc) *CategorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.QueryState.Inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.Ctx.Fields {
		if !ValidColumn(f) {
			return &ValidationError{Name: f, Err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.Path != nil {
		prev, err := _q.Path(ctx)
		if err != nil {
			return err
		}
		_q.Sql = prev
	}
	return nil
}

func (_q *CategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Category, error) {
	nodes, err := _q.Fetch(ctx, hooks...)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	// Dispatch any registered eager loaders. Callbacks were captured by
	// the root facade's With<Entity><Edge> free functions and receive the
	// parent slice for in-place edge assignment. Dispatch lives in sqlAll
	// (not All) so Only/First/IDs/etc. — which all call sqlAll — also
	// fire registered loaders. Fetch is the no-dispatch alternative used
	// by load helpers themselves to avoid recursion.
	for _, loader := range _q.eagerLoaders {
		if err := loader(ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// Fetch executes the SQL parent query only — no eager loading.
// Exposed for the root facade's edge-loading helpers (Task 17), which
// call Fetch on a sub-query to materialize neighbors during eager dispatch.
// Called internally by sqlAll, which wraps Fetch with the eager-loader
// dispatch loop.
func (_q *CategoryQuery) Fetch(ctx context.Context, hooks ...queryHook) ([]*Category, error) {
	var (
		nodes       = []*Category{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.eagerLoaders["todos"] != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Category).ScanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Category{Config: _q.Config}
		nodes = append(nodes, node)
		node.Edges.SetLoadedTypes(loadedTypes)
		return node.AssignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.Drv, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

// PrepareQuery is the exported counterpart of prepareQuery — used by
// root facade eager-load helpers that build join predicates and need
// to attach interceptors/hooks before executing the sub-query.
func (_q *CategoryQuery) PrepareQuery(ctx context.Context) error {
	return _q.prepareQuery(ctx)
}

// SQLQuery is the exported counterpart of sqlQuery — used by root
// facade chained-edge helpers (e.g., QueryXEdgeFromQuery) that need
// this query's SQL selector to construct a SetNeighbors sub-step.
func (_q *CategoryQuery) SQLQuery(ctx context.Context) *sql.Selector {
	return _q.sqlQuery(ctx)
}

// IncludeForeignKeys is a no-op for types with no unexported foreign-key
// columns — every column is already in the SELECT. Emitted so root facade
// load helpers can call it unconditionally without compile-time branching
// on the loaded sibling's FK shape.
func (_q *CategoryQuery) IncludeForeignKeys(bool) *CategoryQuery {
	return _q
}

func (_q *CategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.Ctx.Fields
	if len(_q.Ctx.Fields) > 0 {
		_spec.Unique = _q.Ctx.Unique != nil && *_q.Ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.Drv, _spec)
}

func (_q *CategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(Table, Columns, sqlgraph.NewFieldSpec(FieldID, field.TypeInt))
	_spec.From = _q.Sql
	if unique := _q.Ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.Path != nil {
		_spec.Unique = true
	}
	if fields := _q.Ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, FieldID)
		for i := range fields {
			if fields[i] != FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.Predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.Ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.Ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.Drv.Dialect())
	t1 := builder.Table(Table)
	columns := _q.Ctx.Fields
	if len(columns) == 0 {
		columns = Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.Sql != nil {
		selector = _q.Sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.Ctx.Unique != nil && *_q.Ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.Predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.Ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.Ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CategoryGroupBy is the group-by builder for Category entities.
type CategoryGroupBy struct {
	selector
	build *CategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CategoryGroupBy) Aggregate(fns ...AggregateFunc) *CategoryGroupBy {
	_g.Fns = append(_g.Fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.Ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CategoryQuery, *CategoryGroupBy](ctx, _g.build, _g, _g.build.QueryState.Inters, v)
}

func (_g *CategoryGroupBy) sqlScan(ctx context.Context, root *CategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.Fns))
	for _, fn := range _g.Fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.Flds)+len(_g.Fns))
		for _, f := range *_g.Flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.Flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.Drv.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CategorySelect is the builder for selecting fields of Category entities.
type CategorySelect struct {
	*CategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CategorySelect) Aggregate(fns ...AggregateFunc) *CategorySelect {
	_s.Fns = append(_s.Fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.Ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CategoryQuery, *CategorySelect](ctx, _s.CategoryQuery, _s, _s.QueryState.Inters, v)
}

func (_s *CategorySelect) sqlScan(ctx context.Context, root *CategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.Fns))
	for _, fn := range _s.Fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.Flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.Drv.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// categoryCreateDescriptor holds the metadata and callbacks for constructing a Category entity.
var categoryCreateDescriptor = &entbuilder.CreateDescriptor[Config, Category, *CategoryMutation]{
	Table:   Table,
	NewNode: func(c Config) *Category { return &Category{Config: c} },
	ID: &entbuilder.IDDescriptor[Config, Category, *CategoryMutation]{
		Column:      FieldID,
		Type:        field.TypeInt,
		UserDefined: false,
		AssignGenerated: func(n *Category, v driver.Value) error {
			id, ok := v.(int64)
			if !ok {
				return fmt.Errorf("unexpected Category.ID type: %T", v)
			}
			n.ID = int(id)
			return nil
		},
	},
}

// cloneEagerLoadersCategory returns a shallow copy of the eager-loaders map.
// The closures themselves are shared between original and clone.
func cloneEagerLoadersCategory(in map[string]func(context.Context, []*Category) error) map[string]func(context.Context, []*Category) error {
	if in == nil {
		return nil
	}
	out := make(map[string]func(context.Context, []*Category) error, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}
