// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package edges

import (
	"context"
	"database/sql/driver"
	"fmt"

	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/predicate"
	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/todo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// LoadTodoParent performs the eager-load for the "parent" edge. Body mirrors
// the pre-PR6 *TodoQuery.loadParent method, hoisted to root
// so it can reference cross-package types directly.
func LoadTodoParent(ctx context.Context, query *todo.TodoQuery, nodes []*todo.Todo) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*todo.Todo)
	for i := range nodes {
		if nodes[i].GetTodoChildren() == nil {
			continue
		}
		fk := *nodes[i].GetTodoChildren()
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(todo.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		parents, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "todo_children" returned %v`, n.ID)
		}
		for i := range parents {
			parents[i].Edges.Parent = n
		}
	}
	return nil
}

// WithTodoParent eager-loads the "parent" edge on a todo.TodoQuery. The
// optional arguments configure the sibling sub-query before storage.
func WithTodoParent(q *todo.TodoQuery, opts ...func(*todo.TodoQuery)) *todo.TodoQuery {
	sub := todo.NewTodoClient(q.Config).Query()
	for _, opt := range opts {
		opt(sub)
	}
	return q.StoreEager("parent", func(ctx context.Context, parents []*todo.Todo) error {
		return LoadTodoParent(ctx, sub, parents)
	})
}

// QueryTodoParent returns a todo.TodoQuery for the "parent" edge of a given todo.Todo.
func QueryTodoParent(c *todo.TodoClient, _m *todo.Todo) *todo.TodoQuery {
	query := todo.NewTodoClient(c.Config).Query()
	query.Path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(todo.Table, todo.FieldID, id),
			sqlgraph.To(todo.Table, todo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, todo.ParentTable, todo.ParentColumn),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)

		return fromV, nil
	}
	return query
}

// QueryTodoParentFromQuery returns a todo.TodoQuery that traverses the "parent" edge
// of every todo.Todo matched by q (chained-query form). Mirrors the pre-PR6
// (*todo.TodoQuery).QueryParent method, hoisted to root so it
// can reference the cross-package todo.TodoQuery type.
func QueryTodoParentFromQuery(q *todo.TodoQuery) *todo.TodoQuery {
	query := todo.NewTodoClient(q.Config).Query()
	query.Path = func(ctx context.Context) (fromV *sql.Selector, err error) {
		if err := q.PrepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := q.SQLQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(todo.Table, todo.FieldID, selector),
			sqlgraph.To(todo.Table, todo.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, todo.ParentTable, todo.ParentColumn),
		)
		fromV = sqlgraph.SetNeighbors(q.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}

// LoadTodoChildren performs the eager-load for the "children" edge. Body mirrors
// the pre-PR6 *TodoQuery.loadChildren method, hoisted to root
// so it can reference cross-package types directly.
func LoadTodoChildren(ctx context.Context, query *todo.TodoQuery, nodes []*todo.Todo) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*todo.Todo)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		nodes[i].Edges.Children = []*todo.Todo{}
	}
	query.IncludeForeignKeys(true)
	query.Where(predicate.Todo(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(todo.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GetTodoChildren()
		if fk == nil {
			return fmt.Errorf(`foreign-key "todo_children" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "todo_children" returned %v for node %v`, *fk, n.ID)
		}
		node.Edges.Children = append(node.Edges.Children, n)
	}
	return nil
}

// LoadNamedTodoChildren is the named-edge variant of LoadTodoChildren. It runs the same
// neighbor-fetch logic but appends each result to the parent's
// AppendNamedChildren(name, ...) bucket instead of the default
// Edges.Children slice. Each call seeds an empty bucket for the
// name so consumers can distinguish "loaded with zero rows" from "never
// loaded".
func LoadNamedTodoChildren(ctx context.Context, query *todo.TodoQuery, nodes []*todo.Todo, name string) error {
	for _, node := range nodes {
		node.AppendNamedChildren(name)
	}
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*todo.Todo)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.IncludeForeignKeys(true)
	query.Where(predicate.Todo(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(todo.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.GetTodoChildren()
		if fk == nil {
			return fmt.Errorf(`foreign-key "todo_children" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "todo_children" returned %v for node %v`, *fk, n.ID)
		}
		node.AppendNamedChildren(name, n)
	}
	return nil
}

// WithTodoChildren eager-loads the "children" edge on a todo.TodoQuery. The
// optional arguments configure the sibling sub-query before storage.
func WithTodoChildren(q *todo.TodoQuery, opts ...func(*todo.TodoQuery)) *todo.TodoQuery {
	sub := todo.NewTodoClient(q.Config).Query()
	for _, opt := range opts {
		opt(sub)
	}
	return q.StoreEager("children", func(ctx context.Context, parents []*todo.Todo) error {
		return LoadTodoChildren(ctx, sub, parents)
	})
}

// WithNamedTodoChildren registers a named eager-loader for the "children" edge on a
// todo.TodoQuery. Multiple names accumulate; each loads independently and
// is retrievable via Todo.NamedChildren(name). Replaces the
// pre-PR6 (*todo.TodoQuery).WithNamedChildren method, hoisted to root
// so the named-loader map can hold the cross-package todo.TodoQuery type.
func WithNamedTodoChildren(q *todo.TodoQuery, name string, opts ...func(*todo.TodoQuery)) *todo.TodoQuery {
	sub := todo.NewTodoClient(q.Config).Query()
	for _, opt := range opts {
		opt(sub)
	}
	return q.StoreEager("children:"+name, func(ctx context.Context, parents []*todo.Todo) error {
		return LoadNamedTodoChildren(ctx, sub, parents, name)
	})
}

// QueryTodoChildren returns a todo.TodoQuery for the "children" edge of a given todo.Todo.
func QueryTodoChildren(c *todo.TodoClient, _m *todo.Todo) *todo.TodoQuery {
	query := todo.NewTodoClient(c.Config).Query()
	query.Path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(todo.Table, todo.FieldID, id),
			sqlgraph.To(todo.Table, todo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, todo.ChildrenTable, todo.ChildrenColumn),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)

		return fromV, nil
	}
	return query
}

// QueryTodoChildrenFromQuery returns a todo.TodoQuery that traverses the "children" edge
// of every todo.Todo matched by q (chained-query form). Mirrors the pre-PR6
// (*todo.TodoQuery).QueryChildren method, hoisted to root so it
// can reference the cross-package todo.TodoQuery type.
func QueryTodoChildrenFromQuery(q *todo.TodoQuery) *todo.TodoQuery {
	query := todo.NewTodoClient(q.Config).Query()
	query.Path = func(ctx context.Context) (fromV *sql.Selector, err error) {
		if err := q.PrepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := q.SQLQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(todo.Table, todo.FieldID, selector),
			sqlgraph.To(todo.Table, todo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, todo.ChildrenTable, todo.ChildrenColumn),
		)
		fromV = sqlgraph.SetNeighbors(q.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}

// LoadTodoCategory performs the eager-load for the "category" edge. Body mirrors
// the pre-PR6 *TodoQuery.loadCategory method, hoisted to root
// so it can reference cross-package types directly.
func LoadTodoCategory(ctx context.Context, query *category.CategoryQuery, nodes []*todo.Todo) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*todo.Todo)
	for i := range nodes {
		if nodes[i].GetCategoryTodos() == nil {
			continue
		}
		fk := *nodes[i].GetCategoryTodos()
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(category.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		parents, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "category_todos" returned %v`, n.ID)
		}
		for i := range parents {
			parents[i].Edges.Category = n
		}
	}
	return nil
}

// WithTodoCategory eager-loads the "category" edge on a todo.TodoQuery. The
// optional arguments configure the sibling sub-query before storage.
func WithTodoCategory(q *todo.TodoQuery, opts ...func(*category.CategoryQuery)) *todo.TodoQuery {
	sub := category.NewCategoryClient(q.Config).Query()
	for _, opt := range opts {
		opt(sub)
	}
	return q.StoreEager("category", func(ctx context.Context, parents []*todo.Todo) error {
		return LoadTodoCategory(ctx, sub, parents)
	})
}

// QueryTodoCategory returns a category.CategoryQuery for the "category" edge of a given todo.Todo.
func QueryTodoCategory(c *todo.TodoClient, _m *todo.Todo) *category.CategoryQuery {
	query := category.NewCategoryClient(c.Config).Query()
	query.Path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(todo.Table, todo.FieldID, id),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, todo.CategoryTable, todo.CategoryColumn),
		)
		fromV = sqlgraph.Neighbors(_m.Drv.Dialect(), step)

		return fromV, nil
	}
	return query
}

// QueryTodoCategoryFromQuery returns a category.CategoryQuery that traverses the "category" edge
// of every todo.Todo matched by q (chained-query form). Mirrors the pre-PR6
// (*todo.TodoQuery).QueryCategory method, hoisted to root so it
// can reference the cross-package category.CategoryQuery type.
func QueryTodoCategoryFromQuery(q *todo.TodoQuery) *category.CategoryQuery {
	query := category.NewCategoryClient(q.Config).Query()
	query.Path = func(ctx context.Context) (fromV *sql.Selector, err error) {
		if err := q.PrepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := q.SQLQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(todo.Table, todo.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, todo.CategoryTable, todo.CategoryColumn),
		)
		fromV = sqlgraph.SetNeighbors(q.Drv.Dialect(), step)
		return fromV, nil
	}
	return query
}
