// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"

	"entgo.io/contrib/entgqlgo/internal/parity/ent/category"
	"entgo.io/contrib/entgqlgo/internal/parity/ent/predicate"
	"entgo.io/contrib/entgqlgo/internal/parity/ent/todo"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/runtime/entbuilder"
	"entgo.io/ent/schema/field"
)

// TodoUpdate is the builder for updating Todo entities.
type TodoUpdate struct {
	config
	hooks    []Hook
	mutation *TodoMutation
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdate) Where(ps ...predicate.Todo) *TodoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TodoUpdate) SetStatus(v todo.Status) *TodoUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableStatus(v *todo.Status) *TodoUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TodoUpdate) SetPriority(v int) *TodoUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TodoUpdate) SetNillablePriority(v *int) *TodoUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TodoUpdate) AddPriority(v int) *TodoUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetText sets the "text" field.
func (_u *TodoUpdate) SetText(v string) *TodoUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableText(v *string) *TodoUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *TodoUpdate) SetNote(v string) *TodoUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *TodoUpdate) SetNillableNote(v *string) *TodoUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetParentID sets the "parent" edge to the Todo entity by ID.
func (_u *TodoUpdate) SetParentID(id int) *TodoUpdate {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Todo entity by ID if the given value is not nil.
func (_u *TodoUpdate) SetNillableParentID(id *int) *TodoUpdate {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Todo entity.
func (_u *TodoUpdate) SetParent(v *Todo) *TodoUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Todo entity by IDs.
func (_u *TodoUpdate) AddChildIDs(ids ...int) *TodoUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Todo entity.
func (_u *TodoUpdate) AddChildren(v ...*Todo) *TodoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *TodoUpdate) SetCategoryID(id int) *TodoUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *TodoUpdate) SetNillableCategoryID(id *int) *TodoUpdate {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *TodoUpdate) SetCategory(v *Category) *TodoUpdate {
	return _u.SetCategoryID(v.ID)
}

// SetOwnerID sets the "owner" edge to the Category entity by ID.
func (_u *TodoUpdate) SetOwnerID(id int) *TodoUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Category entity.
func (_u *TodoUpdate) SetOwner(v *Category) *TodoUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (_u *TodoUpdate) Mutation() *TodoMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Todo entity.
func (_u *TodoUpdate) ClearParent() *TodoUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Todo entity.
func (_u *TodoUpdate) ClearChildren() *TodoUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Todo entities by IDs.
func (_u *TodoUpdate) RemoveChildIDs(ids ...int) *TodoUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Todo entities.
func (_u *TodoUpdate) RemoveChildren(v ...*Todo) *TodoUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *TodoUpdate) ClearCategory() *TodoUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// ClearOwner clears the "owner" edge to the Category entity.
func (_u *TodoUpdate) ClearOwner() *TodoUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TodoUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TodoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := todo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Text(); ok {
		if err := todo.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Todo.text": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.owner"`)
	}
	return nil
}

var todoUpdateDescriptor = entbuilder.UpdateDescriptor[config, *TodoMutation]{
	Fields: []entbuilder.UpdateFieldDescriptor[*TodoMutation]{
		{
			Column: todo.FieldStatus,
			Type:   field.TypeEnum,
			Set: func(m *TodoMutation) (driver.Value, bool, error) {
				if value, ok := m.Status(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},

		{
			Column: todo.FieldPriority,
			Type:   field.TypeInt,
			Set: func(m *TodoMutation) (driver.Value, bool, error) {
				if value, ok := m.Priority(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
			Add: func(m *TodoMutation) (driver.Value, bool, error) {
				if value, ok := m.AddedPriority(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},

		{
			Column: todo.FieldText,
			Type:   field.TypeString,
			Set: func(m *TodoMutation) (driver.Value, bool, error) {
				if value, ok := m.Text(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},

		{
			Column: todo.FieldNote,
			Type:   field.TypeString,
			Set: func(m *TodoMutation) (driver.Value, bool, error) {
				if value, ok := m.Note(); ok {
					return value, true, nil
				}
				return nil, false, nil
			},
		},
	},
	Edges: []entbuilder.UpdateEdgeDescriptor[config, *TodoMutation]{
		{
			Clear: func(cfg config, m *TodoMutation) (*sqlgraph.EdgeSpec, bool, error) {
				if m.ParentCleared() {
					edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
						Rel:          sqlgraph.M2O,
						Inverse:      true,
						Table:        todo.ParentTable,
						Columns:      todo.ParentColumn,
						Bidi:         false,
						TargetColumn: todo.FieldID,
						TargetType:   field.TypeInt,
					})
					return edge, true, nil
				}
				return nil, false, nil
			},
			Add: func(cfg config, m *TodoMutation) ([]*sqlgraph.EdgeSpec, error) {
				nodes := m.ParentIDs()
				if len(nodes) == 0 {
					return nil, nil
				}
				edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
					Rel:          sqlgraph.M2O,
					Inverse:      true,
					Table:        todo.ParentTable,
					Columns:      todo.ParentColumn,
					Bidi:         false,
					TargetColumn: todo.FieldID,
					TargetType:   field.TypeInt,
				})
				for _, id := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, id)
				}
				return []*sqlgraph.EdgeSpec{edge}, nil
			},
		},

		{
			Clear: func(cfg config, m *TodoMutation) (*sqlgraph.EdgeSpec, bool, error) {
				if m.ChildrenCleared() {
					edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
						Rel:          sqlgraph.O2M,
						Inverse:      false,
						Table:        todo.ChildrenTable,
						Columns:      todo.ChildrenColumn,
						Bidi:         false,
						TargetColumn: todo.FieldID,
						TargetType:   field.TypeInt,
					})
					return edge, true, nil
				}
				return nil, false, nil
			},
			Remove: func(cfg config, m *TodoMutation) ([]*sqlgraph.EdgeSpec, error) {
				nodes := m.RemovedChildrenIDs()
				if len(nodes) == 0 || m.ChildrenCleared() {
					return nil, nil
				}
				edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
					Rel:          sqlgraph.O2M,
					Inverse:      false,
					Table:        todo.ChildrenTable,
					Columns:      todo.ChildrenColumn,
					Bidi:         false,
					TargetColumn: todo.FieldID,
					TargetType:   field.TypeInt,
				})
				for _, id := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, id)
				}
				return []*sqlgraph.EdgeSpec{edge}, nil
			},
			Add: func(cfg config, m *TodoMutation) ([]*sqlgraph.EdgeSpec, error) {
				nodes := m.ChildrenIDs()
				if len(nodes) == 0 {
					return nil, nil
				}
				edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
					Rel:          sqlgraph.O2M,
					Inverse:      false,
					Table:        todo.ChildrenTable,
					Columns:      todo.ChildrenColumn,
					Bidi:         false,
					TargetColumn: todo.FieldID,
					TargetType:   field.TypeInt,
				})
				for _, id := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, id)
				}
				return []*sqlgraph.EdgeSpec{edge}, nil
			},
		},

		{
			Clear: func(cfg config, m *TodoMutation) (*sqlgraph.EdgeSpec, bool, error) {
				if m.CategoryCleared() {
					edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
						Rel:          sqlgraph.M2O,
						Inverse:      true,
						Table:        todo.CategoryTable,
						Columns:      todo.CategoryColumn,
						Bidi:         false,
						TargetColumn: category.FieldID,
						TargetType:   field.TypeInt,
					})
					return edge, true, nil
				}
				return nil, false, nil
			},
			Add: func(cfg config, m *TodoMutation) ([]*sqlgraph.EdgeSpec, error) {
				nodes := m.CategoryIDs()
				if len(nodes) == 0 {
					return nil, nil
				}
				edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
					Rel:          sqlgraph.M2O,
					Inverse:      true,
					Table:        todo.CategoryTable,
					Columns:      todo.CategoryColumn,
					Bidi:         false,
					TargetColumn: category.FieldID,
					TargetType:   field.TypeInt,
				})
				for _, id := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, id)
				}
				return []*sqlgraph.EdgeSpec{edge}, nil
			},
		},

		{
			Clear: func(cfg config, m *TodoMutation) (*sqlgraph.EdgeSpec, bool, error) {
				if m.OwnerCleared() {
					edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
						Rel:          sqlgraph.M2O,
						Inverse:      false,
						Table:        todo.OwnerTable,
						Columns:      todo.OwnerColumn,
						Bidi:         false,
						TargetColumn: category.FieldID,
						TargetType:   field.TypeInt,
					})
					return edge, true, nil
				}
				return nil, false, nil
			},
			Add: func(cfg config, m *TodoMutation) ([]*sqlgraph.EdgeSpec, error) {
				nodes := m.OwnerIDs()
				if len(nodes) == 0 {
					return nil, nil
				}
				edge := entbuilder.NewEdgeSpec(entbuilder.EdgeSpecParams{
					Rel:          sqlgraph.M2O,
					Inverse:      false,
					Table:        todo.OwnerTable,
					Columns:      todo.OwnerColumn,
					Bidi:         false,
					TargetColumn: category.FieldID,
					TargetType:   field.TypeInt,
				})
				for _, id := range nodes {
					edge.Target.Nodes = append(edge.Target.Nodes, id)
				}
				return []*sqlgraph.EdgeSpec{edge}, nil
			},
		},
	},
}

func (_u *TodoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if err := entbuilder.ApplyUpdate(_u.config, _u.mutation, &todoUpdateDescriptor, _spec); err != nil {
		return 0, err
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TodoUpdateOne is the builder for updating a single Todo entity.
type TodoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TodoMutation
}

// SetStatus sets the "status" field.
func (_u *TodoUpdateOne) SetStatus(v todo.Status) *TodoUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableStatus(v *todo.Status) *TodoUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TodoUpdateOne) SetPriority(v int) *TodoUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillablePriority(v *int) *TodoUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TodoUpdateOne) AddPriority(v int) *TodoUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetText sets the "text" field.
func (_u *TodoUpdateOne) SetText(v string) *TodoUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableText(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *TodoUpdateOne) SetNote(v string) *TodoUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableNote(v *string) *TodoUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// SetParentID sets the "parent" edge to the Todo entity by ID.
func (_u *TodoUpdateOne) SetParentID(id int) *TodoUpdateOne {
	_u.mutation.SetParentID(id)
	return _u
}

// SetNillableParentID sets the "parent" edge to the Todo entity by ID if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableParentID(id *int) *TodoUpdateOne {
	if id != nil {
		_u = _u.SetParentID(*id)
	}
	return _u
}

// SetParent sets the "parent" edge to the Todo entity.
func (_u *TodoUpdateOne) SetParent(v *Todo) *TodoUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the Todo entity by IDs.
func (_u *TodoUpdateOne) AddChildIDs(ids ...int) *TodoUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Todo entity.
func (_u *TodoUpdateOne) AddChildren(v ...*Todo) *TodoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetCategoryID sets the "category" edge to the Category entity by ID.
func (_u *TodoUpdateOne) SetCategoryID(id int) *TodoUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetNillableCategoryID sets the "category" edge to the Category entity by ID if the given value is not nil.
func (_u *TodoUpdateOne) SetNillableCategoryID(id *int) *TodoUpdateOne {
	if id != nil {
		_u = _u.SetCategoryID(*id)
	}
	return _u
}

// SetCategory sets the "category" edge to the Category entity.
func (_u *TodoUpdateOne) SetCategory(v *Category) *TodoUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// SetOwnerID sets the "owner" edge to the Category entity by ID.
func (_u *TodoUpdateOne) SetOwnerID(id int) *TodoUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the Category entity.
func (_u *TodoUpdateOne) SetOwner(v *Category) *TodoUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the TodoMutation object of the builder.
func (_u *TodoUpdateOne) Mutation() *TodoMutation {
	return _u.mutation
}

// ClearParent clears the "parent" edge to the Todo entity.
func (_u *TodoUpdateOne) ClearParent() *TodoUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the Todo entity.
func (_u *TodoUpdateOne) ClearChildren() *TodoUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Todo entities by IDs.
func (_u *TodoUpdateOne) RemoveChildIDs(ids ...int) *TodoUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Todo entities.
func (_u *TodoUpdateOne) RemoveChildren(v ...*Todo) *TodoUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearCategory clears the "category" edge to the Category entity.
func (_u *TodoUpdateOne) ClearCategory() *TodoUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// ClearOwner clears the "owner" edge to the Category entity.
func (_u *TodoUpdateOne) ClearOwner() *TodoUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the TodoUpdate builder.
func (_u *TodoUpdateOne) Where(ps ...predicate.Todo) *TodoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TodoUpdateOne) Select(field string, fields ...string) *TodoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Todo entity.
func (_u *TodoUpdateOne) Save(ctx context.Context) (*Todo, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TodoUpdateOne) SaveX(ctx context.Context) *Todo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TodoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TodoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TodoUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := todo.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Todo.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Text(); ok {
		if err := todo.TextValidator(v); err != nil {
			return &ValidationError{Name: "text", err: fmt.Errorf(`ent: validator failed for field "Todo.text": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Todo.owner"`)
	}
	return nil
}

func (_u *TodoUpdateOne) sqlSave(ctx context.Context) (_node *Todo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(todo.Table, todo.Columns, sqlgraph.NewFieldSpec(todo.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Todo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, todo.FieldID)
		for _, f := range fields {
			if !todo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != todo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if err := entbuilder.ApplyUpdate(_u.config, _u.mutation, &todoUpdateDescriptor, _spec); err != nil {
		return nil, err
	}
	_node = &Todo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{todo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
