// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package gqlgo

import (
	"entgo.io/contrib/entgqlgo/internal/todosplit/ent"
	"github.com/graphql-go/graphql"
)

// Edge resolution helpers for graphql-go.
// These provide optimized edge resolution that checks for eager-loaded data first.

// CategoryTodosResolver resolves the todos edge for Category.
// It first checks if the edge was already loaded via eager loading.
// If not, it falls back to querying the database.
type CategoryTodosResolver struct {
	client *ent.Client
}

// NewCategoryTodosResolver creates a new resolver for the todos edge.
func NewCategoryTodosResolver(client *ent.Client) *CategoryTodosResolver {
	return &CategoryTodosResolver{client: client}
}

// Resolve implements the edge resolution for Category.todos.
func (r *CategoryTodosResolver) Resolve(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Category)
	if !ok {
		return nil, nil
	}

	// Check if edge was already loaded via eager loading
	if edges := source.Edges.Todos; edges != nil {
		return edges, nil
	}

	// Fall back to query
	return source.QueryTodos().All(p.Context)
}

// TodoParentResolver resolves the parent edge for Todo.
// It first checks if the edge was already loaded via eager loading.
// If not, it falls back to querying the database.
type TodoParentResolver struct {
	client *ent.Client
}

// NewTodoParentResolver creates a new resolver for the parent edge.
func NewTodoParentResolver(client *ent.Client) *TodoParentResolver {
	return &TodoParentResolver{client: client}
}

// Resolve implements the edge resolution for Todo.parent.
func (r *TodoParentResolver) Resolve(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}

	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Parent; edge != nil {
		return edge, nil
	}

	// Fall back to query
	return source.QueryParent().Only(p.Context)
}

// TodoChildrenResolver resolves the children edge for Todo.
// It first checks if the edge was already loaded via eager loading.
// If not, it falls back to querying the database.
type TodoChildrenResolver struct {
	client *ent.Client
}

// NewTodoChildrenResolver creates a new resolver for the children edge.
func NewTodoChildrenResolver(client *ent.Client) *TodoChildrenResolver {
	return &TodoChildrenResolver{client: client}
}

// Resolve implements the edge resolution for Todo.children.
func (r *TodoChildrenResolver) Resolve(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}

	// Check if edge was already loaded via eager loading
	if edges := source.Edges.Children; edges != nil {
		return edges, nil
	}

	// Fall back to query
	return source.QueryChildren().All(p.Context)
}

// TodoCategoryResolver resolves the category edge for Todo.
// It first checks if the edge was already loaded via eager loading.
// If not, it falls back to querying the database.
type TodoCategoryResolver struct {
	client *ent.Client
}

// NewTodoCategoryResolver creates a new resolver for the category edge.
func NewTodoCategoryResolver(client *ent.Client) *TodoCategoryResolver {
	return &TodoCategoryResolver{client: client}
}

// Resolve implements the edge resolution for Todo.category.
func (r *TodoCategoryResolver) Resolve(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}

	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Category; edge != nil {
		return edge, nil
	}

	// Fall back to query
	return source.QueryCategory().Only(p.Context)
}

// EdgeResolverMap provides a map of edge resolvers for all types.
type EdgeResolverMap struct {
	client *ent.Client
}

// NewEdgeResolverMap creates a new EdgeResolverMap.
func NewEdgeResolverMap(client *ent.Client) *EdgeResolverMap {
	return &EdgeResolverMap{client: client}
}

// CategoryTodos returns the resolver for Category.todos.
func (m *EdgeResolverMap) CategoryTodos() graphql.FieldResolveFn {
	return NewCategoryTodosResolver(m.client).Resolve
}

// TodoParent returns the resolver for Todo.parent.
func (m *EdgeResolverMap) TodoParent() graphql.FieldResolveFn {
	return NewTodoParentResolver(m.client).Resolve
}

// TodoChildren returns the resolver for Todo.children.
func (m *EdgeResolverMap) TodoChildren() graphql.FieldResolveFn {
	return NewTodoChildrenResolver(m.client).Resolve
}

// TodoCategory returns the resolver for Todo.category.
func (m *EdgeResolverMap) TodoCategory() graphql.FieldResolveFn {
	return NewTodoCategoryResolver(m.client).Resolve
}
