// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package gqlgo

import (
	"context"
	"encoding/json"
	"fmt"

	"entgo.io/contrib/entgqlgo/internal/todosplit/ent"
	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/category"
	"entgo.io/contrib/entgqlgo/internal/todosplit/ent/todo"
)

// Node in the graph.
type Node struct {
	ID     int      `json:"id,omitempty"`     // node id.
	Type   string   `json:"type,omitempty"`   // node type.
	Fields []*Field `json:"fields,omitempty"` // node fields.
	Edges  []*Edge  `json:"edges,omitempty"`  // node edges.
}

// Field of a node.
type Field struct {
	Type  string `json:"type,omitempty"`  // field type.
	Name  string `json:"name,omitempty"`  // field name (as in struct).
	Value string `json:"value,omitempty"` // stringified value.
}

// Edge between two nodes.
type Edge struct {
	Type string `json:"type,omitempty"` // edge type.
	Name string `json:"name,omitempty"` // edge name.
	IDs  []int  `json:"ids,omitempty"`  // node ids (where this edge point to).
}

// CategoryNode returns the Node descriptor for a Category.
func CategoryNode(ctx context.Context, n *ent.Category) (*Node, error) {
	node := &Node{
		ID:     n.ID,
		Type:   "Category",
		Fields: make([]*Field, 2),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	var err error
	if buf, err = json.Marshal(n.Name); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.ConfigType); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "category.ConfigType",
		Name:  "config_type",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Todo",
		Name: "todos",
	}
	if err := ent.QueryCategoryTodos(ent.NewCategoryClient(n.Config), n).
		Select(todo.FieldID).
		Scan(ctx, &node.Edges[0].IDs); err != nil {
		return nil, err
	}
	return node, nil
}

// FriendshipNode returns the Node descriptor for a Friendship.
func FriendshipNode(ctx context.Context, n *ent.Friendship) (*Node, error) {
	node := &Node{
		ID:     n.ID,
		Type:   "Friendship",
		Fields: make([]*Field, 0),
		Edges:  make([]*Edge, 2),
	}
	node.Edges[0] = &Edge{
		Type: "Todo",
		Name: "todo",
	}
	if err := ent.QueryFriendshipTodo(ent.NewFriendshipClient(n.Config), n).
		Select(todo.FieldID).
		Scan(ctx, &node.Edges[0].IDs); err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Category",
		Name: "category",
	}
	if err := ent.QueryFriendshipCategory(ent.NewFriendshipClient(n.Config), n).
		Select(category.FieldID).
		Scan(ctx, &node.Edges[1].IDs); err != nil {
		return nil, err
	}
	return node, nil
}

// TodoNode returns the Node descriptor for a Todo.
func TodoNode(ctx context.Context, n *ent.Todo) (*Node, error) {
	node := &Node{
		ID:     n.ID,
		Type:   "Todo",
		Fields: make([]*Field, 10),
		Edges:  make([]*Edge, 3),
	}
	var buf []byte
	var err error
	if buf, err = json.Marshal(n.Text); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "text",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.Status); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "todo.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.Priority); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "priority",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.Score); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "float64",
		Name:  "score",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.DueDate); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "time.Time",
		Name:  "due_date",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.Tags2); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "[]string",
		Name:  "tags2",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.Metadata); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "map[string]interface {}",
		Name:  "metadata",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.ExternalID); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "uuid.UUID",
		Name:  "external_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(n.Duration); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "int64",
		Name:  "duration",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Todo",
		Name: "parent",
	}
	if err := ent.QueryTodoParent(ent.NewTodoClient(n.Config), n).
		Select(todo.FieldID).
		Scan(ctx, &node.Edges[0].IDs); err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Todo",
		Name: "children",
	}
	if err := ent.QueryTodoChildren(ent.NewTodoClient(n.Config), n).
		Select(todo.FieldID).
		Scan(ctx, &node.Edges[1].IDs); err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "Category",
		Name: "category",
	}
	if err := ent.QueryTodoCategory(ent.NewTodoClient(n.Config), n).
		Select(category.FieldID).
		Scan(ctx, &node.Edges[2].IDs); err != nil {
		return nil, err
	}
	return node, nil
}

// NodeWithDescriptor returns the node descriptor with given global ID.
//
// This API is helpful in case you want to build
// an administrator tool to browse all types in the system.
func NodeWithDescriptor(client *ent.Client, ctx context.Context, id int) (*Node, error) {
	n, err := Noder_(client, ctx, id)
	if err != nil {
		return nil, err
	}
	switch v := n.(type) {
	case *ent.Category:
		return CategoryNode(ctx, v)
	case *ent.Friendship:
		return FriendshipNode(ctx, v)
	case *ent.Todo:
		return TodoNode(ctx, v)
	default:
		return nil, fmt.Errorf("unknown node type: %T", n)
	}
}
