// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package gqlgo

import (
	"context"

	"entgo.io/contrib/entgqlgo/internal/todosplit/ent"
	"github.com/graphql-go/graphql"
)

// GraphQL type definitions for ent types.
// These are generated to work with github.com/graphql-go/graphql.

// CustomInterfaces maps interface names referenced by entgqlgo.Implements
// annotations to their graphql.Interface definitions. Populate this map before
// building the schema (it is read lazily when graphql.NewSchema is called).
// Interface names referenced by Implements annotations but not present in
// this map are silently omitted from the type's interface list.
var CustomInterfaces = map[string]*graphql.Interface{}

// CustomTypes maps type names referenced by entgqlgo.Type annotations (for
// types that are not built-in GraphQL scalars, e.g. custom enums or scalars
// defined outside ent) to their graphql.Type definitions. Populate this map
// before building the schema. Names referenced by Type annotations but not
// present here fall back to graphql.String (see customTypeOr).
var CustomTypes = map[string]graphql.Type{}

// ExtraFields registers additional fields on generated object types — e.g. a
// computed field with a custom resolver (Deal.taskCount) that ent itself does
// not expose. Key by the GraphQL type name (e.g. "Todo", "Deal"); the value is
// merged into that type's field map when its FieldsThunk resolves.
//
// This is the supported extension seam for adding fields to generated object
// types: because those types are built with graphql.FieldsThunk, calling
// (*Object).AddFieldConfig on them after construction is a silent no-op. Populate
// ExtraFields before NewSchema / SchemaConfig is called (it is read lazily the
// first time the schema resolves each object's fields). Entries whose key does
// not match a generated type are ignored; an extra field whose name collides
// with a generated field overrides the generated one.
var ExtraFields = map[string]graphql.Fields{}

// mergeExtraFields overlays ExtraFields[typeName] onto fields and returns it. It
// is called from each generated object's FieldsThunk so consumer-registered
// fields participate in the schema exactly like generated ones.
func mergeExtraFields(typeName string, fields graphql.Fields) graphql.Fields {
	for name, f := range ExtraFields[typeName] {
		fields[name] = f
	}
	return fields
}

// WhereInputExtraFields registers additional GraphQL input fields on generated
// <Entity>WhereInput types — e.g. a custom predicate field (search: String) that
// ent itself does not expose. Key by the GraphQL where-input type name (e.g.
// "TodoWhereInput", "PropertyWhereInput"); the value is merged into that type's
// input-field map when its InputObjectConfigFieldMapThunk resolves.
//
// Because where-input types are built with InputObjectConfigFieldMapThunk,
// (*InputObject).AddFieldConfig after construction is a silent no-op. Populate
// WhereInputExtraFields before NewSchema / SchemaConfig is called (it is read
// lazily the first time the schema resolves each where-input's fields). Entries
// whose key does not match a generated where-input type are ignored; an extra
// field whose name collides with a generated field overrides the generated one.
//
// Use WhereInputParseHooks to give these fields runtime behaviour: the hook
// receives the raw GraphQL input map (where the extra field's value appears) and
// the typed where-input, and may mutate the typed input (e.g. add predicates).
var WhereInputExtraFields = map[string]graphql.InputObjectConfigFieldMap{}

// WhereInputParseHooks registers callbacks invoked by Parse<Entity>WhereInput
// after it builds the typed where-input. Hooks receive the request context, the
// raw GraphQL input map for that where-input, and the typed where-input (e.g.
// *ent.TodoWhereInput) as an interface{}, and may mutate it — typically reading
// a field declared via WhereInputExtraFields and calling the where-input's
// AddPredicates to route filtering. Key by the GraphQL where-input type name.
//
// Hooks run for nested where-inputs too: because Parse<Entity>WhereInput recurses
// into not/and/or/<edge>With, a hook registered for "TodoWhereInput" fires for a
// TodoWhereInput nested inside and: [...] just as it does at the top level.
// Populate before NewSchema / SchemaConfig is called.
var WhereInputParseHooks = map[string][]func(ctx context.Context, raw map[string]interface{}, whereInput interface{}) error{}

// runWhereInputHooks invokes the registered parse hooks for typeName in order,
// passing the raw GraphQL input map and the typed where-input. It is called at
// the end of each generated Parse<Entity>WhereInput (including nested calls).
func runWhereInputHooks(ctx context.Context, typeName string, raw map[string]interface{}, whereInput interface{}) error {
	for _, h := range WhereInputParseHooks[typeName] {
		if err := h(ctx, raw, whereInput); err != nil {
			return err
		}
	}
	return nil
}

// customTypeOr returns the registered custom type for name, or fallback if no
// such type has been registered in CustomTypes. graphql.Type satisfies both the
// graphql.Input and graphql.Output interfaces, so the result is usable for both
// input-object and output-object field configs.
func customTypeOr(name string, fallback graphql.Type) graphql.Type {
	if t, ok := CustomTypes[name]; ok && t != nil {
		return t
	}
	return fallback
}

var (
	// CategoryType is the GraphQL type for Category.
	CategoryType *graphql.Object
	// FriendshipType is the GraphQL type for Friendship.
	FriendshipType *graphql.Object
	// TodoType is the GraphQL type for Todo.
	TodoType *graphql.Object
)

func init() {
	CategoryType = graphql.NewObject(graphql.ObjectConfig{
		Name: "Category",
		Interfaces: graphql.InterfacesThunk(func() []*graphql.Interface {
			ifaces := []*graphql.Interface{NodeInterface}
			return ifaces
		}),
		Fields: graphql.FieldsThunk(func() graphql.Fields {
			return mergeExtraFields("Category", graphql.Fields{
				"name": &graphql.Field{
					Type: graphql.NewNonNull(graphql.String),
				},
				"configType": &graphql.Field{
					Type: CategoryConfigTypeEnum,
				},
				"id": &graphql.Field{
					Type:        graphql.NewNonNull(graphql.ID),
					Description: "The unique identifier of the Category.",
				},
				"todos": &graphql.Field{
					Type:    graphql.NewList(graphql.NewNonNull(TodoType)),
					Resolve: resolveCategoryTodos,
				},
			})
		}),
	})
	FriendshipType = graphql.NewObject(graphql.ObjectConfig{
		Name: "Friendship",
		Interfaces: graphql.InterfacesThunk(func() []*graphql.Interface {
			ifaces := []*graphql.Interface{NodeInterface}
			return ifaces
		}),
		Fields: graphql.FieldsThunk(func() graphql.Fields {
			return mergeExtraFields("Friendship", graphql.Fields{
				"id": &graphql.Field{
					Type:        graphql.NewNonNull(graphql.ID),
					Description: "The unique identifier of the Friendship.",
				},
				"todo": &graphql.Field{
					Type:    graphql.NewNonNull(TodoType),
					Resolve: resolveFriendshipTodo,
				},
				"category": &graphql.Field{
					Type:    graphql.NewNonNull(CategoryType),
					Resolve: resolveFriendshipCategory,
				},
			})
		}),
	})
	TodoType = graphql.NewObject(graphql.ObjectConfig{
		Name: "Todo",
		Interfaces: graphql.InterfacesThunk(func() []*graphql.Interface {
			ifaces := []*graphql.Interface{NodeInterface}
			return ifaces
		}),
		Fields: graphql.FieldsThunk(func() graphql.Fields {
			return mergeExtraFields("Todo", graphql.Fields{
				"text": &graphql.Field{
					Type: graphql.NewNonNull(graphql.String),
				},
				"status": &graphql.Field{
					Type: graphql.NewNonNull(TodoStatusEnum),
				},
				"priority": &graphql.Field{
					Type: graphql.Int,
				},
				"createdAt": &graphql.Field{
					Type: graphql.NewNonNull(TimeScalar),
				},
				"score": &graphql.Field{
					Type: graphql.Float,
				},
				"dueDate": &graphql.Field{
					Type: TimeScalar,
				},
				"tags2": &graphql.Field{
					Type: graphql.NewList(graphql.NewNonNull(graphql.String)),
				},
				"metadata": &graphql.Field{
					Type: customTypeOr("Map", graphql.String),
				},
				"externalID": &graphql.Field{
					Type: customTypeOr("UUID", graphql.ID),
				},
				"duration": &graphql.Field{
					Type: graphql.Int,
				},
				"id": &graphql.Field{
					Type:        graphql.NewNonNull(graphql.ID),
					Description: "The unique identifier of the Todo.",
				},
				"parent": &graphql.Field{
					Type:    TodoType,
					Resolve: resolveTodoParent,
				},
				"children": &graphql.Field{
					Type:    graphql.NewList(graphql.NewNonNull(TodoType)),
					Resolve: resolveTodoChildren,
				},
				"category": &graphql.Field{
					Type:    CategoryType,
					Resolve: resolveTodoCategory,
				},
			})
		}),
	})
}

// resolveCategoryTodos resolves the todos edge for Category.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveCategoryTodos(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Category)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edges := source.Edges.Todos; edges != nil {
		return edges, nil
	}
	// Fall back to query
	return ent.QueryCategoryTodos(ent.NewCategoryClient(source.Config), source).All(p.Context)
}

// resolveFriendshipTodo resolves the todo edge for Friendship.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveFriendshipTodo(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Friendship)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Todo; edge != nil {
		return edge, nil
	}
	// Fall back to query
	edge, err := ent.QueryFriendshipTodo(ent.NewFriendshipClient(source.Config), source).Only(p.Context)
	if err != nil {
		// For optional edges, not found is not an error - return nil
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return edge, nil
}

// resolveFriendshipCategory resolves the category edge for Friendship.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveFriendshipCategory(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Friendship)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Category; edge != nil {
		return edge, nil
	}
	// Fall back to query
	edge, err := ent.QueryFriendshipCategory(ent.NewFriendshipClient(source.Config), source).Only(p.Context)
	if err != nil {
		// For optional edges, not found is not an error - return nil
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return edge, nil
}

// resolveTodoParent resolves the parent edge for Todo.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveTodoParent(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Parent; edge != nil {
		return edge, nil
	}
	// Fall back to query
	edge, err := ent.QueryTodoParent(ent.NewTodoClient(source.Config), source).Only(p.Context)
	if err != nil {
		// For optional edges, not found is not an error - return nil
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return edge, nil
}

// resolveTodoChildren resolves the children edge for Todo.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveTodoChildren(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edges := source.Edges.Children; edges != nil {
		return edges, nil
	}
	// Fall back to query
	return ent.QueryTodoChildren(ent.NewTodoClient(source.Config), source).All(p.Context)
}

// resolveTodoCategory resolves the category edge for Todo.
// It checks if the edge was already eager-loaded to avoid N+1 queries.
func resolveTodoCategory(p graphql.ResolveParams) (interface{}, error) {
	source, ok := p.Source.(*ent.Todo)
	if !ok {
		return nil, nil
	}
	// Check if edge was already loaded via eager loading
	if edge := source.Edges.Category; edge != nil {
		return edge, nil
	}
	// Fall back to query
	edge, err := ent.QueryTodoCategory(ent.NewTodoClient(source.Config), source).Only(p.Context)
	if err != nil {
		// For optional edges, not found is not an error - return nil
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}
	return edge, nil
}
